### ISSUE TITLE
excel-web-16.00.js served by the content delivery network (CDN) is different than the one on GitHub

### ISSUE THREAD

**Issue by sedano** [OfficeDev/office-js#1222]
We started having issues with IE since few days ago, all the exceptions happening in `excel-web-16.00.js`. Our add-in was unchanged so we believe the culprit is `office.js`/`excel-web-16.js` but cannot see any changes to these files in the release branch so we cannot properly identify the root cause.

We discovered that [excel-web-16.00.js](https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js) served by the CDN differs from [excel-web-16.00.js](https://raw.githubusercontent.com/OfficeDev/office-js/release/dist/excel-web-16.00.js) in this repo. It's our understanding that it should be the same.

> A repo and NPM package for Office.js, corresponding to a copy of what gets published to the official "evergreen" Office.js CDN, at https://appsforoffice.microsoft.com/lib/1/hosted/office.js.

## Expected Behavior
Unknown, but we believe `excel-web-16.00.js` served by CDN and `excel-web-16.00.js` present in release branch should be the same.

Only thing we could find are [many new branches](https://github.com/OfficeDev/office-js/branches/active) created few days ago that coincide when we started having problems.

## Current Behavior
There are many differences between the files, the most obvious are the versions inside the files.

On GitHub we have the following 
```
// Sources:
// osfweb: 16.0\12322.10000
// runtime: 16.0.12306.30007
// core: 16.0\12322.10000
// host: 16.0\12322.10000
```

On the CDN we have
```
// Sources:
// osfweb: 16.0\12914.10000
// runtime: 16.0\12914.10000
// core: 16.0\12914.10000
// host: 16.0\12914.10000
```

When using `excel-web-16.00.debug.js` the errors we get in  IE11 are not present.
On the CDN we get:
```
// Sources:
// osfweb: 16.0\12828.10000
// runtime: 16.0.12728.30001
// core: 16.0\12830.10000
// host: 16.0\12830.10000
```

## Steps to Reproduce, or Live Example
Launching any Excel add-in that loads the following script:
`<script src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>`

## Context
The specific error we are getting is:
![image](https://user-images.githubusercontent.com/1914004/84757274-3c662780-afc4-11ea-8f8a-e37148819b3f.png)

Seems to be connected to splitting the request headers:
![image](https://user-images.githubusercontent.com/1914004/84762007-8a7e2980-afca-11ea-803c-7e64b5b018e4.png)

Our add-in is not working since `excel-web-16.00.js` throws the exception when we try to perform any REST API request. Knowing  what were the changes between the  file present in the repo and the one in the CDN would help us  pinpoint the root cause.

We suspect it could be changes in the fetch polyfill or the request logic included in `excel-web-16.00.js` but we don't know which and when this changes were introduced.

It's important to mention that on Windows Excel Desktop it works fine when using WebView based on IE. Only Office Web is affected.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Office Online IE 11
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 0.0.0.0 Excel API  1.11
* Operating System: Windows 10
* Browser (if using Office Online): IE 11.3750.14393.0

## Useful logs
- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by sumurthy** [comment]
Thanks for reporting this issue. Could you be more specific on when you started to experience the issue? Date?
Also, you mentioned that it fails when making an REST API call. Are you able to observe that such a call is failing on your end consistently? 
Is your add-in available on the store for us to try/re-pro?
We did make an update to the CDN on June 9th, but it was backed out due to an unrelated issue. It may be worthwhile to remove all cache and try this again. 
The Github version is updated few days after the CDN is refreshed.

**Comment by MandytMSFT** [comment]
@sedano We recently have a JS minifier issue on office.js . The fix has been deployed to https://appsforoffice.microsoft.com/lib/1/hosted/ this afternoon , could you have a try to see if the issue has gone ? Or can you try https://appsforoffice.microsoft.com/lib/1/hosted/office.debug.js which wasn't minified to see if it works ?

**Comment by sedano** [comment]
> Thanks for reporting this issue. Could you be more specific on when you started to experience the issue? Date?
> Also, you mentioned that it fails when making an REST API call. Are you able to observe that such a call is failing on your end consistently?
> Is your add-in available on the store for us to try/re-pro?
> We did make an update to the CDN on June 9th, but it was backed out due to an unrelated issue. It may be worthwhile to remove all cache and try this again.
> The Github version is updated few days after the CDN is refreshed.

Thank you for the quick reply. We are currently doing validation of our Excel add-in, we tested IE11 the 4th of June and it was working fine. We repeated the same testing on June 15th and the issue appeared. It was with the same Excel add-in and testing environment.

I cannot share the code/add-in but I will try to create one add-in to replicate the issue. Basically, what we are doing is checking if the user is authenticated by making a GET request just after `Office.onReady()`. We have a polyfill in our app ([whatwg-fetch](https://github.com/whatwg/fetch)) to support fetch in IE11. What we believe happens is that the fetch polyfill is overwritten by the one included in `excel-web-16.00.js` and this one fails while splitting headers. This error is unhandled and our add-in crashes.

**Comment by sedano** [comment]
@MandytMSFT when I used the debug version yesterday it worked fine. Will try again with hosted and come back to you.

**Comment by MandytMSFT** [comment]
@sedano  great, that's proved it caused by the JS minifier. Just be noted, the CDN cache refreshing may need about 24 hours

**Comment by sedano** [comment]
@MandytMSFT @sumurthy We tested today again and we are still having the same issue. I don't know if the CDN cache was refresh already. Anyway, I created an add-in based on the yeoman office-generator where the issue can be reproduced.

We have a live version hosted it in one of our servers, here is the [manifest](https://github.com/sedano/cdn-excel-add-in/blob/master/cdn-manifest.xml).

Repo for the project: https://github.com/sedano/cdn-excel-add-in

Here is the error we get in IE11
![image](https://user-images.githubusercontent.com/1914004/85018040-ca7d1200-b16c-11ea-91a6-0427f00669fa.png)

**Comment by MandytMSFT** [comment]
@sedano  My fault, the fix deployed yesterday was only available for Microsoft internal. I am confirming with related people on progress for public user.

**Comment by sedano** [comment]
@MandytMSFT do you have any news regarding the issue? When will the updated file be available on the CDN?

**Comment by MandytMSFT** [comment]
@sedano  i didn't get accurate date from partner team. But i saw the hotfix has been included in next deployment which ideally will be happened in coming days.  Does this block you given debug version works well ?

**Comment by MandytMSFT** [comment]
@sedano  The new office js has been deployed 8 hours ago , you can have a try to see if it works.  Note that the CDN cache may take time to update.

**Comment by sedano** [comment]
@MandytMSFT We tested today and everything is working fine. Thank you for your help.
