### ISSUE TITLE
Not able to use showGridlines property of Worksheet Object

### ISSUE THREAD

**Issue by siddharthashw** [OfficeDev/office-js#142]
Not able to use **showGridlines** property of Worksheet Object

## Expected Behavior
On sets of worksheet's gridlines flag to false, Grid Lines of that sheet should disappear

## Current Behavior
On sets of worksheet's  gridlines flag to false, Grid Lines of that sheet should are not disappearing and even on 

## Steps to Reproduce, or Live Example

``` js
Excel.run(function(context) {
  var sheet = context.workbook.worksheets.getItem("Sheet1");
  sheet.showGridlines = false;
  return context.sync();
}).catch(function(error) {
  console.log("Error: " + error);
  if (error instanceof OfficeExtension.Error) {
    console.log("Debug info: " + JSON.stringify(error.debugInfo));
  }
});
```

* Additional details:
I have taken reference from [Worksheet Object (JavaScript API for Excel)](https://github.com/OfficeDev/office-js-docs/blob/master/reference/excel/worksheet.md)

## Context
Not able to get or set the showGridlines property.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1804 (Build 9226.2126)
* Operating System: windows10
* Browser (if using Office Online): No

**Comment by JuaneloJuanelo** [comment]
thanks for reporting this. i was able to repro. seems to be that the method is not in Office.js production CDN. We'll fix it soon.

@Rick-Kirkham the script lab sample is broken as it has the old name of the API.

**Comment by Rick-Kirkham** [comment]
@JuaneloJuanelo The sample is fixed, but a bug in the system for updating the snippets in Script Lab is blocking all changes.

**Comment by siddharthashw** [comment]
thanks @JuaneloJuanelo for your response. Hope to get this fix soon 👍

**Comment by JuaneloJuanelo** [comment]
turns out this specific API was removed from 1.7 due to a name change. Good news is that the 1.8 release will come soon, so for now its about waiting for the next release, or use it in the beta CDN.

**Comment by jpc1976** [comment]
I am using Excel API v1.8 and I still have the same problem. Property 'showGridlines' does not seem to be available in Excel.Worksheet, despite what the documentation specifies. 

Any help appreciated!

**Comment by Zlatkovsky** [comment]
Re-opening and assigning to @JuaneloJuanelo to investigate.

**Comment by Zlatkovsky** [comment]
Actually, in the StackOverflow, looks like the issue has been resolved after all:

> After some digging around, I found the solution, so I'll answer my own question. I am using TypeScript instead of vanilla JavaScript, which means that when using Office.js the "type definitions" must be locally present in a file called Office.d.ts at the root of the project. The procedure is described here: docs.microsoft.com/en-us/office/dev/add-ins/develop/… – jp76 Dec 26 at 16:24
