### ISSUE TITLE
Office.context.mailbox.item.body.getTypeAsync get 5001 error on Mac

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1499]
When trying call : 
Office.context.mailbox.item.body.getTypeAsync(function (result) {
                    if (result.status == Office.AsyncResultStatus.Failed){
                        zopLog("getBodyType: Office.AsyncResultStatus.Failed:"+result.status);
                        //...
                    }
                    else {
                        //...
                    }
                });
Get result: failed :error code: 5001 error message: internal error ...

This problem only happened on 
Mac: 10.15.7
Outlook: 16.44 (20111100)
And some users can fix this by reinstall outlook. But this not work every time.

But it works fine on browser.

## Expected Behavior
Api can work normally.

## Current Behavior
Api not work so that add-in can't insert any content to body.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.44 (20111100)
* Operating System: Mac 10.15.7
* Browser (if using Office on the web): NA

I see some one mentioned this on https://github.com/OfficeDev/office-js/issues/826.
Is this callback handler register is necessary?

**Comment by SWei1234** [comment]
Hi @exextoc 
More and more user met this problem. Any idea?
Thanks

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in build 16.44(20111502) or later.When an update build is available depends on the release channel a customer is on

**Comment by SWei1234** [comment]
Thanks @exextoc

**Comment by SWei1234** [comment]
Hi @exextoc 
We have user can update to 16.44.20112300 . Did this version fixed this problem?
Thanks

**Comment by exextoc** [comment]
Yes, version 16.44.20112300 should have the fix.

**Comment by SWei1234** [comment]
Hi @exextoc 
But it looks users who update to '16.44.20112300' still have this problem. Report 5001. Will update to newer version be helpful. 
For example, update version in  'inside faster' mode.
Also tried update to beta version '16.44 (20112309)' . But not fix this problem. This problem might not fixed in this channel...
Thanks

**Comment by shff** [comment]
I'm on 16.45 (20120106) beta and it's still happening.

**Comment by shff** [comment]
Updated today to 16.45 (20121303) and it's also still broken for me.

The error happens after I call `body.setAsync`... after that I can't call any getter functions.

The only workaround is to ask the end-user to select the email again in the "From" field, even if it's already selected.

**Comment by exextoc** [comment]
Hey guys,

The issue with body API failing consistently has been fixed and should be available in the December build update 16.44 (20121301) and later. About the getter functions failing, can you share some repro steps, and if possible- a manifest where this issue is reproducible? That would really help us with our investigation.

**Comment by SWei1234** [comment]
Hi @exextoc 
We have tried this on zoom add-in. 
Steps is open zoom then open dev-tool-> console->call 'Office.context.mailbox.item.body.getTypeAsync' 
And then get this error.

**Comment by exextoc** [comment]
Hi @SWei1234 , we were not able to reproduce this error on the latest Outlook. Have you tried updating to 16.44 (20121301) or later, on the Insider Fast channel?

**Comment by ndvbd** [comment]
Same issue here. Error 5001 on Outlook 16.47 for Mac
