### ISSUE TITLE
Charts functions issues on iPad - axis min/max, markers, ticks, second axis, reversePlotOrder

### ISSUE THREAD

**Issue by alexuaua** [OfficeDev/office-js#1688]
I've issues with charts related API on iPad. The earlier bug that caused a crash when assigning a marker style is fixed with v2.46 (thank you), but we have issues with axis related chart API methods.
I've checked the [Excel API Requirement sets page](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets) and it says that Excel for iPad v16.40+ should support API 1.12 but even some API 1.8 functions fail (like using `axisGroup?: Excel.ChartAxisGroup` property).
I have gist code that build two charts with multiple methods that do work.

API that does not work as expected:
* ChartSeries.axisGroup?: Excel.ChartAxisGroup

## Expected Behavior
Charts produced by the code in Excel for Mac 2016 / Excel 2016 for Windows as well as in Excel 2019, latest Office 365.
<img width="401" alt="excelMac2016" src="https://user-images.githubusercontent.com/8337308/109762514-b3793580-7bbe-11eb-8512-c23b2184b761.png">

## Current Behavior
Results for "production" code.
![ipad-best](https://user-images.githubusercontent.com/8337308/109877644-46f34a80-7c41-11eb-98c9-db5daa2471fa.png)
(I'm trying to reproduce this chart above with a simple code and I will add a gist, unfortunately loading scrips using add-in on iPad requires  more time).

## Steps to Reproduce, or Live Example

_UPDATE:_ I've created much simpler script with more "atomic" requests and only one chart. The script works with any desktop Excel (tested from Excel 2016 up to insider Office 365) and works on online (except for... markerStyles), but fails to set up secondary axis group on iPad.

https://gist.github.com/alexuaua/6404d44ea6c496a5e2b2faac3747ef73

1) New script fails on a markerStyle statement for the second series XYScatterplot (it's a bit strange, because [when used with line - the bug was already fixed](https://github.com/OfficeDev/office-js/issues/1538)),
2) And when I try to set up the second axis group.
![IMG_0518](https://user-images.githubusercontent.com/8337308/109897942-72862d00-7c61-11eb-89dc-d9a8f99ab326.jpg). 
Probably ignored hidden ticks are result of (2). 
3) I'm checking if reversePlotOrder works with very simple chart with one axis group, but it failed within this script.

--- 
Old and complicated script:
I've extracted chart preparation method and tried to make it smaller as possible. But the chart data is separated from plotting procedure to make it easier to test with two different chart types - combined scatter + columns (method `function addchart1()`) and regular scatter plot (`function addchart2()`). 

https://gist.github.com/alexuaua/bb42d5147b10e65edb1b8a5e41080cda

For the first chart it does not matter if you start with columns and add a XY scatter plot or vice verse. I've separated two method that write test data into a sheet `writeArrayStringToColumn()` and `writeArrayDoubleToColumn()` to test with different data (much easier to paste array from JSON as [1,2,3] vs [[1],[2],[3] when chart is by columns).

All the code before line ~250 is based on working code as well as other snippets, and all the series and axes formatting happens in ParseSeriesAxes() – at first I write test data to a sheet and pass it to series `setValues(), setXAxisValues()`, then I assign `markerStyle, markerSize` and `format.line.color, lineStyle`.
For some reason setting  markerStyle to Excel.ChartMarkerStyle.none is ignored on iPad.

But the worst part starts at `CreateAxisGroup()` – even for simple scatter plot with only one axis group (only primary X + Y) Excel for iPad ignores _axis minimum and maximum values, reversePlotOrder_*flag, title, as well as series and markers colors (while it looks like when smth goes wrong, following code is simply ignored).
Also ticks and title cannot be hidden (to hide the whole axis).

I've tried to add and wait for context.sync() after almost all lines (ie. making changes of axis parameters step-by-step),  but didn't got any noticeable difference. I've also tried remote logging, but have not got any exceptions.

## Context
Excel for iPad supports API 1.12 but some chart related features from API 1.8 and 1.9 fail.
Simple scatter plots ignore axis parameters (ticks, axis min/max). Combined chart ignores second axis parameters (min/max). 
Markers ignore foreground/background color (there is also no  support for transparent color, but this is probably is a feature request and not a bug).

## Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: iOS (iPad)
Host [Excel, Word, PowerPoint, etc.]: Excel
Office version number: 2.46
Operating System: iOS 14.2 or 14.0

**Comment by AlexJerabek** [comment]
Thanks for reporting this @alexuaua. 

Tagging @lumine2008 to investigate.

**Comment by alexuaua** [comment]
@AlexJerabek  I've created much simpler script with more atomic requests (for better debug) and only one chart. The script works well with any desktop Excel (tested from Excel 2016 up to insider Office 365), and works in Excel online (thanks for ScriptLab for Excel online) except for `markerStyles`, but fails with markerStyles and axis related methods on iPad.

https://gist.github.com/alexuaua/6404d44ea6c496a5e2b2faac3747ef73

In short:
1) New script fails on a markerStyle statement for the second series XYScatterplot (it's a bit strange, because [when used with line - the bug was already fixed](https://github.com/OfficeDev/office-js/issues/1538)),

2) It fails when I try to set up the second axis group.
![IMG_0518](https://user-images.githubusercontent.com/8337308/109897942-72862d00-7c61-11eb-89dc-d9a8f99ab326.jpg). 
Probably ignored hidden ticks are result of (2). 
`
["error",{"code":"InvalidArgument","message":"The argument is invalid or missing or has an incorrect format.","toString":"[object Function]","errorLocation":"ChartAxis.position","statement":"item.position = ...;","surroundingStatements":["...","var item = axes.getItem(...);","var title = item.title;","title.visible = ...;","title.text = ...;","item.setCategoryNames(...);","// >>>>>","item.position = ...;","// <<<<<","item.visible = ...;","var item1 = axes.getItem(...);","var title1 = item1.title;","title1.visible = ...;","title1.text = ...;","..."],"fullStatements":["var workbook = context.workbook;","var worksheets = workbook.worksheets;","var worksheet = worksheets.getItem(\"{35B82B2F-B4F3-264E-860B-59D55A2847B5}\") /* originally add() */;","var cell = worksheet.getCell(0, 15);","// Instantiate {cell}","var absoluteResizedRange = cell.getAbsoluteResizedRange(5, 1);","// Instantiate {absoluteResizedRange}","absoluteResizedRange.values = [[\"4 To 6\"],[\"6 To 8\"],[\"8 To 10\"],[\"10 To 12\"],[\"12+\"]];","var charts = worksheet.charts;","var chart = charts.getItem(\"{FCE94440-ED62-F741-B59B-B8D1B86E0989}\") /* originally add(\"ColumnClustered\", v, \"Columns\") */;","var axes = chart.axes;","var item = axes.getItem(\"Category\", \"Primary\");","var title = item.title;","title.visible = true;","title.text = \"Bin\";","item.setCategoryNames(absoluteResizedRange);","item.position = \"Minimum\";","item.visible = true;","var item1 = axes.getItem(\"Value\", \"Primary\");","var title1 = item1.title;","title1.visible = true;","title1.text = \"Count\";","item1.minimum = 0;","item1.maximum = 3.5;","item1.position = \"Minimum\";","item1.reversePlotOrder = true;"]}]`

3) I'm checking if reversePlotOrder works with very simple chart with one axis group, but it failed within this script.

**Comment by lumine2008** [comment]
Yes, some Axie API doesnt work for iOS, A bug 4922579 was logged to track this issue.

**Comment by joshuawwright** [comment]
@lumine2008 I am seeing this issue also on Windows and Excel Online. Here is script lab gist for reproduction:
[https://gist.github.com/DesertFoxNV/c90e76bc2c183505b0a55a29345af3a8](https://gist.github.com/DesertFoxNV/c90e76bc2c183505b0a55a29345af3a8)

Fails on the following environments:
Windows Office Version 16.013801.20266
Excel Online

On Windows if I revert to 16.013628.20448, the gist works as expected.

**Comment by MiaofeiWang** [comment]
@alexuaua Thanks for helping us find the bug. The `markerStyles` issue on XYScatter chart should have been fixed on Windows/Mac/~~Online~~, except iPad. Please let us know if not.

For the Axis issues, we confirmed that there is a bug when setting Axis.position on iPad. But the other Axis APIs (Axis.reversePlotOrder, Axis.title, Axis.minimum and Axis.maximum) work fine on my machine. Could you please remove the line `x.position = Excel.ChartAxisPosition.minimum` and try the other Axis APIs again on iPad?

**Comment by joshuawwright** [comment]
@MiaofeiWang I just tested Excel Online again with the following gist: [https://gist.github.com/DesertFoxNV/c90e76bc2c183505b0a55a29345af3a8](https://gist.github.com/DesertFoxNV/c90e76bc2c183505b0a55a29345af3a8). Unfortunately, I am still getting the following error:

> [ERROR]: Error:
{
    "stack": "RichApi.Error: This operation is not permitted for the current object.\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:303333)\n    at n.i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:365151)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:363256",
    "message": "This operation is not permitted for the current object.",
    "name": "RichApi.Error",
    "code": "InvalidOperation",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "InvalidOperation",
        "message": "This operation is not permitted for the current object.",
        "errorLocation": "ChartSeries.markerStyle",
        "statement": "add2.markerStyle = ...;",
        "surroundingStatements": [
            "...",
            "var series = add.series;",
            "var add1 = series.add(...);",
            "add1.markerStyle = ...;",
            "add1.axisGroup = ...;",
            "var add2 = series.add(...);",
            "// >>>>>",
            "add2.markerStyle = ...;",
            "// <<<<<",
            "add2.axisGroup = ...;"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 400
}

**Comment by MiaofeiWang** [comment]
@DesertFoxNV Sorry for my typo. The markerStyle issue is not fixed yet on Excel online which will take a few more days.

**Comment by MiaofeiWang** [comment]
@alexuaua This issue should be fixed on all platforms (for iOS, the Office build is 2.49). Could you try it again?
I will close this case and please re-activate it if still repro.

**Comment by alexuaua** [comment]
@MiaofeiWang , sorry, I missed the notification. 
Unfortunately, second axis group and other parameters are still being ignored on Excel online as well as on iPad.

**Comment by MiaofeiWang** [comment]
@alexuaua sorry to know that. But I tried your gist https://gist.github.com/alexuaua/6404d44ea6c496a5e2b2faac3747ef73 on Excel Online and below is the result which is same with that on Excel Windows. 
![image](https://user-images.githubusercontent.com/28795134/132330522-6daf6004-1a7a-40dd-adbf-fdf327c95671.png)

Could you provide more information about the error you meet?

**Comment by MiaofeiWang** [comment]
@alexuaua I tried again on Excel iPad: the result is same with that on Excel Windows and Excel Online. My Excel build on iPad is Version 2.55 (21102904). 
Close this case as fixed.
![image](https://user-images.githubusercontent.com/28795134/141414832-02c482d9-751b-490a-961d-ea9651892267.png)
