### ISSUE TITLE
Windows Excel, errors with markerStyle, axes max and min, scaletype "logarithmic"

### ISSUE THREAD

**Issue by elariccc** [OfficeDev/office-js#1729]
After Update Release 16.0.13721.35451 (#1640) we have errors with assigning to chart properties such as markerStyle, axes max and min, logarithmic type of chart.

## Expected Behavior

![image](https://user-images.githubusercontent.com/66617789/111463022-2d1d3180-8730-11eb-876d-fe8f450b1566.png)
![image](https://user-images.githubusercontent.com/66617789/111463203-5fc72a00-8730-11eb-83e9-665a93e5dfdf.png)

Before the update those worked fine

## Current Behavior

Assigning 'none' to markerStyle throws this exception
![image](https://user-images.githubusercontent.com/66617789/111463616-d5cb9100-8730-11eb-9340-151d4564836d.png)

Assigning other values works fine

Assigning max min to axes and scaletype "logarithmic" throws this:
![image](https://user-images.githubusercontent.com/66617789/111463821-0f9c9780-8731-11eb-8107-3dec14f57dd6.png)

## Steps to Reproduce, or Live Example

I can provide you more details if needed, but i can't share whole application, because it's for internal use

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2016, 2019, 365
* Operating System: Windows

**Comment by lindalu-MSFT** [comment]
@lumine2008 Seems to me there are other issues with Chart objects. Is this a dupe of another issue that's in the backlog?

**Comment by lumine2008** [comment]
it seems i cannot repro this issue, could you please share your gist? i have tried on this version. 

![image](https://user-images.githubusercontent.com/26398035/111765898-deae9500-88df-11eb-85e4-d74dd8650505.png)

**Comment by elariccc** [comment]
@lumine2008 I reproduced this bug in simple visual studio 2019 project https://github.com/elariccc/bugReproduce.

You will find script with issue in home.js, function highlightHighestValue. I've commented lines that throws exceptions. 

1) In case of logarythmic type of axis, minimum of axis between 0 and 1 throws exception.
![image](https://user-images.githubusercontent.com/66617789/112042419-88985680-8b58-11eb-9ac9-b5c2f662b88c.png)

2) I pass active cell as sourceData to create new chart. In my project i do it in purpose to pass empty cell as argument to create chart without series. When i select empty active cell, setting markekstyle to 'None' throws exceptions. Setting to other values seems to work fine. When non-empty active cell is selected, this line works fine too.
![image](https://user-images.githubusercontent.com/66617789/112043096-576c5600-8b59-11eb-8fbd-826458ea3c24.png)

Several weeks ago this code worked fine

**Comment by joshuawwright** [comment]
Office Version: 16.013801.20266 and Excel Online

I experience this issue when using secondary axis groups:

Script Lab Gist: [https://gist.github.com/DesertFoxNV/c90e76bc2c183505b0a55a29345af3a8](https://gist.github.com/DesertFoxNV/c90e76bc2c183505b0a55a29345af3a8)

**Reproduction Steps**
1) Create a new chart 
`const chart = sheet.charts.add(
          Excel.ChartType.xyscatter,
          sheet.getRange("A1:B11"),
           Excel.ChartSeriesBy.columns
        );`
2) Add a second series
`const series2 = chart.series.add('series 2');
        series2.set({
          axisGroup: Excel.ChartAxisGroup.secondary,
          markerStyle: Excel.ChartMarkerStyle.circle 
        })`
3) Add a 3rd series using the secondary Axis Group and a marker style.
`const series3 = chart.series.add('series 3');
        series3.set({
          axisGroup: Excel.ChartAxisGroup.secondary,
          markerStyle: Excel.ChartMarkerStyle.circle
        })`

The 3rd series produces the error whenever the `axisGroup` is set to `Excel.ChartAxisGroup.secondary` and is combined with any other property.

Reverting to 16.0.13628.20448 on Windows fixes the issue temporarily for me.

**Comment by MiaofeiWang** [comment]
@elariccc For logarithmic type of axis, it is by design that the minimum value for `Axis.minimum` is 1. We think that logarithmic curve shouldn't have X value smaller than 1 although it is not limited yet on Excel client.

For the markerStyle issue on XYScatter chart, it should have been fixed on Excel Windows (no need to reverting to old build). Could you please help try that again?

**Comment by joshuawwright** [comment]
@MiaofeiWang I am still seeing an issue on Excel Online using the gist [https://gist.github.com/DesertFoxNV/c90e76bc2c183505b0a55a29345af3a8](https://gist.github.com/DesertFoxNV/c90e76bc2c183505b0a55a29345af3a8). Is it only fixed on Windows?

> [ERROR]: Error:
{
    "stack": "RichApi.Error: This operation is not permitted for the current object.\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:303333)\n    at n.i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:365151)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:363256",
    "message": "This operation is not permitted for the current object.",
    "name": "RichApi.Error",
    "code": "InvalidOperation",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "InvalidOperation",
        "message": "This operation is not permitted for the current object.",
        "errorLocation": "ChartSeries.markerStyle",
        "statement": "add2.markerStyle = ...;",
        "surroundingStatements": [
            "...",
            "var series = add.series;",
            "var add1 = series.add(...);",
            "add1.markerStyle = ...;",
            "add1.axisGroup = ...;",
            "var add2 = series.add(...);",
            "// >>>>>",
            "add2.markerStyle = ...;",
            "// <<<<<",
            "add2.axisGroup = ...;"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 400
}

**Comment by MiaofeiWang** [comment]
@DesertFoxNV Only on Windows and Mac for now. The fix on Excel Online and iPad will take a few more days.

**Comment by MiaofeiWang** [comment]
@DesertFoxNV This has been fixed on Excel Online with build >= 16.0.14012.37951.

**Comment by lumine2008** [comment]
Thanks Miaofei, let me put the bug (#4984713) here for future reference.

**Comment by lumine2008** [comment]
@elariccc would you please validate if this issue still repro?

**Comment by lumine2008** [comment]
Kindly reactive this issue if you still repro, thanks
