### ISSUE TITLE
Add-in iframe does not allow storage access API activation

### ISSUE THREAD

**Issue by siseli** [OfficeDev/office-js#1822]
Our office addin (Outlook) uses cookies for autentication.
Certain browsers (Safari always, Firefox optionally) block third party cookies.
Thesee browsers feature the Storage Access API (https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API) which contains the `requestStorageAccess()` function to allow third party cookies.

Unfortunately the storage access API only works if the add-in iframe has the `allow-storage-access-by-user-activation` token set in its `sandbox` attribute. 

## Expected Behavior
Outlook should set the `allow-storage-access-by-user-activation` token in the `sandbox` attribute for addin iframes.
This would allow the addin code to use the storage access API to be able to use cookies in browsers with strict tracking prevention (Safari, Firefox).

## Current Behavior
Outlook sets several `sandbox` tokens, but not `allow-storage-access-by-user-activation`, which makes Addins that rely on cookies for authentication completely unusable on Safari.

**Comment by exextoc** [comment]
We are unable to reproduce this issue on our end. Could you please provide us a sample add-in via email to our mail id admin@M365x010952.onmicrosoft.com so that we could reproduce it in-house?

**Comment by exextoc** [comment]
@siseli We have pushed a fix which will take a week or so to be available. Please try your scenario by 17th or 18th May to check if things work for you.

**Comment by siseli** [comment]
Thx. will report back here, if it solves our issue.

**Comment by exextoc** [comment]
@siseli Is the issue resolved?

**Comment by siseli** [comment]
No, I don't see any change in the addin iframe (yet).
Still no `allow-storage-access-by-user-activation` value in the `sandbox` attribute.

Checked just now on https://outlook.office.com.

**Comment by siseli** [comment]
@exextoc can we still expect a fix being pushed to outook? 
could you please reopen the ticket as the issue is not solved yet.

**Comment by exextoc** [comment]
Apologies for providing incorrect information earlier. Fix is still rolling out and we will provide update on this soon.

**Comment by siseli** [comment]
any news on this? is the change still expected to be rolled out anytime soon?

**Comment by exextoc** [comment]
@siseli  Apologies for the delay. The fix should be available globally within two weeks. We will update this thread once the fix is out.

**Comment by jscoder1009** [comment]
facing same issue on Microsoft Word windows and when opening Add-in in web word instance. Our application is built on Angular 12.

 "@angular/core": "~12.0.1",
  "@azure/msal-angular": "^2.0.4",
  "@azure/msal-browser": "^2.18.0",

Error while parsing the 'sandbox' attribute: 'allow-storage-access-by-user-activation' is an invalid sandbox flag. 

I can confirm app works when loaded as side-loaded Add-in in Mac Native Word. 

We are using redirect way of PKCE implementation in Angular application

**Comment by tanmay-joshi-tfs** [comment]
I see this error too when I try side-loading oneNote add-in in chrome.
