### ISSUE TITLE
Excel Content Pane App UI becomes frozen after Windows Resume

### ISSUE THREAD

**Issue by david-ps** [OfficeDev/office-js#2094]
There appears to be recent changes to the way the Content Pane is managed as a Shape that causes the UI to become frozen on Windows Resume or when the Excel/Content Pane App is idle for some time.

## Environment
Platform: PC
Host : Excel
Office version number Microsoft 365 MSO 16.0.14228.20200
Operating System: Windows 10

## Expected behavior
The Content Pane App is responsive in Excel when resuming Windows or after extended idle period.

## Current behavior
Insert the App and leave it idle or allow windows to auto sleep based on power settings and resume. 
Content Pane interface becomes frozen but Debugger log messages for resize and app function like drag still execute. In fact reloading the Add-in from the Content Pane > Reload menu option still works does reload the app, displays logs in the debugger as expected but does NOT unfreeze the app now displayed as an image.

## Steps to reproduce
Insert App
Allow Windows to sleep (does not occur when user manually select Power > Sleep)
Resume Windows
App UI Frozen > App functions are still operating and responsive but are not updating the UI. Debugger is registering logs.

**Image**: The App has been resized to demonstrate that the UI appears to be an image (NB. Show as Image is not checked).
The only way we have discovered to recover is to set "Show as Image" then uncheck to force a Reload that also resets the UI. Just Reload from the menu has not effect on the frozen UI. Restart Excel and reopen workbook resolves the issue.
![image](https://user-images.githubusercontent.com/47418828/131661654-9a88b22d-23c1-4222-9538-e3e06c6e6c34.png)

## Context
This behaviour makes the App unusable.
After extensive review and testing, we do not believe this bug is a result of our App but rather as result of recent changes to the way the Content Pane "Shape" container operates eg #2018 @dengshan2018

**Comment by Dengshan2018** [comment]
@david-ps could you try the workaround once you experience the issue:
1. switch to other application and leave excel in the background for more than 20 seconds.
2. switch back to excel

**Comment by david-ps** [comment]
@Dengshan2018 Yes, that worked for a Content Pane instance that displayed inactive and transparent on Windows Resume which I have see occasionally in addition to the UI as (frozen) image. The Content Pane system menu was still active and Reload executed but failed to resolve the issue. As requested, I switched to another application for 20+ seconds and on return to Excel it was working normally. 

Update: In another instance of the issue where the App was frozen as an image, this approach did not work.

**Comment by david-ps** [comment]
@slabereemsft @croicu @keyur32 @Dengshan2018  A sidenote of concern: It appears that recent changes to how Content Pane works (ie. Shape properties behaviours eg. Z-order supported) has created bugs and unintended consequences in addition to this bug and the previous bug posted #2018 
For example, our Content Pane add-in that previously supported mouse drag in Power Point presentation mode now does not.
Obviously the implications of releasing API updates with these issues means for us, the target audience App Office version requirements keep increasing with significant negative commercial impact.

**Comment by david-ps** [comment]
@croicu FYI: Testing the same app in PowerPoint exhibits similar behaviour. Frozen but also locked up PowerPoint. Not sure if it is related and it may be an app issue but we have not had this before. Will raise separate issue if required. See Task Manager actvity while frozen:
![PowerPointFreezeTaskManager](https://user-images.githubusercontent.com/47418828/132087895-c60bcdcc-7bf5-44d9-b52b-254b95be7c29.gif)

**Comment by Dengshan2018** [comment]
@david-ps are you saying you repro same issue in PowerPoint add-in? could you add the version of window 10?

**Comment by david-ps** [comment]
@Dengshan2018 I cannot say for certain it is same issue in Power Point just that Content Pane is similarly frozen on resume but may be coincidental and from our app so we are continuing to test. We do not believe it is our app issue in Excel.
Windows: 10 Pro
Version: 20H2
OS build: 19042.1165
Windows Feature Experience Pack 120.2212.3530.0

**Comment by david-ps** [comment]
@Dengshan2018 We have confirmed this behaviour in Excel affects the Microsoft Visio Add-in, here's a video demo of the bug: https://www.screencast.com/t/4DPCU7I1

**Comment by Dengshan2018** [comment]
Thanks @david-ps for more information. This issue isn't related with add-in itself. It should apply any excel content add-in. Just summarize the issue:
1. Excel content Add-in can repro the issue with the steps.
2. If the issue happened, switch to other applications and stay for more than 20 seconds, then switch back to excel. the issue can be resolved. 
3. Another workaround is to Freeze, and Unfreeze. The excel content add-in will become live again.
2. On same machine, PowerPoint content Add-in might have the issue, but can't repro any more.

Please confirm.

**Comment by david-ps** [comment]
@Dengshan2018 see confirmations below marked **>>**
1. Excel content Add-in can repro the issue with the steps **>> Yes, affects Content Pane Add-ins**
2. If the issue happened, switch to other applications and stay for more than 20 seconds, then switch back to excel. the issue can be resolved **>> Most of the time does not work**
3. Another workaround is to Freeze, and Unfreeze. The excel content add-in will become live again. **>> Check Add-in "Show as Saved Image" and then Uncheck resolves the issue**
4. On same machine, PowerPoint content Add-in might have the issue, but can't repro any more. **>> Yes, unsure if it is same issue but consider it Likely**

**Comment by david-ps** [comment]
@Dengshan2018 So this is major issue for developers of existing and new Content Pane Add-ins including Microsoft.
Can you give some timeline for a fix and verify the implications > now all users will require latest version and it won't be available in some Channels for some months? This recently introduced Shape bug is a major QA fail and a disaster for us. **Every** Content Pane in a workbook freezes every time a user leaves their PC for some time.

**Comment by Dengshan2018** [comment]
@david-ps we don't have repro yet. I leave excel application with in-content add-in. wait for 3 hours. when come back to the machine, the add-in is still live. Not sure if it will be related with hardware.
I did see the issue long before rolling out in-content with webview2. and we had the fix. After that I didn't see it any more.

What's more, we have new feature to improve Office rendering. This feature is shipped in PowerPoint. I believe that Excel will not have this issue once the feature is enabled. The feature in Excel is still dogfooding. no ETA for the production. I can provide registry key to enable it if you are interested in it.

Whatever, I will continue to try more to get the repro without this new feature.

**Comment by david-ps** [comment]
@Dengshan2018 Thanks for the update. I will try to repro on more machines and advise you. This seems only a recent occurrence within last 30 days that we noticed it. may be related to last Office Update applied in that period as shown above?

Yes, I would like the registry key to preview improved Office rendering. 

Thanks for continiuing your investigation, please let me know if there is anything we can do to assist.

**Comment by david-ps** [comment]
@Dengshan2018 We are able to repro this behaviour on other PCs. There are no API calls for "Show as saved image" that we may have been able to use to implement that manual workaround. Are there any programmatic approaches you could suggest we explore?  Also please send me the registry key you mentioned previously.

**Comment by Dengshan2018** [comment]
Here is registry key you can try for new feature:
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\Common\ExperimentEcs\Overrides]
"of22tfsc11br160"="true"

I still can't get the repro, but find one suspicion. will make the fix based on that.

**Comment by Dengshan2018** [comment]
@david-ps though I can't repro same issue, there is a clue. we are fixing the issue based on that assumption. Before the fix is made, could you provide the minidump with heap when the issue is repro? then we can verify if the fix can address the issue.

**Comment by david-ps** [comment]
@Dengshan2018 ok will do

**Comment by david-ps** [comment]
@Dengshan2018 Here is a snapshot taken when issue occured. Thanks for your help.
[Heap-20211001T084259.zip](https://github.com/OfficeDev/office-js/files/7262939/Heap-20211001T084259.zip)

**Comment by david-ps** [comment]
@Dengshan2018 I noticed that after Heap Snapshot the issue is resolved and the app becomes active. Do Snapshots start with Garbage Collection so this might be the reason it is resolved? Here another snapshot that when taken, resolved the issue:
[Heap-20211003T105427.zip](https://github.com/OfficeDev/office-js/files/7272489/Heap-20211003T105427.zip)

**Comment by Dengshan2018** [comment]
@david-ps thanks for providing the dump. There is potential fix in 16.0.14530.20000+. It could be available next week. You can try the beta. 
Once put excel in background for 20 more seconds, the issue could be resolved automatically.

**Comment by david-ps** [comment]
@Dengshan2018 Thanks I will check the beta. Putting Excel in the Background does not reliably resolve the issue.
Can you say why the problem seems to be resolved after a Garbage Collection related to the Edge Heap Dump?

**Comment by cornflakeboy** [comment]
Hey Guys,
What is the status here? We and our customers experience similar freezing behavior with different versions of excel, the latest of which is 16.0.14931.20118 .
Is there something else to do in order to test the fix? 
@david-ps Were you able to test the fix and did it help you?

**Comment by cornflakeboy** [comment]
I would be happy to contribute more information on this issue, if needed. It affects our business really hard. Freezing charts are unacceptable for our customers, so I would like to help resolving it. I can reproduce it with our content add-in by inserting it into a worksheet and switching to another worksheet. When switching back after 5 minutes or so, it is frozen and (in my case) fully opaque, but the inspector seems to recognize elements.

Sometimes the frozen add-in can be recovered by clicking on it, by resizing it or just by highlighting elements using the inspector as you can see [here](https://vimeo.com/688346797).
Sometimes it can only be recovered by toggling _show as saved image_. You can watch me desperately trying to recover the frozen add-in [here](https://vimeo.com/688347990).

**Comment by david-ps** [comment]
@cornflakeboy this is still a critical issue and to my knowledge and experience has not been addressed. Hard to understand why Microsoft has not made this a top priority given it also affects their own add-ins eg Visio add-in

**Comment by Dengshan2018** [comment]
Thanks @cornflakeboy for providing more repro steps and @david-ps . We did a fix last year. Not sure whether this is regression. Will investigate the issue and update the thread for the finding.

**Comment by Dengshan2018** [comment]
@cornflakeboy I can repro the issue with the steps you provided with low resource mode. It should be fixed with new rolling out feature. At same time, we will fix the issue in legacy path.
Once you see the issue, you can try switch to other application and leave Excel as background. After 20-30 seconds, switch back to Excel. Expect that in-content add-in will be recovered automatically.

**Comment by david-ps** [comment]
@Dengshan2018 FYI: this does not work consistently in my and other users experience: "After 20-30 seconds, switch back to Excel. Expect that in-content add-in will be recovered automatically"

**Comment by Dengshan2018** [comment]
Had the fix on 16.0.15118.*** and ported back to 16.0.15028.20112. Expect that both of them will be available in Office Insider Beta and CC next week. 
@david-ps and @cornflakeboy please give a try.

**Comment by Dengshan2018** [comment]
And the fix is ported back to 16.0.14931.20256 as well.

**Comment by cornflakeboy** [comment]
We tried with 16.0.15028.20152 and the issue seems to still exist. When can we expect 16.0.15118.*** to be released?
edit: Many thanks for responding so fast and being so committed to roll out fixes!

**Comment by Dengshan2018** [comment]
@cornflakeboy I check out our system. there is no 16.0.15028.20152 rolling out. Following versions in the productions should include the fix:
16.0.14931.20274, 16.0.15028.20160, 16.0.15028.20204 and 16.0.15209.20000

**Comment by cornflakeboy** [comment]
Thanks, I will verify our installed versions again...

**Comment by cornflakeboy** [comment]
We are a bit confused which version we should use to verify the fix. I just updated my excel version to the newest version available. Excel shows me two different build/version numbers and none of them seems to exactly align with the ones you mentioned. 
![image](https://user-images.githubusercontent.com/36692477/164458002-b3703adf-19b8-4164-9fe5-0e07842b2f57.png)

- Which one is the version we are talking about? The two-part or the four-part version in 'About Excel'?
- Can I assume that my version 16.0.15028.20218 contains the fix, given that it is higher than two of the versions you mentioned?

Sadly this version does not fix the issue. My content add-in still appears frozen when reopening its worksheet or restoring the excel window. What exaclty should I expect to be fixed? The add-in keeps being frozen and does not recover by itself when switching to other applications and switching back after a minute or so.

**Comment by Dengshan2018** [comment]
@cornflakeboy It should be 15028.20228. This is latest version for Current Channel. Expect it will have the fix.
Could you check the version of osfui.dll?

In the videos you posted, the add-in turned to transparent rectangle. so "frozen" means static image?
It will be great to have new video with the office version of 16.0.15028.20218.
So appreciate to help on locating the issue.

Could you upload more logs by following the steps from https://docs.microsoft.com/en-us/office365/troubleshoot/diagnostic-logs/collect-office-diagnostic-logs?

**Comment by david-ps** [comment]
I have same experience on latest version

Regards,
David
________________________________

**Comment by cornflakeboy** [comment]
With the term "frozen" I mean frozen in the state of being a transparent rectangle as showed in the videos. Sorry for the confusion.
We have now tested our add-ins with the latest version of excel which is 16.0.15128.20158. That version fixes the issue for us. Some of our customers claim to still have this issue with the newest version, but I think it could be that they are just confused. If not, I will get back to you. Thank you for your help so far.
