### ISSUE TITLE
Outlook: Office.context.ui.displayDialogAsync callback seem to be misfiring in OWA

### ISSUE THREAD

**Issue by avisheknand** [OfficeDev/office-js#2356]
# Provide required information needed to triage your issue
We have noticed that our dialogs on outlook item send event are showing blank instead of the message we are passing to the Dialog . We are suspecting the issue could reside on the Office.context.ui.displayDialogAsync callback function.

While debugging ( having break point) the dialog events are working perfectly fine. However, without debugging the issue is re produce able. The issue is happening in OWA, on desktop client it works fine.

Here is the code for the callback function 

`function sendConfirmdialogCallback(asyncResult) {

    if (asyncResult.status === "failed") {

        _asyncResult.completed({ allowEvent: false });
        // In addition to general system errors, there are 3 specific errors for 
        // displayDialogAsync that you can handle individually.
        dialogErrorHandler(asyncResult.error.code);

    }
    else {
        sendConfirmdialog = asyncResult.value;
        sendConfirmdialog.addEventHandler(Office.EventType.DialogMessageReceived, processSendConfirmMessage);

        /*Events are sent by the platform in response to user actions or errors. For example, the dialog is closed via the 'x' button*/
        sendConfirmdialog.addEventHandler(Office.EventType.DialogEventReceived, eventHandler);
    }
}`

We also believe that the line of code [ **sendConfirmdialog.addEventHandler(Office.EventType.DialogMessageReceived, processSendConfirmMessage);**] , where it is creating an event handler is not working as well. When the dialog initiates its is not able to pass the message back to the parent.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: office on web
* Host [Excel, Word, PowerPoint, etc.]: Outlook web
* Operating System: windows 10
* Browser (if using Office on the web):  chrome and edge
 
## Expected behavior

Before the events were firing correctly and the information was displayed correctly on the Dialog

## Current behavior

Currently there is no information/data displaying on the Dialog at all. 

## Context

We have an Outlook addin which is used by many customers and they are affected by this now.

#

**Comment by AkhileshShah-MS** [comment]
@exextoc could you please help with this issue.

**Comment by avisheknand** [comment]
We have another Outlook addin, this addin is a taskpane addin which opens up an dialog on a button click . In that the dialog callback asyncresult status is failed with error code of 12007 ( which means a dialog is already open by the host window) . However, there is no dialog open by the taskpane. I guess there is some updates been pushed out to OWA which is causing this issue. Again all is working fine on the Outlook desktop client.
Any help will be much appreciated :)

**Comment by exextoc** [comment]
@avisheknand Could you please share the add-in manifest with us and the steps to reproduce the bug in your add-in.

**Comment by avisheknand** [comment]
@exextoc i am sending you the Outlook taskpane addin manifest file link here https://customer_resources.s3.us-east-1.amazonaws.com/Office365%20Apps/EmailCaddie/EmailCaddie%20for%20O365.xml

Also, this app is live so you will be able to access in inside Outlook -> Get addins and search for "EmailCaddie"

Steps to Reproduce:

Logon to the OWA 
- Select an email and click on the EmailCaddie App ( Opens the EmailCaddie  taskpane)
- Click on the Start Using EmailCaddie Button
- You will see an error that " A dialog is already open"  at the bottom of the taskpane

Logon to Outlook Desktop
- Click on the EmailCaddie app and click on the Start using email caddie button , the  dialog appears correctly 

I am not sending you the Outlook item send addin manifest as it requires setup on both our side and your side ( Granting admin access to the app so it can run as delegate application  and etc) . I  hope the taskpane addin helps identify the issue

**Comment by exextoc** [comment]
@avisheknand Thanks for reporting this issue regarding Display Dialog. It has been put on our backlog. We, unfortunately, have no timelines to share at this point 

Internal tracking id: Office: 2551820

**Comment by avisheknand** [comment]
@exextoc , thanks for the update. Lots of our users are affected by this so any fix/workround for this will be appreciated. Has anyone else raised an issue about this?

**Comment by exextoc** [comment]
@avisheknand We were able to reproduce this issue only once on our end. Currently, we are not able to see any repro for this. Are there any specific steps that we need to perform for this repro? Otherwise, can you share any test account with us where we can consistently repro this?

**Comment by avisheknand** [comment]
@exextoc , i was also trying to test it on my side with the taskpane addin and it is no longer reproducible. However, the issue still exist on item send addin for Outlook.

i have a created a test account in my office 365 developer account for you.

emailaddress: exextoc@avishektest.onmicrosoft.com
Password: test@123#$

I have already setup the itemsend addin for you in the account. Also it only happens when you are sending an email using the pop-up window. I have created a video which shows how to reproduce it : https://customer_resources.s3.us-east-1.amazonaws.com/test/OfficeAddinItemSendDialogIssue.MP4

Hope this helps. Thanks.

**Comment by stefanoslig** [comment]
@exextoc we are able to reproduce this issue when we open for the first time the [https://outlook.office.com/mail/](https://outlook.office.com/mail/) and we create a new message. Then the dialogs don't open from the task pane. If you discard the message and then open the task pane again, the dialogs work fine. Then the only way to reproduce it is if you close the [https://outlook.office.com/mail/](https://outlook.office.com/mail/) tab and open it again(the detail is that if you have pinned the task pane, then this bug is not reproducible).

@avisheknand maybe this description helps you to reproduce it again?
@avisheknand I tried to open your task pane addin from the test account but I cannot find it after I installed it.

**Comment by avisheknand** [comment]
@stefanoslig , thanks lots :) ,  yes I was able to reproduce it when a new message is open in the pop up window and then the dialog does not open from the task pane.

@exextoc , i believe all is related when the new message is open in pop up window, the similar issue happens on the itemsend addin as well when sending email using the pop up window ( the video link i sent earlier ) , however in this case a dialog opens but nothing is displayed because the callbacks stop working.

**Comment by clavx** [comment]
I am experiencing a similar issue.

You can reproduce it by rewriting the code created by `yo office` as follows.

``` ts
function action(event: Office.AddinCommands.Event) {
  Office.context.ui.displayDialogAsync(
    location.origin + "/taskpane.html",
    { displayInIframe: true, height: 50, width: 30 },
    (result) => {
      console.log(result);
      if (result.status === Office.AsyncResultStatus.Succeeded) {
        result.value.addEventHandler(Office.EventType.DialogEventReceived, (arg) => {
          console.log(arg);
          event.completed({ allowEvent: true });
        });
        result.value.addEventHandler(Office.EventType.DialogMessageReceived, (processMessage) => {
          console.log(processMessage);
        });
      } else {
        event.completed({ allowEvent: false });
      }
    }
  );
}
```

https://user-images.githubusercontent.com/58804032/149330177-4faf957d-9ba9-4b72-bb92-45b9fac00fb5.mp4

It seems that both `Failed` and `Succeeded` are being executed when the ` Office.context.ui.displayDialogAsync` API is called.

If you have a code that terminates the process on failure, you will not be able to close the dialog screen due to this issue.

When `Failed` was recorded in the console log, the following was output.

```
error: OSF.DDA.Error
  code: 12007
  message: "The operation failed because this add-in already has an active dialog."
  name: "Display Dialog Error"
```

**Comment by stefanoslig** [comment]
@exextoc any update on this?

**Comment by avisheknand** [comment]
Hi @exextoc , is there any update on this? please note that most of ours users are affected by this. Thanks

**Comment by exextoc** [comment]
Hi @avisheknand, We are not able to repro the error at our end, even with the test credentials shared by you. Can you please share some consistent test steps so that we can repro and debug it?

And, please share console logs also if you see any error during the repro.

**Comment by avisheknand** [comment]
@exextoc thank you for the update. I also logged in to the test account and saw the issue was not repo. This is because the addin was removed. I believe someone must have logged in and removed it accidently as the account credential was publicly accessible. Is there an email address where i can send you the test account new credential with everything ready setup?

**Comment by exextoc** [comment]
@avisheknand Thanks for your patience. Kindly use this test account 
**adelev@M365x07818152.onmicrosoft.com** and the password is **p1moah5j3Q** so that we can try to repro it from our end.

**Comment by avisheknand** [comment]
@exextoc , I have set it up on the test account you have provided.

Also the manifest link : [https://sendguardm365.s3.us-east-1.amazonaws.com/Standss/D166A146-14BB-494D-9027-EE218A430ED3/SendGuard%20for%20M365Manifest_TestServer_ClientSideDLP.xml](url)

https://user-images.githubusercontent.com/80862413/149877001-419f7f91-1c89-4b2f-96c9-7cba283fdae9.MP4

**Comment by exextoc** [comment]
@avisheknand  We are able to repro the issue and we are working on a fix as quickly as we can. Will keep you updated once the fix is out. Thanks for your support.

**Comment by avisheknand** [comment]
@exextoc , thanks for update and giving this a priority

**Comment by clavx** [comment]
@exextoc any update on this?
This issue is always encountered when the `OnSendAddinsEnabled` flag is `True`, as it forces the **"Open in new window"** behavior. As a temporary workaround, we are telling our customers to set the `OnSendAddinsEnabled` flag to `False` and not to use **"Open in new window"**.

It seems to be possible to work around this issue by ignoring the 12007 error, so we are considering implementing this action if it still takes time to fix.

Could you please let us know the status of the fix?

Does not work (facing the issue):
``` ts
function action(event: Office.AddinCommands.Event) {
  Office.context.ui.displayDialogAsync(
    location.origin + "/taskpane.html",
    { displayInIframe: true, height: 50, width: 30 },
    (result) => {
      if (result.status === Office.AsyncResultStatus.Succeeded) {
        result.value.addEventHandler(Office.EventType.DialogEventReceived, () => event.completed({ allowEvent: true }));
      } else {
        if (result.error.code === 12007) {
          event.completed({ allowEvent: false });
        }
      }
    }
  );
}
```
Works (ignoring the 12007 error):
``` ts
function action(event: Office.AddinCommands.Event) {
  Office.context.ui.displayDialogAsync(
    location.origin + "/taskpane.html",
    { displayInIframe: true, height: 50, width: 30 },
    (result) => {
      if (result.status === Office.AsyncResultStatus.Succeeded) {
        result.value.addEventHandler(Office.EventType.DialogEventReceived, () => event.completed({ allowEvent: true }));
      } else {
        if (result.error.code !== 12007) {
          event.completed({ allowEvent: false });
        }
      }
    }
  );
}
```

**Comment by avisheknand** [comment]
@exextoc , any updates on this issue?

**Comment by exextoc** [comment]
We have fixed the issue, will update you once it reaches 100% of the users.

**Comment by avisheknand** [comment]
@exextoc thanks for the update. Appreciate the work on this :)

**Comment by exextoc** [comment]
Hey @avisheknand, is the issue still repro for you?

**Comment by milankonir** [comment]
@exextoc The issue is still reproducible with the sample add-in and reproduction steps I have provided in #2389

**Comment by avisheknand** [comment]
@exextoc , yes i am still able to repro the issue. Also have tried to clear by browser cache and test it out and it is repro

**Comment by clavx** [comment]
We have confirmed that our add-in works fine after the change to the new UI design.

Does not work (OLD design):
![owa_old](https://user-images.githubusercontent.com/58804032/153824501-e406c3ec-45dd-4f9b-a79e-a0a28471fc32.png)

Works (NEW design):
![owa_new](https://user-images.githubusercontent.com/58804032/153824518-47ced83b-3bbe-4525-b320-24a8f67f79fb.png)

Thank you for resolving the issue!

**Comment by clavx** [comment]
Sorry for the lack of confirmation.
We only checked when the `OnSendAddinsEnabled` flag was `False`, not when it was `True`. We additionally checked the case where the `OnSendAddinsEnabled` flag is `True`, and were able to reproduce another problem reported by https://github.com/OfficeDev/office-js/issues/2431.
We are sorry for the confusion.

**Comment by exextoc** [comment]
@avisheknand @stefanoslig can you confirm that the issue is resolved.

**Comment by avisheknand** [comment]
@exextoc , retested today and confirming that the issue is fixed. Thanks for the work on this.
