### ISSUE TITLE
Office APIs failing with internal error 5001

### ISSUE THREAD

**Issue by milankonir** [OfficeDev/office-js#2386]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.1211.1000
* Operating System: Mac OS X
* Browser (if using Office on the web): N/A
 
## Expected behavior

Office APIs do not randomly fail with internal errors

## Current behavior

Office API calls randomly fail with
```
code: 5001
name: Internal Error
message: An internal error has occurred.
```

We have seen this on various APIs, e.g.:
`Office.context.mailbox.item.to.getAsync`
`Office.context.mailbox.item.getBody`
`Office.context.mailbox.item.from.getAsync`

## Steps to reproduce

This error is repeatedly reported in our add-in telemetry. We were not able to get a stable repro that we could provide.

## Link to live example(s)

N/A

# Provide additional details

This only happens in the new Outlook for Mac UI, we have no errors coming in for the old Outlook for Mac UI. The problem has been reported several times and usually closed due to inactivity.

The errors happen in various context (add-in task pane, ItemSend event).

I realise it maybe be hard to find a fix without proper repro, but maybe there are some improvements in telemetry or the error message returned from Office API that could help resolve these issues?
 
## Context

We need to provide reliable add-in experience to users which is impossible with Office APIs randomly failing.

## Useful logs

File https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-mac-16.00.js  line 20 col 193232 in [anonymous]
File https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-mac-16.00.js  line 20 col 193828 in a
File https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-mac-16.00.js  line 20 col 194216 in [anonymous]
File https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-mac-16.00.js  line 20 col 105822 in d
File https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-mac-16.00.js  line 20 col 103101 in [anonymous]
File https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-mac-16.00.js  line 20 col 101915 in g

**Comment by exextoc** [comment]
Thanks @milankonir for reporting this issue.

(1) Can you please provide Outlook Mac version you are using?
(2) Is this happening with a particular Outlook Mac version or all kinds of version with "New UI"?
(3) Can you please provide specific Mac OSX version you are using?

**Comment by milankonir** [comment]
As mentioned in the ticket description, these are coming in through our telemetry and we have a hard time reproducing in house. We are keeping an eye on these errors and will collect powerlift logs if we encounter them.

The errors are reported exclusively for Outlook for Mac "New UI", so far we have record following Outlook / Mac OS versions:

Outlook: 16.0.1211.1000 / Mac OS: 10.15.7
Outlook: 16.0.613.1000 / Mac OS: 10.15.7
Outlook: 16.0.111.1000 / Mac OS: 10.15.7

**Comment by exextoc** [comment]
The format of the outlook version you have shared doesn't match with Mac outlook version. Mac outlook versions looks like 
![c591b39d-e6b8-4460-a2ad-0b15a0f90133](https://user-images.githubusercontent.com/28549921/151962233-a9c61e8e-97ec-4bf1-8149-d763bf0dbc0a.jpg)
Can you get it by clicking on : Outlook->About Outlook and share it with us.

**Comment by milankonir** [comment]
As I already mentioned on two occasions, the errors are collected in our telemetry that is coming in from customers. The versions come from the `Office.diagnostics.hostVersion` API  https://docs.microsoft.com/en-us/javascript/api/outlook/office.diagnostics?view=outlook-js-preview#outlook-office-diagnostics-hostversion-member

For old UI for Mac, the diagnostics API reports same version as is displayed in the about box, for new UI for Mac the diagnostics API reports versions I have listed in my comment. I would assume, you would be able to map the diagnostics info to appropriate new UI Outlook version.

## Luckily, we also managed to repro the problem internally:

1. Click reply on an email
2. Pop out the email into new window (Continue message in a separate Window)
3. Close the new Window
4. Click resume editing on the inline reply

From that point, calls start to fail with internal 5001 or does not even callback at all.

Repro video: https://share.getcloudapp.com/NQuxjQe6

Snippet used in Script lab:
```
$("#run").click(run);

function run() {
  Office.context.mailbox.item.from.getAsync(result => console.log(result));
  Office.context.mailbox.item.body.getAsync(Office.CoercionType.Html, result => {
    const loggableResult = { ...result, value: result.value.substring(1, 30) };
    console.log(loggableResult);
  });
  Office.context.mailbox.item.to.getAsync(result => console.log(result));
}
```

Outlook version used in repro is:
![image](https://user-images.githubusercontent.com/72383088/151977863-61e4cef6-5ac4-4e62-94a2-938a0e58308f.png)

**Comment by exextoc** [comment]
Thanks for reporting this issue. We are able to reproduce this issue internally. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by jackdawHome** [comment]
We have the same issue with Office.context.mailbox.item.internetHeaders.getAsync. It fails randomly with internal error 5001.
macOS Monterey, version 12.2
Microsoft Outlook for Mac, v 16.63 (22070801)

**Comment by sumitmodi01** [comment]
We are also facing the same issue. Getting this error 5001 in getAttachmentContentAsync() call. Its intermittent issue.

Setup details:
macOS BigSur 11.4
Outlook version 16.64 (22081401)
Outlook New UI 

Error string : 
{"name":"Internal Error","message":"An internal error has occurred.","code":5001}


Steps to Repro:
1. Make sure outlook addin is loaded.
2. compose a mail item in popped up window 
3. Add message body, to , cc lists and add an attachment

**Comment by vikramsw** [comment]
@exextoc , It is unclear to me if the following is related to the root_cause of the issue, but right before when the issue occurs, an XPC failure for the Webkit.WebContent process also occurs alongside a mach-lookup failure for **com.apple.tccd.system** caused by **sandbox violation**.

**RELEVANT LOGS**
<code>
2022-09-10 02:05:30.609261+0530 0x496686   Error       0x0                  0      0    kernel: (Sandbox) 1 duplicate report for Sandbox: com.apple.WebKit(68894) deny(1) mach-lookup com.apple.tccd.system
2022-09-10 02:05:30.609264+0530 0x496686   Error       0x0                  0      0    kernel: (Sandbox) Sandbox: com.apple.WebKit(68894) deny(1) file-read-data /Library/Preferences/com.apple.networkd.plist
2022-09-10 02:05:30.544783+0530 0x496686   Error       0x530fe3             68894  0    com.apple.WebKit.WebContent: (TCC) [com.apple.TCC:access] send_message_with_reply_sync(): XPC_ERROR_CONNECTION_INVALID for message 0x7f9fea3065a0
2022-09-10 02:05:30.544784+0530 0x496686   Error       0x530fe3             68894  0    com.apple.WebKit.WebContent: (TCC) [com.apple.TCC:access] TCCAccessRequest_block_invoke: Connection invalid
</code> 
 
Webkit, whose process loads the outlook mail-addin , recently saw a relevant change in its source.
https://trac.webkit.org/changeset/271901/webkit
https://bugs.webkit.org/attachment.cgi?id=418405&action=diff

Also, as per the comments in the above Webkit checkin, mach-lookup to the service 'com.apple.tccd.system' in the WebContent process **are no longer being used**. Then why is Outlook's addin flow still making a mach-lookup for com.apple.tccd.system ?

The above WebKit change affects MacOS BigSur, Monterey and above. We have confirmation that we are seeing this issue on BigSur and Monterey.  If someone can confirm that macOS Catalina also has this issue, then the earlier mentioned sandbox violation is not affecting the issue cause likely. 

CC: @sumitmodi-lab

**Comment by Premsagar-lab** [comment]
@exextoc Please provide some update on why this issue occurs when fetching attachments. Our customers are facing this issue intermittently on their machines and awaiting response from us.

**Comment by vikramsw** [comment]
@exextoc , Any update regarding this issue ?

**Comment by vikramsw** [comment]
@exextoc , REMINDER:  An update is requested on this please.

**Comment by vikramsw** [comment]
@exextoc , REMINDER: An update is requested on this please.

**Comment by exextoc** [comment]
We are working on this issue and will update on this thread once we have a fix

**Comment by vikramsw** [comment]
@exextoc , Thanks. Looking forward to a resolution on this issue.

**Comment by vikramsw** [comment]
Requesting a re-open.

**Comment by teejay001** [comment]
Hi,

We are facing the same issue with draft email on Mac OS. Any update on the issue please.

Do kindly reopen this issue as it's never communicated it's fixed and @vikramsw has also requested it been reopened.

Thanks

**Comment by milankonir** [comment]
@exextoc Can you please reopen the issue?

**Comment by exextoc** [comment]
@milankonir, @teejay001, @vikramsw  We have fixed the bug and the fix should be available in next build. When an updated build is available depends on the release channel a customer is on.

**Comment by Howard-Song** [comment]
@exextoc **Did this fix release already valid in `https://appsforoffice.microsoft.com/lib/1/hosted/Office.js`?**  I also meet this issue in Outlook for windows when using these code to get body/recipient/attachment every 300ms.
```
$("#run").click(loop);
let errors = [];
function loop() {
 window.Office.context.mailbox.item.to.getAsync((result) => {
     if(!isSuccess(result)) return;
      window.Office.context.mailbox.item.cc.getAsync((result) => {
        if(!isSuccess(result)) return;
        window.Office.context.mailbox.item.bcc.getAsync((result) => {
        if(!isSuccess(result)) return;
        window.Office.context.mailbox.item.getAttachmentsAsync((result) => {
        if(!isSuccess(result)) return;
        window.Office.context.mailbox.item.sessionData.setAsync("test", new Date().getTime() + '', (result) => {
            retry();
        })
            })
              })
      })
    })
}
function retry(){
     setTimeout(()=>loop(),300)
}
function isSuccess(result){
    if(result.status !== window.Office.AsyncResultStatus.Succeeded){
        errors.push(result);
        retry();
        return false;
    }else{
        return true;
    }
}
```
The error in one day(last 24 hours) grown up to 32k: `{"name":"Internal Error","message":"An internal error has occurred.","code":5001}` includes these API:
![image](https://user-images.githubusercontent.com/28775661/204430439-c48e7e67-c50f-4af9-be8a-a6036cb86bc0.png)
**So is this the same issue here or should I submit another one?**
Looking forward to your reply, thanks.

**Comment by milankonir** [comment]
@JesseHeisenberg  I believe that the `5001` is an umbrella exception for all sorts of internal office api errors with multitude of root causes. While the repro I have provided in this ticket is possibly fixed, we are still getting bunch of these errors even on the Mac platform.

I'd recommend to create a new issue with your problem / repro.

**Comment by Premsagar-lab** [comment]
@exextoc, @vikramsw & @sumitmodi01 , We have again started seeing this issue while retreiving attachments API.

**Comment by tubedude** [comment]
I was having the same issue with Word

> Platform [PC desktop, Mac, iOS, Office on the web]: Mac
> Host [Excel, Word, PowerPoint, etc.]: Word
> Office version number: Version 16.86 (24060916)
> Operating System: Mac OS X 14.5 (23F79)
> Browser (if using Office on the web): N/A

My solution was to give Word Full disk access on mac's security settings. Maybe it was a coincidence and rebooting word in the process fixed.
