### ISSUE TITLE
Outlook Online: getAsync() and setAsync() methods of the Office.Location interface do not work

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#2472]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Out add-in for compose mode supports mail and meeting (<ExtensionPoint xsi:type="AppointmentOrganizerCommandSurface">) items. For meeting items, we use the [Office.Location](https://docs.microsoft.com/en-us/javascript/api/outlook/office.location) methods such as getAsync and setAsync. In Outlook Online, both methods do not work in case a user enters a location manually.

## Your Environment
* Platform: Office on the web
* Host: Outlook Online
* Office version number: 
* Operating System: Windows 10 21H1
* Browser (if using Office on the web): Chrome 99.0.4844.51
 
## Expected behavior
The getAsync method shall return a string from the Location field. The setAsync method shall overwrite the current data in the Location field.

## Current behavior
Both methods do not work in case a user enters text in the Location field manually.

## Steps to reproduce
1. In Outlook Online, switch to Calendar and click the "New event" button
2. In a new meeting window that opens, enter some text (say Room 55) into the Location field
3. Start the add-in and execute the following code:
`Office.context.mailbox.item.location.getAsync((asyncResult) => {`
`    console.log(asyncResult);`
`});`

4. Problem 1 - as you can see there is an empty string in asyncResult.value
5. Then try to execute the following code:
`Office.context.mailbox.item.location.setAsync('', (asyncResult) => {`
`    console.log(asyncResult);`
`});`

6. Problem 2 - the setAsync method shall overwrite the current “Room 55” value but does not do this

# Provide additional details
1. Both methods work fine in Outlook Desktop on Windows and Outlook for Mac on macOS.

**Comment by exextoc** [comment]
Hey @DmitryKostochko ,

Does the location that you've typed in the location field resolve to a location before you call the API, like this:
<img width="646" alt="Screenshot 2022-03-12 at 9 09 15 PM" src="https://user-images.githubusercontent.com/28549921/158024645-79f73b37-f37d-4353-bbfe-4a4885084d26.png">

It is expected that the location should be resolved before an add-in API is able to read it.

**Comment by DmitryKostochko** [comment]
@exextoc, thank you for your quick turnaround.

The text that I entered was not resolved into a location. Is it possible to force resolving by calling an API method?

**Comment by exextoc** [comment]
Hi @DmitryKostochko,
There is no API to force resolve the location.
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by DmitryKostochko** [comment]
@gergzk, please re-open the issue. The bug is still reproducible in Outlook Online. And, as I mentioned, both methods work correctly in Outlook Desktop. So, a fix is needed in the Online API version.
