### ISSUE TITLE
Office.context.mailbox.item.recurrence.getAsync is giving - Uncaught (in promise) Error: unhandled recurrence pattern undefined

### ISSUE THREAD

**Issue by maliksuyash** [OfficeDev/office-js#2864]
In our Office Add-In, when getting the recurrence details using outlook.js we are getting error in console - **Uncaught (in promise) Error: unhandled recurrence pattern undefined** when we are calling **Office.context.mailbox.item.recurrence.getAsync() function** in Outlook Web only but works perfectly in Outlook Native. It starts happening from today only. Previously, it was working fine. Has something change in outlook.js?
  
![image](https://user-images.githubusercontent.com/91523389/191963725-56acdd79-38fd-42f6-8706-e2a9e7a8c559.png)

![image](https://user-images.githubusercontent.com/91523389/191963327-5cd5b16b-e698-4dc0-bd2b-cabf10372246.png)

**Comment by maliksuyash** [comment]
@exextoc One more issue is happening, Create a recurrence meeting from Outlook Native and change the time of whole series from OWA. The recurrence details are removed from the graph event thus making it single day meeting. Please find below screen shots.

![image](https://user-images.githubusercontent.com/91523389/192101038-4e21f329-b810-4aba-acd5-7b383ba591e7.png)

![image](https://user-images.githubusercontent.com/91523389/192101046-69ac11af-ff43-40b1-8e8a-fdb36300d696.png)

![image](https://user-images.githubusercontent.com/91523389/192101051-3070b09a-4b6a-4508-b330-7307e4ee970b.png)

**Comment by exextoc** [comment]
We are not able to repro this. Can you please share the repro steps along with API calls made, it will help us to understand the issue better.

**Comment by AlexandrDiakov** [comment]
I have encountered the same issue with outlook add-ins that try to get meeting recurrence.
We started developing our add-in not so long ago and everything worked just fine until a few days ago this  "unhandled recurrence pattern undefined" error started popping up in console.
It doesn't look like this problem is on our side cause we did no changes to our add-in code & it looks like the Zoom add-in command for adding a meeting also crashes with this error if recurrence for current meeting is turned on.

**Comment by johnbergvall** [comment]
One of our developers got this problem as well during the last couple of days, but no one else so far.

```
Uncaught (in promise) Error: unhandled recurrence pattern undefined
    at a (owa.CalendarBoot.js:2:950197)
    at i (owa.CalendarBoot.js:2:950607)
    at Z (owa.Addins.js:2:855571)
    at owa.Addins.js:2:1155350
```
Minified code below.

The unhandled exception seems to be caused by owa.CalendarBoot.js sends `e.__type` as `"WeeklyRecurrence"` but all the `r[key]`-values have a `:#Exchange`-suffix. I.e. `r.MG == "WeeklyRecurrence:#Exchange"` != `"WeeklyRecurrence"`


![outlook_error](https://user-images.githubusercontent.com/1251711/192740318-3b0af0e5-0145-4cd8-ae9d-adc4044b14b3.PNG)

**Comment by thoffmann-fms** [comment]
I and several other developers are seeing this too, on multiple browsers.  This also causes ```Office.context.mailbox.item.start.getAsync()``` to never return.  No failure, just the promise is never resolved/rejected.

Fails also on MacOS Safari when called by owa.addins.js version 20220916007.08

![image](https://user-images.githubusercontent.com/28546239/192799465-e98f0750-7c48-4e5a-9e3a-f18ec2d1148b.png)


Console log:
![image](https://user-images.githubusercontent.com/28546239/192797928-10f52fa1-bb98-4262-9252-4c030c0e24cf.png)

**Comment by thoffmann-fms** [comment]
Pure OWA is failing (no Add-Ins involved).

Create a recurring meeting starting on Monday.  Select the end date of Friday. Save.
Console log full of errors:
        
```       Failed to load resource: net::ERR_CONNECTION_REFUSED
owa.CalendarBoot.js:2 
        
       Uncaught (in promise) Error: unhandled recurrence pattern undefined
    at a (owa.CalendarBoot.js:2:950197)
    at i (owa.CalendarBoot.js:2:950607)
    at Z (owa.Addins.js:2:855571)
    at owa.CalendarQuickCompose.js:1:353782
      

        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
owa.CalendarBoot.js:2 
        
       Uncaught (in promise) Couldn't save event
owa.CalendarBoot.js:2 
        
       Uncaught (in promise) Error: [fetchFullCalendarEvent] Action source:FullComposeInEditMode_SendEventErrorNotification with response code: ErrorItemNotFound and error: [getCalendarEventService] request failed. Message: The occurrence couldn't be found., Item not found., ResponseCode: ErrorItemNotFound, ResponseClass: Error
    at De (owa.CalendarBoot.js:2:480402)
    at async We (owa.43290.js:2:174826)
    at async Ue (owa.43290.js:2:174075)
    at async Ke (owa.43290.js:2:177111)


       Failed to load resource: net::ERR_CONNECTION_REFUSED
owa.CalendarBoot.js:2 
        
       Uncaught (in promise) Error: unhandled recurrence pattern undefined
    at a (owa.CalendarBoot.js:2:950197)
    at i (owa.CalendarBoot.js:2:950607)
    at Z (owa.Addins.js:2:855571)
    at owa.CalendarQuickCompose.js:1:353782

owa.CalendarBoot.js:2 
        
       Uncaught (in promise) Couldn't save event
owa.CalendarBoot.js:2 
        
       Uncaught (in promise) Error: [fetchFullCalendarEvent] Action source:FullComposeInEditMode_SendEventErrorNotification with response code: ErrorItemNotFound and error: [getCalendarEventService] request failed. Message: The occurrence couldn't be found., Item not found., ResponseCode: ErrorItemNotFound, ResponseClass: Error
    at De (owa.CalendarBoot.js:2:480402)
    at async We (owa.43290.js:2:174826)
    at async Ue (owa.43290.js:2:174075)
    at async Ke (owa.43290.js:2:177111)

owa.CalendarBoot.js:2 
        
       Uncaught (in promise) Error: unhandled recurrence pattern undefined
    at a (owa.CalendarBoot.js:2:950197)
    at i (owa.CalendarBoot.js:2:950607)
    at Z (owa.Addins.js:2:855571)
    at owa.CalendarQuickCompose.js:1:353782
```

Pick the Tuesday event, right-click and “This and all following”. Change the end-time and click save.  OWA aborts:

![image](https://user-images.githubusercontent.com/28546239/192818738-5550d8c7-515c-4c4b-8087-8b7e55a11281.png)

The “More Details” button provides no information. The Tuesday event is sometimes left in Draft state.  Wed-Fri are gone.

Console log:
```
owa.CalendarBoot.js:2 
        
       Uncaught (in promise) Couldn't save event
(anonymous) @ owa.CalendarBoot.js:2
await in (anonymous) (async)
```

**Comment by techpool** [comment]
I'm getting the same error and hence not able to get whether an event is recurring or not. Is there any other way to figure that out?

**Comment by thoffmann-fms** [comment]
Until that bug is fixed other bad things happen, too.  I have also opened a case via the Exchange Support path and cross referenced this ticket. Waiting to hear back from that side.

**Comment by maliksuyash** [comment]
@exextoc  For first issue. We have developed an Add-In. Where we are fetching the recurrence details using the function **Office.context.mailbox.item.recurrence.getAsync()** of Office.js. But as soon as it is called the error gets logged **Uncaught (in promise) Error: unhandled recurrence pattern undefined** in developer console and the next statement in the below screen shot never gets called **if (asyncResult.status == Office.AsyncResultStatus.Succeeded)** because of which we are not able to get the recurrence details. **Its only happening in OWA only**

![image](https://user-images.githubusercontent.com/91523389/193724471-a52d33f6-d134-451c-8795-17c67f6e10bb.png)

Below error gets logged in developer console

![image](https://user-images.githubusercontent.com/91523389/193724623-f48ed02b-60f0-40a5-bf28-a19d0e916693.png)

**Comment by maliksuyash** [comment]
@exextoc For second issue **which is also happening in OWA only**. Go to OWA and create a recurrence. 

![image](https://user-images.githubusercontent.com/91523389/193725090-d2f09d6a-75ef-4618-89cd-f777f9bb58cb.png)

Edit the same recurrence and change the time of whole series and save. It will give below alert

![image](https://user-images.githubusercontent.com/91523389/193725265-d7f982c1-f3ec-418d-9c3c-6a3f995c8240.png)

Click save mentioned in the above screen shot and observe that the events gets deleted accept the first event like below.

![image](https://user-images.githubusercontent.com/91523389/193725404-76b48c4e-ba43-4f17-97dd-d3ec4a6b8778.png)

**Comment by darko-kovac-clebex** [comment]
I can confirm this started happening in our outlook add-in as well two weeks ago, same error messages.  Office.context.mailbox.item.recurrence.getAsync() function in Outlook Web fails but works perfectly in Outlook Native.

![image](https://user-images.githubusercontent.com/112626094/194308238-17063d88-d06d-4d00-8039-b77c7eb98313.png)

Any progress on the issue?

**Comment by hello-chenchen** [comment]
with the same problem @exextoc @lindalu-MSFT in owa. just in new event, select daily recurrence, you will receive this error

**Comment by exextoc** [comment]
We are working on the fix with high priority. Will update once the fix is available.

**Comment by juritdev** [comment]
Any update on the fix? Because it's been broken for over three weeks now. Thanks

**Comment by exextoc** [comment]
We have checked in a fix and it is presently rolling out. It should be available by the end of this week.

**Comment by thoffmann-fms** [comment]
11am Eastern on Fri 10/21, still getting the error.

**Comment by thoffmann-fms** [comment]
Monday 10/24 AM, still happening, but at a different line  # than previously.
```
owa.CalendarQuickCompose.js:1 
 Uncaught (in promise) Error: unhandled recurrence pattern undefined
    at a (owa.CalendarBoot.js:2:717918)
    at i (owa.CalendarBoot.js:2:718289)
    at Z (owa.Addins.js:2:38094)
    at owa.CalendarQuickCompose.js:1:86263
```

**Comment by thoffmann-fms** [comment]
Tue 10/26, Fixed, no errors logged, and Office.context.mailbox.item.start.getAsync() works as expected.

**Comment by Texaner** [comment]
I can confirm that the error messages are gone.
But the actual error as described by @maliksuyash is still present.
When can we expect a fix?

**Comment by Texaner** [comment]
Any news or plan for a fix?

**Comment by exextoc** [comment]
@maliksuyash @Texaner Is the issue still reproducible? Can you provide the exact repro steps?

**Comment by Texaner** [comment]
Seems to be fixed, the error can no longer be reproduced.
Thanks
