### ISSUE TITLE
Addin is not loading. Seeing a message "Addin warning: This addin is no longer available"

### ISSUE THREAD

**Issue by vinay-sattur** [OfficeDev/office-js#3146]
Addin is not loading

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel

 
## Expected behavior
Addin should load.

## Current behavior
Addin is not loading and a message is displayed saying "Addin warning: This addin is no longer available". And on click of refresh button below the warning message nothing is happening.

**Comment by ghost** [comment]
Thank you for letting us know about this issue. We will take a look shortly. Thanks.

**Comment by ruijiaMS** [comment]
Thanks for your patient here @vinay-sattur, could you please provide your session id of the client, which is facing this issue, for us?
Session ID for excel online could be in: File -> About -> Recommended tab

**Comment by zpfaltersack** [comment]
Hello, we have been receiving this same warning for the last couple days. It happens for all customers, across all of our environments, and for both of our add-ins. No changes have been deployed. Sometimes the issue is resolved by refreshing but more often than not it just doesn't work. We have found that editing the document locally in Excel desktop loads the add-in fine so this appears to be an issue specifically with Excel Online.
The one thing I've noticed is that my development side-loaded add-in seems to resolve after a refresh or two "fairly" reliably. It's the centrally-deployed add-ins that fail to load.

Using desktop Excel at least keeps us moving forward but this is a pretty bad look for us with our customers.

A couple session IDs for me: defe334e-d6e4-4bbe-9785-c31f77b2f134, d953a5f6-bd50-4f4a-ba82-9c2f907b714b

There are a couple of bugs related to the Excel Online store mechanism (one is mine) that I can't help but wonder are related to this: #3076 and #2878.

**Comment by vinay-sattur** [comment]
Hi @ruijiaMS, here is the session id.
8f8f50ad-4d04-462d-b04f-265cb86e690d

**Comment by penglongzhaochina** [comment]
Hi, all, We have created a s2 incident to track this issue.

**Comment by ruijiaMS** [comment]
Hi all, the fix is rolling out right now. Please verify in a few hours to see whether the problem still exists. Thanks.

**Comment by vinay-sattur** [comment]
Hi @ruijiaMS ,
The issue is still happening. Here is the session id: fc79a0fc-ca4e-4c96-a9d0-c7d1aeff1e28

**Comment by penglongzhaochina** [comment]
@vinay-sattur Could you try appending this to your Office Online URL and trying again?
&wdtf=+Microsoft.Office.SharedOnline.SetSolutionIdWithSharedRuntimeCacheKeyKillSwitch:true

**Comment by vinay-sattur** [comment]
Hi @penglongzhaochina ,
We are opening the excel file through WOPI protocol. And the issue is happening in our production environment and we cannot make any changes there.

**Comment by penglongzhaochina** [comment]
Hi @vinay-sattur the fix is rolling out. It is likely going to take until sometime tomorrow to saturate deployment, so I would expect another ~24 hours for this to begin helping.

**Comment by zpfaltersack** [comment]
The issue seems to be resolved for me in my dev and testing environments. Over the next several hours we'll reach out to our impacted customers and confirm the issue is resolved on their end as well. Thanks for getting to this so promptly!

**Comment by ruijiaMS** [comment]
Thanks for your feedback @zpfaltersack!!
@vinay-sattur is it resolved/working in your dev and testing environments?

**Comment by vinay-sattur** [comment]
Hi @ruijiaMS , I verified this morning and addin is loading in our prod and dev environments. Thank you for fixing the issue!
