### ISSUE TITLE
Space as thousand seperator confuses excel standard of formatting.

### ISSUE THREAD

**Issue by thordurk91** [OfficeDev/office-js#3244]
This codeblock below, when run in an excel sheet with the thousand seperator as a single space.
Gives the results as of ",666.00" instead of "666.00" (1 becomes ",1.00")
 
Also gives this outcome if the thousand seperator is a letter, ":", "-", probably anything besides "." and ","
 
                entity.properties[prop] = {
                  type: Excel.CellValueType.formattedNumber,
                  basicValue: props[prop],
                  numberFormat: "#,##0.00",
                };

The space as a thousand seperator is fx. used in russian and french so this creates issues with outputted data for those users.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2302 (Build 16130.20332 Click-to-Run)
* Operating System: Windows 10
* Browser (if using Office on the web): N/A
 
## Expected behavior
For the numberFormat to behave as the user settings dictate.

## Current behavior
It's injecting a leading , to numbers in the hundreds and defaulting to "." as the decimal with 2 units of accuracy.
## Steps to reproduce
1. have your thousand seperator set to a space
2. Call a customfunction with a numberformat of this kind, with a sub 4 digit number.
3. See the leading thousand seperator appear in your data

## Link to live example(s)
https://gist.github.com/thordurk91/155d6aa41a202d3549fc184dcfff792a
1. Load script lab, enter a 1-3 digit number
2. Change thousand seperator to a single space " "
3. See the leading thousand seperator appear

## Context
Users in regions with space as it's thousand seperators get data that's less usable, have to cast it to a double/int for usage due to the format returning.
Prevent the leading thousand seperator and most users can navigate the outputted numbers.
or fix how numberFormat is handling these cases.

**Comment by penglongzhaochina** [comment]
Could you try whether the excel build-in functions have a similar behavior following this [Custom Excel number format (ablebits.com)](https://www.ablebits.com/office-addins-blog/custom-excel-number-format/)? I guess the thousand separator setting in the "numberFormat" should always be "," ,if the user change the setting following this [Change the character used to separate thousands or decimals - Microsoft Support](https://support.microsoft.com/en-us/office/change-the-character-used-to-separate-thousands-or-decimals-c093b545-71cb-4903-b205-aebb9837bd1e#:~:text=Click%20File%20%3E%20Options.,separator%20and%20Thousands%20separator%20boxes.), the thousand separator shows in cells will be changed accordingly (like 6 666.00) even the "numberFormat" is set as "#,##0.00". As what mentioned in this link, "By default, Microsoft Excel uses the system separators that are defined in the regional settings in Control Panel".

**Comment by thordurk91** [comment]
Good point, the custom formatter switches to using the custom set thousand and decimal in the excel format. 
Using the french system of blank space and "." as the thousand and decimal it wants to use that in it's preview # ##0.00 for example.
Basically overriding the logic supported by the standard comma or dot as the seperators.

For support of numberformat with french/russian space as a thousand seperator I need to get the users language/region settings in the javascript or have them set it in the window for compatability for how formatted entity display, since the user just gets a #VALUE on literally every function since it's in the basic entity for all numbers, since a currency display is almost always somewhere in the entities.

Is there some office js hook to get the users region of the workbook/sheet?

**Comment by JHJ-MS** [comment]
Hi @thordurk91 , these two APIs ([Office.context.contentLanguage](https://learn.microsoft.com/en-us/javascript/api/office/office.context?view=common-js-preview#office-office-context-contentlanguage-member) and [Office.context.displayLanguage](https://learn.microsoft.com/en-us/javascript/api/office/office.context?view=common-js-preview#office-office-context-displaylanguage-member)) may help you. For you reference, 1. [Use the JavaScript API to determine locale-specific strings](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/localization?tabs=xmlmanifest#use-the-javascript-api-to-determine-locale-specific-strings) 2.[JavaScript API to detect Office language and Excel argument separator](https://stackoverflow.com/questions/37648526/javascript-api-to-detect-office-language-and-excel-argument-separator)

**Comment by thordurk91** [comment]
Thank you for the resources @JHJ-MS.
For my current situation it was faster to revert this for the time being away from formatted cells and implement later with logic from these APIs.

**Comment by chgrossMSFT** [comment]
> Thank you for the resources @JHJ-MS. For my current situation it was faster to revert this for the time being away from formatted cells and implement later with logic from these APIs.

Hey, @thordurk91, just wanted to respond back here and let you know that we have pushed out a fix a few weeks ago that should address this. You should be able to use the same APIs you were. Would you mind giving it a go again and letting me know if you are still running into the issue?

Thanks for letting us know about this issue!

Chris

**Comment by thordurk91** [comment]
@chgrossMSFT 

Hey, I've checked this out and on my available excel installs I didn't see a change in the behaviour.
I had one of the users with #VALUE errors, on everything using that numberFormat, to make sure his faulty version was updated. But the error still persisted for his french default thousand seperators.

I myself only managed to reproduce errors creating ",00.6" outputs.

I've moved my output to simply using double fields for digits.

**Comment by ropari** [comment]
@thordurk91 

Could you let us know which version of Excel you are testing with?  We expect the issue to be fixed for builds after 16501.20000. 

To find out the build number, you can select the file tab, and then click on the Account tab.  There should be a section called "About Excel" that will list a version number that should look similar to this "Version 2305 (Build 16501.20180)".

**Comment by thordurk91** [comment]
> @thordurk91
> 
> Could you let us know which version of Excel you are testing with? We expect the issue to be fixed for builds after 16501.20000.
> 
> To find out the build number, you can select the file tab, and then click on the Account tab. There should be a section called "About Excel" that will list a version number that should look similar to this "Version 2305 (Build 16501.20180)".

The one I'm on is 2304 (Build 16327.20248) and after an update I'm up 2305 (Build 16501.20196).
I can confirm the functionality works now! My snipper produces a space as it's thousand seperator now. Awesome!

I have some users with difficult to update excel installs that were affected in a more severe way (#VALUE on everything) that I suspect is this numberFormat and their older installs, but still under investagion. I'll add notes that this version is the one that works with the functions. 

Thanks!
