### ISSUE TITLE
After the location update of the event, it will disappear automatically after a while

### ISSUE THREAD

**Issue by echowwl** [OfficeDev/office-js#3338]
system: mac 
system version:
![image](https://user-images.githubusercontent.com/105787768/236402667-d4ae09ea-a867-4fa3-9833-40d83f817ef4.png)

outlook version:
![image](https://user-images.githubusercontent.com/105787768/236402648-b3f5a3ba-fd3f-4f1f-9890-78fd8c99cfcf.png)

Issue Description:

==============

After the location update of the event, it will disappear automatically after a while

1. create a meeting use zoom addon

2. edit the event, change the date/ time then click zoom setting panel, and click"update"

3. open zoom setting panel, right-click and click the inspect , go to console:

use the command

function getLocation() {

    return new Office.Promise(function (resolve) {

        Office.context.mailbox.item.enhancedLocation.getAsync(callbackFunction);

    });

}

function callbackFunction(asyncResult) {

    asyncResult.value.forEach(function (place) {

        console.log("Display name: ",place);

        console.log("Type: " + place.locationIdentifier.type);

        if (place.locationIdentifier.type === Office.MailboxEnums.LocationType.Room) {

            console.log("Email address: " + place.emailAddress);

        }

    });

}

getLocation()

 

then i can see the location has value

3. click save

4. waiting for 2/3 minus

5. the location is disappeared.

6.use the command

function getLocation() {

    return new Office.Promise(function (resolve) {

        Office.context.mailbox.item.enhancedLocation.getAsync(callbackFunction);

    });

}

function callbackFunction(asyncResult) {

    asyncResult.value.forEach(function (place) {

        console.log("Display name: ",place);

        console.log("Type: " + place.locationIdentifier.type);

        if (place.locationIdentifier.type === Office.MailboxEnums.LocationType.Room) {

            console.log("Email address: " + place.emailAddress);

        }

    });

}

getLocation()

then i can see the location has no value

Before:
![image](https://user-images.githubusercontent.com/105787768/236401807-67e3419e-086e-4038-83a9-f63f6ae33e67.png)

After:
![image](https://user-images.githubusercontent.com/105787768/236402084-c06551a5-94d3-452f-9d42-dc203d789d1d.png)

 

Before:

 
![image](https://user-images.githubusercontent.com/105787768/236402179-45aa91c1-714c-41d1-a745-110116617dd9.png)

After:

![image](https://user-images.githubusercontent.com/105787768/236402248-855e1c21-ca46-44c7-8c33-62a32566d438.png)

here is the recording for the issue:
https://success.zoom.us/rec/share/NXBK_DQxYgybnWSbV63jDuHZVAJe5_x5VsdaWXfr_mMisbpf6HhcA3u8IJg8uNY.F8sHteP2Fd63fkOx Passcode: +G7ZW^d+

**Comment by echowwl** [comment]
The steps:
1.create a zoom meeting
2.edit the event
3.open zoom setting panel, and open the inspect
4.run the code in console:

function getLocation() {
    return new Office.Promise(function (resolve) {
        Office.context.mailbox.item.enhancedLocation.getAsync(callbackFunction);
    });
}

function callbackFunction(asyncResult) {
    asyncResult.value.forEach(function (place) {
        console.log("Display name: ",place);
        console.log("Type: " + place.locationIdentifier.type);
        if (place.locationIdentifier.type === Office.MailboxEnums.LocationType.Room) {
            console.log("Email address: " + place.emailAddress);
        }
    });
}
getLocation()

function removeEnhanceLocation (joinUrl) {
    return new Office.Promise(function (resolve) {
        var locations = [
            {
                id: joinUrl,
                type: Office.MailboxEnums.LocationType.Custom
            }
          ];
          Office.context.mailbox.item.enhancedLocation.removeAsync(locations, function (result) {
              if (result.status === Office.AsyncResultStatus.Succeeded) {
                  console.log("removeEnhanceLocation success");
                  resolve(true);
              } else {
                  console.log("removeEnhanceLocation failed: "+JSON.stringify(result));
                  resolve(false);
              }
        });
    });
};

function setEnhanceLocation (joinUrl) {
    return new Office.Promise(function (resolve) {
        var locations = [
            {
                id: joinUrl,
                type: Office.MailboxEnums.LocationType.Custom
            }
          ];
        Office.context.mailbox.item.enhancedLocation.addAsync(locations, function (result) {
            if (result.status === Office.AsyncResultStatus.Succeeded) {
                console.log("setEnhanceLocation success");
                resolve(true);
            } else {
                console.log("setEnhanceLocation failed: "+JSON.stringify(result));
                resolve(false);
            }
        });
    });
}

ss=“your location meeting link url"
removeEnhanceLocation(ss)
setEnhanceLocation(ss)
getLocation()
then save the event

wait few minutes, you will see the location disappear

then you can open the event again ,and run the code :
function getLocation() {
    return new Office.Promise(function (resolve) {
        Office.context.mailbox.item.enhancedLocation.getAsync(callbackFunction);
    });
}

function callbackFunction(asyncResult) {
    asyncResult.value.forEach(function (place) {
        console.log("Display name: ",place);
        console.log("Type: " + place.locationIdentifier.type);
        if (place.locationIdentifier.type === Office.MailboxEnums.LocationType.Room) {
            console.log("Email address: " + place.emailAddress);
        }
    });
}
getLocation()

you will see nothing

**Comment by echowwl** [comment]
Before
![Screenshot2023_05_05_181837](https://user-images.githubusercontent.com/105787768/236432958-52d49c8d-11aa-4293-957f-6f30a75f3ddd.jpg)
![Screenshot2023_05_05_181837(1)](https://user-images.githubusercontent.com/105787768/236432974-6b55e156-3d0a-40cc-ac9c-4e3070725592.jpg)
![Screenshot2023_05_05_181837(2)](https://user-images.githubusercontent.com/105787768/236432997-344e71fc-1075-4853-8d34-d4093a304cbd.jpg)
![Screenshot2023_05_05_181837(3)](https://user-images.githubusercontent.com/105787768/236433019-bfa35c59-0168-45bc-acb6-638a8cb66712.jpg)
After:
![Screenshot2023_05_05_181837(4)](https://user-images.githubusercontent.com/105787768/236433057-360fea73-1b41-4560-88c6-90361864086b.jpg)
![Screenshot2023_05_05_181837(5)](https://user-images.githubusercontent.com/105787768/236433090-11636132-c44a-4a69-88a3-a910b1f36b87.jpg)

**Comment by exextoc** [comment]
@echowwl Thanks for reporting this issue regarding the location update event in a detailed way. We are able to repro the bug, and It has been put on our backlog. We, unfortunately, have no timelines to share at this point.

Internal tracking id: Eg: Office: 7871382

**Comment by exextoc** [comment]
Hi @echowwl,
We have fixed the bug and the fix should be available in build 16.74(23051900) or later. When an updated build is available depends on the release channel a customer is on.

**Comment by echowwl** [comment]
Thanks for the update

**Comment by mmhforjavaweb** [comment]
<img width="310" alt="image" src="https://github.com/OfficeDev/office-js/assets/19813166/f9575971-be0a-4020-b219-fc5b801ef6d6">

1.Edit  a event with  rooms
2. add locations
```
const locations = [
  {
    id: "Contoso",
    type: Office.MailboxEnums.LocationType.Custom
  }
];
Office.context.mailbox.item.enhancedLocation.addAsync(locations, (result) => {
  if (result.status === Office.AsyncResultStatus.Succeeded) {
    console.log(`Successfully added locations ${JSON.stringify(locations)}`);
  } else {
    console.error(`Failed to add locations. Error message: ${result.error.message}`);
  }
});
```
3.remove locations
```
const locations = [
  {
    id: "Contoso",
    type: Office.MailboxEnums.LocationType.Custom
  }
];
Office.context.mailbox.item.enhancedLocation.removeAsync(locations, (result) => {
  if (result.status === Office.AsyncResultStatus.Succeeded) {
    console.log(`Successfully removed locations ${JSON.stringify(locations)}`);
  } else {
    console.error(`Failed to remove locations. Error message: ${result.error.message}`);
  }
});
```
4.The changes in the interface are consistent with our expectations.
5.Send event.
6.View the Event, 'Contoso' appears in the locations

The bug should still exist @exextoc

**Comment by exextoc** [comment]
@mmhforjavaweb  This is a different issue from the one mentioned in this post and  has been reported here https://github.com/OfficeDev/office-js/issues/3578 already. Please track the same for more updates
