### ISSUE TITLE
Ranges behave different after replacing in Word on Web and on desktop

### ISSUE THREAD

**Issue by gion-andri** [OfficeDev/office-js#3362]
# Provide required information needed to triage your issue
Replacing a range behaves different in Word on web and on desktop

## Your Environment

macOS
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.72 (23040900)
* Operating System: macOS Ventura
* Browser (if using Office on the web): -

Web
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.16510.41005
* Operating System: macOS
* Browser (if using Office on the web): Chrome and Firefox
 
## Expected behavior

To work with the APIs, I expect them to behave the same on both platforms.

## Current behavior

The same API works different on different platforms. This makes it difficult to use the results to continue.

## Steps to reproduce

1. Install that Gist in Script Lab: `https://gist.github.com/gion-andri/c9e02c520d023169123bc274a6fd4501`
2. Click the `Setup` button to create a simple content for the word document.
3. Click the `Run` button to execute the code. It logs the text content in the range after the replace operation into the document.

When run on the web, it contains
```
Range contains before replacing: shrt sentence. 
Range contains after replacing: short sentence 
```
(mind the missing period after the second sentence: The range has still the same size and startingpoint, but as the sentence is longer now, the period is not part of the range anymore).

When run on Word for macOS, it containes
```
Range contains before replacing: shrt sentence.
Range contains after replacing:  sentence.
```
(the replaced word is not part of the range anymore, the range starts with the space character after the first word. But it still contains the period after the sentence)

## Link to live example(s)

1. `https://gist.github.com/gion-andri/c9e02c520d023169123bc274a6fd4501`

## Context

We suggest changes to the text the user enters. We need the text of a paragraph after we replaced a word in it to create the next suggestion. 

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by xiaoyuMS** [comment]
Hi @gion-andri 
Thanks for reporting this. The current range object is not a dynamic range on Word Web while it should be adjusted properly on Desktop. So there should be two potential bugs:
1. The range object can't adjust itself when it is changed on Word Web.
2. The range object gets shrunk when there is a sub-range that gets replaced on Word Desktop.

Two bugs have been created for internal tracking VSO#7908063, VSO#7908067.

**Comment by gion-andri** [comment]
@xiaoyuMS Do you have any news on this?

**Comment by xiaoyuMS** [comment]
@gion-andri Sorry for the inconvenience caused by the bug. We appreciate your patience and understanding as we need to prioritize the work item in the backlog.

**Comment by jipyua** [comment]
hi @gion-andri for the desktop issue VSO#7908067, it has been fixed and will be deployed in coming builds. Feel free to have a try and let us know your feedback. thanks.

**Comment by xiruatms** [comment]
@gion-andri , we've provided a fix. It'll be rolled-out soon.

**Comment by gion-andri** [comment]
Where will it be rolled out? Did u fix VSO#7908063 and VSO#7908067 ?

**Comment by jaiswalshubh1** [comment]
Hi @gion-andri ,

As per the internal ticket: 7908067, issue has been fixed, can you please verify from your side ? 

CC: @kustonaut 

Thanks!
Shubham Jaiswal

**Comment by gion-andri** [comment]
@jaiswalshubh1 
Was VSO#7908063 fixed too? Or only VSO#7908067?

**Comment by gion-andri** [comment]
Was VSO#7908063 fixed too? Or only VSO#7908067?

**Comment by kustonaut** [comment]
@gion-andri From internal tracking ids I can see only "The range object get shrunk when there is a sub range get replaced" was fixed and "When the range object is changed, it cannot be adjusted automatically." was not. May I request you to raise a fresh Issue for "When the range object is changed, it cannot be adjusted automatically." so that we can re-traige, repro and prioritize this issue?

**Comment by gion-andri** [comment]
@kustonaut  I still can reproduce both issues reported with the exact steps indicated in the issue. Just execute them, you still see the exact issue described. Nothing changed. 

I don't see why I should open an new issue. The behaviour is still exactly the same 3.5 years ago. 

Fix the problem internally instead of constantly bothering volunteer, unpaid contributors.
