### ISSUE TITLE
Word Office.js is now throwing RichApi.Error: NotImplemented

### ISSUE THREAD

**Issue by figgsoftware** [OfficeDev/office-js#3587]
After the August 10th update Word Office.js is now throwing RichApi.Error: NotImplemented for certain scenarioes where content controls are replaced with html. This didnt happen earlier.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96fd2dec-eed6-4e7d-0f11-b01228543555
* Version Independent ID: 1b5b34ee-5d87-e115-9a98-21a66c5ae644
* Content: [Office client application and platform availability for Office Add-ins - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/requirement-sets?view=common-js-preview)
* Content Source: [docs/requirement-sets/requirement-sets.md](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/requirement-sets/requirement-sets.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @figgsoftware,

Thank you for raising this issue. I'm going to transfer this to the [office-js repo](https://github.com/OfficeDev/office-js) where product bugs are triaged.

**Comment by olimpiapater** [comment]
We at Mendeley Cite are also experiencing this issue on Word Desktop. Our users are unable to use the add-in after updating Word to version 16.76 and the complaints we are receiving suggest that most users are experiencing this on Mac OS.

**Comment by ddesh5208660** [comment]
Yes, I am also facing too in Mac after some kind of update. Please resolve this ASAP.

**Comment by sergiosagu** [comment]
Hi @figgsoftware, @olimpiapater, @ddesh5208660,

Thank you for reporting the issue. The fix has been completed and it's in the process of being deployed...

Could you, please, confirm if you are part of the Microsoft 365 Insider program and the Beta Channel or Current Channel (Preview)?

**Comment by Xanthic-Orchid** [comment]
@sergiosagu , I got this issue as well with Mendeley Cite. I'm on the Current Channel on MacOS. (App store Word version 16.76)

**Comment by tga93** [comment]
Also have this issue with Mendeley Cite on Microsoft Word v.16.76 MacOS - how long will the fix take to be deployed? Have a very pressing thesis deadline...

**Comment by Xanthic-Orchid** [comment]
> Also have this issue with Mendeley Cite on Microsoft Word v.16.76 MacOS - how long will the fix take to be deployed? Have a very pressing thesis deadline...

The Windows-version (Click to Run) still works with Cite. I'm in the same situation (regarding the thesis-deadline) and moved over as soon as i discovered that the Windows Version still works. I hope this is an option for you as well.

**Comment by figgsoftware** [comment]
> Hi @figgsoftware, @olimpiapater, @ddesh5208660,
> 
> Thank you for reporting the issue. The fix has been completed and it's in the process of being deployed...
> 
> Could you, please, confirm if you are part of the Microsoft 365 Insider program and the Beta Channel or Current Channel (Preview)

The issue seems to be present in the regular channels also. We are seeing the issue on both Windows and Mac. @sergiosagu

**Comment by DerekKarssenberg** [comment]
Same problem here, MS Word v 16.76 MacOS. Mendeley plugin does not work after updating from 16.75.

**Comment by ilirjn** [comment]
> Thank you for reporting the issue. The fix has been completed and it's in the process of being deployed...

Hi @sergiosagu , Mendeley Cite rep here. Will you be updating this thread once the fix has been deployed successfully, as that information will help us with our user comms. Thank you.

**Comment by davidchesnut** [comment]
Hi @sergiosagu, I assigned this issue to you. Can you please update status when the fix is deployed? Thanks!

**Comment by suvo9965** [comment]
Hello all, is there any update on fixing this? Hoping for this to resolve soon as I use Mendeley all the time for reference purposes while writing my academic essays.

**Comment by A-Wag** [comment]
Any update on this would be great! I am frantically working towards a thesis deadline in the coming days, using Mendeley, and desperately need resolution on this! Fingers crossed it'll be back up and running tomorrow.

**Comment by GAGAKUMA-18** [comment]
This sucks I can't use Mendeley cite on my Mac. how long should we wait because we have papers to write and they come with deadlines? The new Mendeley is terrible

**Comment by KatherineYii** [comment]
When it can be used?

**Comment by greatescape95** [comment]
Possible connected issue with possible same root cause (content control api throws error, starting to appear with latest Mac OS version update 16.76): https://github.com/OfficeDev/office-js/issues/3593

**Comment by tga93** [comment]
Is the issue with Mendeley Cite going to be sorted today? I need to be able to export my bibliography by tomorrow for a thesis deadline and this isn't at all ideal

**Comment by Xanthic-Orchid** [comment]
> 
Use a Windows PC. Don't wait for a fix for this. The problem lies with Microsoft. They are investigating. There is no guarantee that if the fix will release today it will solve the Mendeley Cite issue. Mendeley Cite for the web still works and it still works on Windows PC's. You are responsible for your own contingency and deadlines.

**Comment by greatescape95** [comment]
Also maybe you can try word online, i belive it works there.

**Comment by tga93** [comment]
I'm getting an 'unable to load references' error on Word online and I don't have access to a Windows PC - I wouldn't be posting here if I had a workaround

**Comment by Xanthic-Orchid** [comment]
> I'm getting an 'unable to load references' error on Word online and I don't have access to a Windows PC - I wouldn't be posting here if I had a workaround

I should not try to help you anymore since you gave me a thumbs down when i was trying to help you. But no issues here with word Online and Mendeley Cite. Clear history and try again? Or if that fails try another browser like Chrome/Firefox?

**Comment by RebeccaGarnham** [comment]
Any updates on how long this will take?

I am on to the final conclusion of my thesis and if I can't get Mendeley cite working on Word version 16.76 ASAP, I think I might just throw my Mac out of the nearest window and sign on the dole instead.

**Comment by fiona1506** [comment]
I would really like this to be the last day that I spend writing my thesis so any signs of life from the people that are working this out would be great

**Comment by sadhedgehog** [comment]
Thanks for reporting this, glad to know the issue has been identified.
It's a joke to force a productivity tool constantly updating to **hot, new, & unstable garbage** features just to break user experience.

**Comment by ilirjn** [comment]
> I would really like this to be the last day that I spend writing my thesis so any signs of life from the people that are working this out would be great

Mendeley rep here. We have this as our highest priority for Mendeley Cite, we are currently exploring a workaround whilst we wait for Microsoft to resolve this on their end. I will update this thread as we progress as well as updating our FAQ on this, I apologise to all of you for the stress and inconvenience this is causing.

**Comment by olinchloe** [comment]
even the web version cannot work!!! I am working on my dissertation, can you fix this asap!! 👎

**Comment by rahmaahnn** [comment]
hi, I also have the same problem on mac after installing word 16.76 ver, I tried this and it works
https://youtu.be/g6FP2gVyd1Q

**Comment by ilirjn** [comment]
> 

Hi, can you confirm which browser you are using? Mendeley Cite is currently working as expected when using Chrome to access Word for the web.

**Comment by ilirjn** [comment]
> even the web version cannot work!!! I am working on my dissertation, can you fix this asap!! 👎

Hi, can you confirm which browser you are using? Mendeley Cite is currently working as expected when using Chrome to access Word for the web.

**Comment by tga93** [comment]
> > even the web version cannot work!!! I am working on my dissertation, can you fix this asap!! 👎
> 
> Hi, can you confirm which browser you are using? Mendeley Cite is currently working as expected when using Chrome to access Word for the web.

I've tried Firefox, Chrome and Safari (in and out of private browsing) and I'm receiving the same error message of 'unable to update references'

**Comment by ilirjn** [comment]
> > > even the web version cannot work!!! I am working on my dissertation, can you fix this asap!! 👎
> > 
> > 
> > Hi, can you confirm which browser you are using? Mendeley Cite is currently working as expected when using Chrome to access Word for the web.
> 
> I've tried Firefox, Chrome and Safari (in and out of private browsing) and I'm receiving the same error message of 'unable to update references'

I have raised this with the backend team as I believe this may be an issue outside of this specific report, please [contact our support team](https://service.elsevier.com/app/home/supporthub/mendeley/) where they will aim to assist you further.

**Comment by DirkHotel** [comment]
Just to add a few more data points.  Working with existing 30pp documents with >50 references... 

- Using Safari, web-based MS-Word fails to load Mendeley Cite.
- Using Chrome, web-based MS-Word loads Mendeley Cite successfully, and updates library successfully.  Editing the document also successfully reorders existing citations.  Adding additional citations in the existing document, however, works initially, but if followed shortly after by One-Drive saving error.  New citations are not retained in reloaded document.

Hope that's helpful and this gets resolved soon!

**Comment by teyahwanig** [comment]
Pls, I'm experiencing a problem with Mendeley Cite using my Lenovo IdeaPad laptop

**Comment by olinchloe** [comment]
> > even the web version cannot work!!! I am working on my dissertation, can you fix this asap!! 👎
> 
> Hi, can you confirm which browser you are using? Mendeley Cite is currently working as expected when using Chrome to access Word for the web.

I was using Safari, and just tried on Chrome. It only works on Chrome.

**Comment by ddesh5208660** [comment]
> Hi @figgsoftware, @olimpiapater, @ddesh5208660,
> 
> Thank you for reporting the issue. The fix has been completed and it's in the process of being deployed...
> 
> Could you, please, confirm if you are part of the Microsoft 365 Insider program and the Beta Channel or Current Channel (Preview)?

I don’t know about any of that but it is also not working on MS Word web. Kindly fix the issue.

**Comment by swervb** [comment]
I saw this with the previous releases in the beta channels... so i down graded to get my work done. Once 16.76 became main channel it impacted Mendelay again... BUT I just swtiched my update preferences to the most beta / preview that my updater shows me, and it works again. So MS maybe did deploy the fix as mentioned above they would be doing... the version I am at for Word now is: 16.77 (23081601) and can confirm the plug in loads as expected, citations do get added, and biblograpy works. Im on macOS Sonoma.

**Comment by swervb** [comment]
> 

Yes... it works. Updates to 16.77 via beta channel

**Comment by tga93** [comment]
Have also updated to 16.77 and it's working again 

For anyone unsure how to update:

Open Word 
Help
Check for updates
Advanced
Change Update Channel to Beta
Select Check for updates again
It should find 16.77 and click download (make sure to close word for it to fully install)

**Comment by sergiosagu** [comment]
Small update on the fix deployment process...
As some of you realized, the fix is already in the beta channel, and the deployment continues, thus if there are no impediments it will reach the other channels in few days.
Fortunately for the Win build, the pipeline caught the fix for the current release build on time. But unfortunately for the Mac build, the pipeline had already generated the release build before getting the fix. And in principle the fix will be present in the next release build early next week.
Once again, sorry for the inconvenience!

**Comment by A-Wag** [comment]
Thanks so much for the swift turnaround - up and running again at my end! Big relief!

**Comment by swervb** [comment]
@sergiosagu Very thankful... there is obviously a few of us in here at various levels of academia and this particular add-in is very useful. Awesome job to your team!

**Comment by haver00** [comment]
Thanks so much for the update, after installing 16.77 beta, working again! So relieved!!

**Comment by bisceg50** [comment]
@sergiosagu Thank you for fixing this quickly. I was panicked (working on dissertation).

**Comment by suvo9965** [comment]
Yay!! It's working, thank you @sergiosagu & @tga93 for the updates and for keeping us posted :)

**Comment by ddesh5208660** [comment]
> Have also updated to 16.77 and it's working again
> 
> For anyone unsure how to update:
> 
> Open Word Help Check for updates Advanced Change Update Channel to Beta Select Check for updates again It should find 16.77 and click download (make sure to close word for it to fully install)

Thanks all for the quick turnaround! it's working with beta channel updates.

**Comment by ikbalhardal** [comment]
> > I would really like this to be the last day that I spend writing my thesis so any signs of life from the people that are working this out would be great
> 
> Mendeley rep here. We have this as our highest priority for Mendeley Cite, we are currently exploring a workaround whilst we wait for Microsoft to resolve this on their end. I will update this thread as we progress as well as updating our FAQ on this, I apologise to all of you for the stress and inconvenience this is causing.

Have also updated to 16.77 and works fine. could you please update the FAQ page as well for guidence?
Thank you all especially @sergiosagu @tga93 @swervb

**Comment by ApurvaG05** [comment]
Hi ! Any updates on the issue?? Im working on my Dissertation with a really tight deadline!
Any updates or solution to this issue would be much appreciated.

**Comment by Xanthic-Orchid** [comment]
> Hi ! Any updates on the issue?? Im working on my Dissertation with a really tight deadline!
> Any updates or solution to this issue would be much appreciated.

Yes, it is fixed in Beta.. See thread for details.

**Comment by ApurvaG05** [comment]
> > Hi ! Any updates on the issue?? Im working on my Dissertation with a really tight deadline!
> > Any updates or solution to this issue would be much appreciated.
> 
> Yes, it is fixed in Beta.. See thread for details.

Oh great ! Updated to the Beta version of 16.77 ! 
It worked !! Thank you!!

**Comment by mchequer** [comment]
ok, sorry to bang on this same drum, but I have the same issue (Microsoft® Word for Microsoft 365 MSO (Version 2308 Build 16.0.16731.20052) 64-bit ). How can I get Word update? or when will it be generally released because this affects all users of our Add-in. Checking in the word (Account -> Update options -> Update now) there is nothing new available.

Appreciate any advice, tips, because currently I'm dead in the water with no work around.

**Comment by swervb** [comment]
Have to change your update settings to the beta channels. Someone posted directions up above.

**Comment by mchequer** [comment]
I've updated, but I still have the same issue, this is crazy, this is such as basic command. With a blank document and plain text no issues, if I add one content control (from the word menu) this is the code that fails, and this is the word version (Microsoft® Word for Microsoft 365 MSO (Version 2309 Build 16.0.16811.20000) 64-bit )
    
await Word.run(async (context) => {
      const ourContentControls = context.document.contentControls;
      ourContentControls.load("items");
      await context.sync();    

this is the error

RichApi.Error: NotImplemented
    at new n (:25:263863)
    at i.processRequestExecutorResponseMessage (:25:328309)
    at https://appsforoffice.microsoft.com/lib/1.1/hosted/word-win32-16.01.js:25:326372

**Comment by xtnsele** [comment]
I also faced the same problem, but I was able to find a temporary solution by using this link.: https://techdirectarchive.com/2023/08/19/mendeley-cite-ecite40001-error-fix-issue-using-on-microsoft-word-desktop-application/

**Comment by sadhedgehog** [comment]
> I've updated, but I still have the same issue, this is crazy, this is such as basic command. With a blank document and plain text no issues, if I add one content control (from the word menu) this is the code that fails, and this is the word version (Microsoft® Word for Microsoft 365 MSO (Version 2309 Build 16.0.16811.20000) 64-bit )
> 
> await Word.run(async (context) => { const ourContentControls = context.document.contentControls; ourContentControls.load("items"); await context.sync();
> 
> this is the error
> 
> RichApi.Error: NotImplemented at new n (:25:263863) at i.processRequestExecutorResponseMessage (:25:328309) at https://appsforoffice.microsoft.com/lib/1.1/hosted/word-win32-16.01.js:25:326372

You are not alone, I have also updated to the latest beta build and the problem remains.
`Microsoft 365 MSO (Version 2309 Build 16.0.16811.20000) 64-bit `

Would be great if Mendeley folks @ilirjn could take a note, it seems that most people here are on the non-MSO Mac and Windows build, no mentioning of 365 MSO so far.

Serves me right to trust these merge-and-pray SSAS internet 3.0 garbage solutions from Microsoft, should've gone with the MSI install.

**Comment by mchequer** [comment]
Dear MS team, firstly I love office.js, but I am feeling very exposed with this big. Essentially, it stops dead my product (Claims Letters) which is used by a number of insurance companies. Can you confirm you are still working on this issue, because the beta version you released to the channel does not address the issue I am experiencing.

Best.
Mark
,

**Comment by MuhammadAliKhalid-MAK** [comment]
To resolve this issue, it is recommended to initiate the following steps: Firstly, launch the Microsoft Word application. Next, go to the "Help" section and proceed to choose the "Check for updates" option. Subsequently, click on the "Advanced" tab and, of utmost importance, modify the Update Channel to "Beta". Finally, reselect the "Check for updates" option to complete the process.
The user is advised to locate the value of 16.77 and initiate the download process, ensuring the closure of the Word application to complete the installation.
In due course, the issue will be resolved. Personally, I am really relieved by this outcome, since it was not functioning as intended. Wishing you the best of luck.

**Comment by MalikMuneebAhmad** [comment]
I am still facing the same issue even after updating on beta channel
My current version is Microsoft 365 MSO (Version 2309 Build 16.0.16811.20000) 64-bit.

**Comment by ZYUN-MSFT** [comment]
Hi all,

Really sorry that this issue bring a lot of confuse and bad experience to you. Our team is still pushing the roll out status, and we will continuesly driving the process and update the information here once the process has been done.

For Mac user, update the office to beta channel will mitigate this issue (we are pushing the roll out status to production).\
For Win user, this issue currently only affect beta user, and the latest beta will be avaliable in these days (which should solve this issue).

**Comment by mchequer** [comment]
Hopefully this helps:

This was working, but no longer `works`

`await Word.run(async (context) => {
	const ourContentControls = context.document.contentControls;
	ourContentControls.load("items");
	await context.sync();
`

This does work, so it's a difference between "Items and id"
`
await Word.run(async (context) => {
	const ourContentControls = context.document.contentControls;
	ourContentControls.load("id");
	await context.sync();
`

**Comment by ghost** [comment]
Hi everybody. I cannot use Mendeley on Word even after the update today. what can i do? I have windows pc, and there is no advanced option for the update thing. what can I do? please help!

**Comment by tkichuk** [comment]
The Mendeley fix is not working on the beta version or on the web platform. When can we expect a fix?

**Comment by ilirjn** [comment]
Hi all, a new version of Mendeley Cite (1.60.0) has now been released, this should resolve the issue with using Microsoft Word 16.76 - Apologise for the inconvenience this has caused. For any other support queries please feel free to reach our [support team](https://service.elsevier.com/app/home/supporthub/mendeley/) - they are more than happy to help! Thank you.

**Comment by Xanthic-Orchid** [comment]
Can confirm. I reverted back to 16.76 (App Store edition) from 16.77 Beta and it works. Working with beta-editions felt risky. Good work from Microsoft and Elsevier Mendeley on this issue.

**Comment by koppie04** [comment]
> Hi all, a new version of Mendeley Cite (1.60.0) has now been released, this should resolve the issue with using Microsoft Word 16.76 - Apologise for the inconvenience this has caused. For any other support queries please feel free to reach our [support team](https://service.elsevier.com/app/home/supporthub/mendeley/) - they are more than happy to help! Thank you.

Hello! How do you get the new version? I'm so lost now for all those issues since last week. I can start my thesis paper because of this issue.

**Comment by xtnsele** [comment]
Hi All, for those of you who used this [guide](https://techdirectarchive.com/2023/08/19/mendeley-cite-ecite40001-error-fix-issue-using-on-microsoft-word-desktop-application/) in implementing the workaround before the new release of Mendeley Cite (1.60.0), this information has been updated. 
![Mendeley Cite 1 60 0](https://github.com/OfficeDev/office-js/assets/26944958/56509f6f-c061-42c0-b684-ca6458861f2c)

**Comment by sergiosagu** [comment]
For folks facing this issue on Word for Windows and on the Beta Channel, please, check if the update build 16.0.16818.20000 (released yesterday) fixes the issue on your side. Builds released after 16.0.16815.20000 should contain the fix.

**Comment by larrywelch** [comment]
There is a great deal of information regarding Word for Mac, however, very little on Word for Windows.  We have an addin that is dead due to this issue.  Asking our customers to downgrade/revert Microsoft Office is a terrible solution.  We can't ask our users, who are not technical, to perform downgrade or beta channel activities.  What is the timeframe for this fix making it to mainstream?  What is the source of the problem, is there a coding work around?

**Comment by larrywelch** [comment]
I just joined the Microsoft 365 Insider program using the option in Word (Word->Account->Microsoft 356 Insider).  I then changed my channel to Beta, restarted, attempted to update and get the following:
<img width="365" alt="image" src="https://github.com/OfficeDev/office-js/assets/25418400/a13b0343-13e3-4740-ac34-bbea402cc2ef">

Please advise!

**Comment by hengchengfei** [comment]
@mchequer  @larrywelch work ground as follows:

replace
```js
 controls.load("items, id, tag")
```
with
```js
 controls.load(["items", "id", "tag"])
```

**Comment by ZYUN-MSFT** [comment]
Hi all, this issue should be fixed now. If you still have the error, please update to the newest version of Office and retry, thanks.
