### ISSUE TITLE
Send email blocked after several emails have been sent with ItemSend event based addin

### ISSUE THREAD

**Issue by elemen7s** [OfficeDev/office-js#3709]
We have an event based addin which makes use of OnMessageCompose and ItemSend events. We are getting a lot of reports from customers who got blocked from sending emails until the outlook client is restarted. 

We have been able to reproduce this issue and from the developer tools we were able to see that our events are not being triggered. The email gets blocked for 5 minutes and the send button disabled. Once the 5 minutes pass it gets re-enabled but on sending again the email is blocked again. 

The issue happens after sending multiple emails one after the other in the same session. An error (Cannot read properties of undefined (reading 'userIdentity')) is shown in the console as in screenshot below and the Send button is blocked until the client is refreshed/restarted. When the Send button is clicked, the ItemSend event of the addin is not triggered.

Note that the error below is not caused by our addin. The error is linked to a file named owa.mailindex.js with this url https://[res-h3.public.cdn.office.net/owamail/20230915006.14/scripts/owa.mailindex.js](https://res-h3.public.cdn.office.net/owamail/20230915006.14/scripts/owa.mailindex.js)

<img width="910" alt="image" src="https://github.com/OfficeDev/office-js/assets/10210686/398f5a1b-d72c-4d25-a63e-f522d3ae63cd">

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop, Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Windows
* Browser (if using Office on the web): Edge/Chrome/Firefox
 
## Expected behavior
Expected behavior is for the emails to never be blocked and addin ItemSend event is always triggered. Furthermore no errors from outlook should affect the execution of the addin.

## Current behavior
After sending multiple emails, an error is shown in the console and once the Send button is clicked, email is blocked and ItemSend event is never triggered.

## Steps to reproduce
1. Open dev tools (in case of web)
2. Send multiple emails, one after the other (sometimes up to 15 or more emails)
3. As soon as you see the error in console, on the next Send button click, the issue occurs (Error: Cannot read properties of undefined (reading 'userIdentity'))

## Useful logs

`owa.mailindex.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'userIdentity')
    at r (owa.mailindex.js:2:42784)
    at a (owa.mailindex.js:2:106567)
    at o (owa.mailindex.js:2:100280)
    at owa.MailBoot.m.js:6:721995
    at r (owa.MailBoot.m.js:6:722124)
    at owa.AddinsCore.m.js:1:160638
    at W (owa.AddinsCore.m.js:1:160875)
    at Y.insertOsfControl (owa.AddinsCore.m.js:1:163693)
    at refCallback (owa.AddinsCore.m.js:1:168104)
    at Ru (owa.ven.extframework.m.js:2:209304)`
<img width="908" alt="image" src="https://github.com/OfficeDev/office-js/assets/10210686/600c2556-7273-452d-89e6-0f20cc78a474">

**Comment by elemen7s** [comment]
@exextoc 

Any updates for this issue?

We wanted to double check that this issue does not have anything to do with our add-in so we created a new test tenant without our add-in installed and sent a bunch of emails. The exact same exception was logged. Since there was no add-in installed which hooks to the ItemSend the email was not stopped from sending however the first email that was sent lagged a bit. All subsequent emails were sent normally.

Please treat this issue with priority since we are getting lots of customer complaints because of this issue.

**Comment by Harleymckee** [comment]
My team is experiencing the same issue

**Comment by t-ariyoshi30907** [comment]
@exextoc 
The same issue is occurring with my product as well. The problem arises with approximately a 1/5 probability. Please make improvements as customers are facing difficulties.

**Comment by zhngx1** [comment]
Thanks for reporting this. Does the issue happen only on the web or it happens to Outlook windows app as well?

**Comment by t-ariyoshi30907** [comment]
@zhngx1 
Both similar issues are occurring, but it's unclear if they are the same problem. In Outlook on the web, there is an error related to "'userIdentity'," while in Outlook for Windows, I cannot check the console content. Please advise on how to check the console in Outlook for Windows.

**Comment by elemen7s** [comment]
@zhngx1 We had reports from customers on both web and outlook windows with the exact same behaviour.

**Comment by t-ariyoshi30907** [comment]
@zhngx1 @exextoc 
Could this issue not occur in your environment? If it doesn't, I can provide more information. Many customers are facing this problem, so could you please prioritize addressing it?

**Comment by zhngx1** [comment]
Can you provide minimum repro steps? For example, a simple manifest with simple JavaScript files for your event functions. 
It would also help if you can provide the build number for your windows Outlook. A video would also help for us to repro but please edit out any private data or use a test account. 

When you are responding, please indicate if the answer is for windows or web client.

**Comment by t-ariyoshi30907** [comment]
@zhngx1 

I will provide my execution environment and include the reproduction steps, so please give it a try.

■Environment
OS: Windows10
Platform: Outlook on the web
Web-browser: Google Chrome or microsoft Edge

■Steps to reproduce
Access the following URL.
　https://drive.google.com/file/d/1Xrc-HuBLSjBAwDmU7y7Pbi7amwegbPDY/view?usp=share_link
Download "sample.zip" and place it in your desired location.
Launch the command prompt and navigate to the corresponding directory.
Run "npm install".
Run "npm run dev-server".
Upload "manifest.xml" in Outlook on the web to install the add-in. (The XML file is stored in sample.zip)
Create and send an email.
Sending emails approximately 5 to 10 times.

**Comment by t-ariyoshi30907** [comment]
@zhngx1 
Last week, I provided you with the execution environment and replication procedures. Can you reproduce this issue in your environment? Please let me know the status of your investigation.

**Comment by elemen7s** [comment]
@exextoc @zhngx1 Are there any updates on this please? This was opened over 2 weeks ago and there are still no updates, even after @t-ariyoshi30907 provided steps and example how to reproduce it again.

**Comment by exextoc** [comment]
Apologies for delayed response. And thanks for reporting this issue. This has been fixed and getting rolled out. The fix should be available by end of this week

**Comment by elemen7s** [comment]
@exextoc Thank you for the prompt reply and for deploying the fix.

**Comment by exextoc** [comment]
@elemen7s Can you confirm for which windows app does it happen, new outlook or classic/old one?

**Comment by t-ariyoshi30907** [comment]
@exextoc 
Thank you for your quick response! The error is still occurring on Outlook on the web, but I will check the functionality again this weekend.

**Comment by elemen7s** [comment]
> @elemen7s Can you confirm for which windows app does it happen, new outlook or classic/old one?

@exextoc We have had reports on windows old for sure and on web. We are not 100% sure this also happened on outlook new but since outlook new and web are sort of the same, we assumed it is happening on the new one as well.

On web it is still happening for us aswell, we will check again after the roll out.

**Comment by elemen7s** [comment]
@exextoc We are still experiencing the same issue on Outlook Web. Was the fix fully deployed ?

@t-ariyoshi30907 / @Harleymckee  Are you still experiencing the same issue?

**Comment by t-ariyoshi30907** [comment]
@elemen7s 
I just tested it. I opened Outlook on the web using the Chrome browser.
The first time I tried, the same issue as before occurred.
However, when I cleared the browser cache and tried it in incognito mode, the issue did not occur.
If you clear the browser cache or try it in incognito mode, will the issue occur again in your environment?
@Harleymckee . Are you still experiencing the same issue?

**Comment by exextoc** [comment]
Fix is rolled out 100% for Outlook on the Web. Please let us know if you are still facing the issue.

**Comment by elemen7s** [comment]
@exextoc Just finished testing and could not reproduce it on Outlook web. Was the fix also rolled out on Windows Client? So we start testing that as well.

**Comment by Harleymckee** [comment]
My team is still reporting this issue in web and the new Outlook client today

**Comment by zhngx1** [comment]
I was not able to repro on Windows client using the sample provided by @t-ariyoshi30907.
@elemen7s Can you provide the build number for your client and let me know if you are using the new Outlook or the old Outlook windows client.

**Comment by elemen7s** [comment]
@zhngx1 One of the customers who reported the issue was on Microsoft Outlook (Version 2308 Build 16.0.16731.20182) 64 Bit. The problem for this customer occurred on the 20.09.2023 between 10:00 and 10:25 AM.
 
We are still checking if it is still happening on windows clients.

**Comment by zhngx1** [comment]
Thank you @elemen7s. Please let us know if your customers are still running into the issue.

**Comment by ArkaiAriza** [comment]
My team is experiencing a similar issue, but instead is the OnMessageCompose event the one that is, seemingly, not being triggered.

Basically after sending several emails (15+) opening a Compose Window does not trigger the event. It seems like it doesn't even try to fetch the add in files. The OnMessageSend event works correctly.

Edit: No strange errors in the console.

**Comment by zhngx1** [comment]
@ArkaiAriza Do you see the error on Outlook Web or Outlook Windows or Outlook Mac? If it's on Outlook Windows, is it the new Outlook or the old Outlook and if you can provide the build number?

**Comment by ArkaiAriza** [comment]
Sorry for not clarifying. The error presents in Outlook Web. We haven't tested Windows nor Mac.

**Comment by zhngx1** [comment]
@ArkaiAriza  A fix has been rolled out last week. Can you please double check if you can reproduce the error?

**Comment by ArkaiAriza** [comment]
Hi. Yes, I can reproduce the error as of this morning. In Outlook web, both using out addin and using a mostly empty one.

**Comment by exextoc** [comment]
@ArkaiAriza ItemSend and onMessageCompose are two different things. Could you please create a separate Github issue with the platform, version and use case details. 

@elemen7s Do you still see this issue in your initial use case?

**Comment by elemen7s** [comment]
> @ArkaiAriza ItemSend and onMessageCompose are two different things. Could you please create a separate Github issue with the platform, version and use case details.
> 
> @elemen7s Do you still see this issue in your initial use case?

Issue looks like it has been fixed. Ticket can be closed.

**Comment by exextoc** [comment]
@elemen7s Thanks for the confirmation. Closing.
