### ISSUE TITLE
Outlook getSelectedItemsAsync throws elevated permission error (Office on the web)

### ISSUE THREAD

**Issue by manuelsidler** [OfficeDev/office-js#3914]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Office 365
* Operating System: macOS Sonoma 14.2
* Browser (if using Office on the web): Edge for Mac (Version 120.0.2210.61 (Official build) (arm64))
 
## Expected behavior
When selecting multiple items and calling `Office.context.mailbox.getSelectedItemsAsync`, it should return the selected items.

## Current behavior
When running the add-in on Outlook on the web, calling `Office.context.mailbox.getSelectedItemsAsync` throws an error:
<img width="575" alt="image" src="https://github.com/OfficeDev/office-js/assets/802015/463f586c-b904-40d2-8dc6-92bc16499403">

## Steps to reproduce
1. Clone the example GH repo to reproduce the issue (see link below)
2. Run the add-in with `npm install` and `npm run dev-server`
3. Side load the add-in on Outlook on the web
4. Select multiple items
5. Open the add-in
6. Click the _Get selected items_ button
7. Open the developer tools
8. The console contains the error (see screenshot above)

The same steps on Outlook for Mac work fine.

## Link to live example(s)
- GitHub Repo with example to reproduce: https://github.com/manuelsidler/outlook-addin-multiselect

## Context
The permissions in the manifest are set to `ReadWriteMailbox`

**Comment by exextoc** [comment]
@manuelsidler   We do not have a repro of this issue with your add-in. On clicking Get Selected Items, Add-in is displaying the selected Item info both on OWA and Mac.
<img width="348" alt="image" src="https://github.com/OfficeDev/office-js/assets/28549921/8ed71b8d-7b53-429d-817b-0928820a1512">

Is the issue occurring intermittently? It would help if you can share a repro video.

**Comment by manuelsidler** [comment]
@exextoc thank you for taking time to investigate our issue. The error occurs every time when calling `getSelectedItemsAsync`. I also tried it on Edge on Windows. Please find attached the video.

https://github.com/OfficeDev/office-js/assets/802015/be97767d-7419-41a7-b22b-30f4c5bbb581

**Comment by exextoc** [comment]
@manuelsidler We have recently checked in a fix for this issue and fix will be 100% rolled out by end of week. Please try this again next week and let us know if issue persists.

**Comment by CameronDwyer** [comment]
I've been blocked with this issue as well. Great to see a fix has been worked on. I look forward to it rolling out and giving it a test.

**Comment by manuelsidler** [comment]
@exextoc the issue has been fixed, thank you!

**Comment by JonasBjerke89** [comment]
I did experience the same issue back in December both in OWA + PWA versions of Outlook, but it worked before then we did the actual implementation of "supportsMulti" in November.

The issue doesn't seem to be resolved (sorry for the danish):
![image](https://github.com/OfficeDev/office-js/assets/21952399/80f7c39c-a83d-4e75-be87-6b5d3cc9275c)

Anyone else still seeing this issue?

**Comment by kirtisuri** [comment]
This issue is happening when we are using other regular user except for Global admin and Outlook on web. For Global admin it works fine. In the manifest have the permission set as ReadWriteMailbox.

For regular user. When  selecting multiple emails the event handler that we use to get the selected items does not consistently return the selected email items. The  Outlook getSelectedItemsAsync throws "Internal error has occured". The error does not have any specific error codes.
Is it that the manifest I am using does not have the fixes that were done by Microsoft recently? How to make sure I am using the later version of Office.js In my html page I have 
 <script src="https://appsforoffice.microsoft.com/lib/1.1/hosted/Office.js" type="application/javascript"></script>

Here is the screenshot of the error:

![error](https://github.com/OfficeDev/office-js/assets/157402030/fd04853f-c0fc-4a6d-9bee-f551fb5ad5a1)


Is there any specific permission that is needed. For regular users? I tried to check the Office.context.mailbox.initialData and the permission level is set as 3 for this user.

**Comment by JonasBjerke89** [comment]
Changed manifest permission to "ReadWriteMailbox". Updated, waited a few days and our client reports back that it works as expected in Outlook web and Outlook New 💪

**Comment by kirtisuri** [comment]
@JonasBjerke89 What is the version you specified in the manifest file ?
