### ISSUE TITLE
Outlook Task pane does not close on item change

### ISSUE THREAD

**Issue by wilcotroost** [OfficeDev/office-js#3995]
Recently the behaviour of the Outlook AddIn changed. Before if you opened a task pane it would close automatically as soon as you clicked a different message in the Outlook email message list. 

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Browser (if using Office on the web): Chrome, Safari, Edge
 
## Expected behavior
An opened TaskPane closes as you click on a different email

## Current behavior
The opened TaskPane does not close

**Comment by Oleg-O** [comment]
I was unable to reproduce this. Do you consistently reproduce this? What's your client version?

**Comment by wilcotroost** [comment]
> I was unable to reproduce this. Do you consistently reproduce this? What's your client version?

Hello Oleg, I can constantly reproduce this. We did not change the code on our side but this behaviour appeared overnight.

The version of outlook online seems to be 20231215008.10

I uploaded a screencast;

https://github.com/OfficeDev/office-js/assets/5337155/22dcf87a-fd77-456a-b868-b51c41009a8e

**Comment by exextoc** [comment]
@wilcotroost Can you try this in version latest 20240105 + version?

**Comment by wilcotroost** [comment]
I will if someone explains to me how I can change the version of Outlook Online.
I was under the impression that Microsoft decides which version they present to you. 

By the way: I am not completely sure about the version I mentioned. A coworker used a microsoft utility to show the version. I did not find any menu or option that showed the version of my Outlook online application.

**Comment by exextoc** [comment]
@wilcotroost For finding outlook web version and channel - append view-source: to your outlook web url in the address bar. For example: view-source:https://outlook.office.com/mail/ .
In the source , search for "meta name=scriptVer" . This will give the version.

**Comment by wilcotroost** [comment]
@exextoc Thanks! The correct version is : 20240105004.04

**Comment by ajays-msft** [comment]
@wilcotroost - This issue is fixed in newer builds. > 20240105

**Comment by wilcotroost** [comment]
@ajays-msft Thanks for the update! Any idea when this version will be distributed to us?

**Comment by ajays-msft** [comment]
It will be available by 1/19

**Comment by wilcotroost** [comment]
@ajays-msft My current Outlook version is 20240112004.09 but the problem remains the same.

**Comment by jkirby** [comment]
@ajays-msft We are experiencing the same issue where an unpined addin task pane no longer closes when swapping emails.
This behavior is the same on web version 20240112004.12 and desktop outlook (Microsoft Outlook Version 1.2024.111.100 (Production). Client Version is 20240112004.12)
The issue is not just with our custom addin but with Microsoft addins like SendToOneNote / ShareToTeams and all thirdparty addins as well.
If the add in is pinned, the addin works as expected however, if not pinned and the user swaps to a new email then addin's context is still linked with the original email. (this means many incorrectly filed emails) 
This behavior began for us on Monday 22 Jan 24.
Please fix.

**Comment by jkirby** [comment]
> @ajays-msft We are experiencing the same issue where an unpined addin task pane no longer closes when swapping emails. This behavior is the same on web version 20240112004.12 and desktop outlook (Microsoft Outlook Version 1.2024.111.100 (Production). Client Version is 20240112004.12) The issue is not just with our custom addin but with Microsoft addins like SendToOneNote / ShareToTeams and all thirdparty addins as well. If the add in is pinned, the addin works as expected however, if not pinned and the user swaps to a new email then addin's context is still linked with the original email. (this means many incorrectly filed emails) This behavior began for us on Monday 22 Jan 24. Please fix.

Today the issue seems to have been resolved. (Outlook Version 1.2024.111.100 (Production). Client Version is 20240119003.09)

**Comment by exextoc** [comment]
The issue has been fixed. Please hard refresh your browser and confirm.

**Comment by wilcotroost** [comment]
@exextoc Everything works like a charm. Thanks!

**Comment by imjohnparsons** [comment]
I am also seeing this issue with the web version scriptVer content=20240202008.10
sometimes when I first open outlook it pops up on its own without any user interaction to the app

**Comment by imjohnparsons** [comment]
[Recording-20240207_131706.webm](https://github.com/OfficeDev/office-js/assets/43581158/c7d873c0-10f7-4c88-b55a-253854b225c8)
