### ISSUE TITLE
WOPI ADD-IN Button showing "Popular Addins"

### ISSUE THREAD

**Issue by SirDavenport** [OfficeDev/office-js#4058]
# Provide required information needed to triage your issue
We have a microsoft wopi implementation in production and test, and we preinstall **1** add-in. However, when we open word, excel, and powerpoint documents in wopi, when we click the "Add-ins" button, it shows "Popular Add-ins" and allows us to install them which is something we do not want because it is not secure.
## Your Environment

Wopi in the web. Build: 16.0.17323.41000
 
## Expected behavior
There should be no Popular addins. The wopi documentation says the only addins you'll have are the ones you preinstall and the ones you sideload.

## Current behavior
There are popular add-ins that can be installed.

## Steps to reproduce
1. Open a document in wopi.
2. Click the addins button.
3. See popular addins.
![image](https://github.com/OfficeDev/office-js/assets/35716952/4c72c373-41be-4efa-b09e-297f40fdb915)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by AkhileshShah-MS** [comment]
Hi @SirDavenport ! Thanks for reaching out to us for the issue. Our team will look into this issue and get back to you. 
One quick question - Are these popular apps only discoverable or users are able to install them as well i.e. when trying to add, does is succeed or fails? 
@Wenjun-Gong Could you please help look into this issue.

**Comment by dil-sumishra** [comment]
I am facing similar issue. I don't need user to see the Popular Addins.

**Comment by SirDavenport** [comment]
@AkhileshShah-MS Hi, thanks for the reply. The users CAN install the popular add-ins. It does the thing where it fails the first time, and then you have to refresh the WOPI page, and then the next time you try to install the popular add-in, it will install.

**Comment by JinghuiMS** [comment]
Thanks for reporting this issue. It has been put on our backlog<Bug#8703711> for internal track. We will keep track of this issue and let you know if there are any updates.

**Comment by SirDavenport** [comment]
@JinghuiMS Appreciate that, but it is a pretty big security issue, and I'm sure once other people realize its happening, you'll get a lot more of these posts. What are the chances we can get this expedited?

**Comment by gingerjia** [comment]
hi @SirDavenport, thanks very much for the kindly reminding! We have been working actively on the fix and try to unblock users as quickly as possible. We will keep the status update here when have any progress. 
Really high appreciated for your great support to make us doing better!

**Comment by gingerjia** [comment]
hi @SirDavenport, our fix has been deployed to Word and PowerPoint PROD env. For Excel, the fix is still under deployment. Could you help to validate at your side to make sure the issue has been resolved when you are convenient? 
Thanks again for your great support and help to us!

**Comment by SirDavenport** [comment]
Hi @gingerjia, Just tried and got an Inserting (loading) and then a Waiting (loading), and then nothing happened after that.

**Comment by SirDavenport** [comment]
Hi @gingerjia, Sorry, I originally thought this was a different ticket, so I deleted that comment. Yep for word it looks like the addin button in wopi no longer has the Popular addins. Thanks!

**Comment by SirDavenport** [comment]
Hi @gingerjia, however, it does seem like sometimes we still see the Popular add-ins.

**Comment by gingerjia** [comment]
@SirDavenport thanks very much for helping to validate the fix! Could you help to share the session id to us if the issue repro again? This would be helpful for us to identify the root cause. You can get the session id by clicking [File] button and go to [About] tab. 
<img width="445" alt="image" src="https://github.com/OfficeDev/office-js/assets/62282034/403bb260-a8ff-4f16-8d67-35c15882010a">
Thanks again for your support!

**Comment by SirDavenport** [comment]
Unfortunately they closed the window and haven't seen the issue again. I'll try and grab the session id if it comes up again, thanks.
