### ISSUE TITLE
Office outlook ItemId and get getSharedPropertiesAsync bug

### ISSUE THREAD

**Issue by SE-Hubert** [OfficeDev/office-js#4781]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Pc desktop (new outlook) and office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 1.2024.725.400 (Production)
* Operating System: windows
* Browser (if using Office on the web): chrome
 
## Expected behavior
When trying to get the itemId in compose mode. We save the message and as an callback result we have the itemId:
```
                Office.context.mailbox.item.saveAsync(async (result) => {
                    const itemId = result.value;
                });
```

For the getSharedPropertiesAsync, we call the function and we should get the shared properties of a given shared mailbox if the function is defined.

## Current behavior
For the itemId currently in the desktop version of outlook the first time we save the compose message, the itemId is like so: "clientId:(guid)". And the second time we will call it would resemble a normal itemId: "AAMkAGFjZjI3MTFiLThiZDctNGMyZS05YjI3LWFjOGNmYjcxZWQzOABGAAAAAABRMWgXD0utQLNDsO/0Fe5IBwCcsJP4/6D0Q6oczvczNWVUAAAAAAEPAACcsJP4/6D0Q6odzvczNWVUAAJMlQ00AAA="
So in my case I always have to get/save the itemId 2 times before I get the actual value.

For the getSharedPropertiesAsync, when called with a callback, the callback never gets called. When debugging I found that the api call might be the issue, here is the error message that I found in the console: "Access to XMLHttpRequest at 'https://outlook.office365.com/autodiscover/autodiscover.json/v1.0/shared@secureexchanges.onmicrosoft.com?Protocol=REST' from origin 'https://outlook.office.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

## Steps to reproduce

1. Simply do an office add-in that supports sharedFolders in the xml
2. Then try to get the item id of a compose message by saving it
3. Add a shared mailbox and try to getSharedPropertiesAsync with a callback only

## Useful logs

- Screenshots
![image](https://github.com/user-attachments/assets/a7d40170-48f1-4bb7-96c3-f5e1a56d752f)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by sivachandran-msft** [comment]
Hi @SE-Hubert , thanks for sharing your query. 

This is a known issue with clientID and our team is actively work on the fix. The fix will be available in sometime. We will update the post once it is in PROD.

**Comment by SE-Hubert** [comment]
Great to know thanks!

**Comment by manaunl** [comment]
Our customers are experiencing similar issues. It would be greatly appreciated if this fix could be prioritized. Thank you in advance for your attention to this matter.

**Comment by sivachandran-msft** [comment]
@manaunl  Fix is already in action and will share the update once it reached complete PROD.

**Comment by manaunl** [comment]
Hi @sivachandran-msft,

Could you please provide an estimated timeline for when the fix will be fully rolled out to production? Additionally, is there any workaround that we can implement in the meantime to mitigate the impact on our customers?

Thank you!

**Comment by sivachandran-msft** [comment]
Hi @manaunl , there are 2 observations reported in this issue. 

1. The clientID retrieved is having different value before & after saving - The team has already fixed this and it will be available in few weeks.
2. The second observations related to CORS, the team is analysing this and currently we cannot share the expected timeline for this.

**Comment by manaunl** [comment]
Hi @sivachandran-msft 

Thank you for quick response. Our primary concern is the CORS-related issue, as it's impacting our customers. We understand that the team is still analyzing it, but if there are any temporary workarounds or steps we can take in the meantime, that would be extremely helpful.

**Comment by andymozza** [comment]
Also critical customer issue here for us. This was working and taken down by a recent change it seems.
This should have priority please to restore what was working.

**Comment by geoffreyreemer** [comment]
Adding another vote to the mix. Unfortunately, the issue hinders our customers who use shared mailboxes from interacting with secure emails in their mailboxes, which greatly impacts their productivity. If a recent change caused this, would you consider reverting that change? @sivachandran-msft ?

**Comment by DustinBrungart** [comment]
This is a critical issue to our customer base who are experiencing a significant loss of functionality and would like to remain updated on its timely resolution.

**Comment by anjalitp** [comment]
Our team is actively working on fixing the CORS related issue and we will update this thread once fix is available.

**Comment by SwatidPathak** [comment]
[Office outlook ItemId and get getSharedPropertiesAsync bug](https://github.com/OfficeDev/office-js/issues/4781#top)
#4781
Following up on this issue. Is the fix in Prod yet? Our processes are impacted heavily due to this.

**Comment by rajjha-msft** [comment]
The issue has been fixed and deployed. Please let us know if you still see the issue.

**Comment by sumitjain-rsi** [comment]
in our case on browser, cors and unauthorized error is now not coming. but method is still not executing. Office.context.mailbox.item.getSharedPropertiesAsync({}, function (result2) {});
![image](https://github.com/user-attachments/assets/ceac464f-582c-4de5-bb87-2be10c63fe9b)

**Comment by DC-de-Villiers** [comment]
The cors issue seems to be resolved, but the callback is still not being executed.

**Comment by DanielSchwabeDocuware** [comment]
same for us. Callback is not executing

**Comment by SE-Hubert** [comment]
Same here

**Comment by andymozza** [comment]
Hi, this is not fixed. Callback is still not working.

**Comment by geoffreyreemer** [comment]
Not fixed for us either, unfortunately. Critical issue still remains.

**Comment by ChibaniMohamed** [comment]
Not Fixed

**Comment by mobisw-msft** [comment]
Hey everyone,

We are working on this issue and we will keep this thread posted.

**Comment by geoffreyreemer** [comment]
@mobisw-msft Hey. Thanks for the update and your continuous efforts. Just wanted to mention that perhaps it's good to remove the **Status: fixed** label for this issue, since the deployed release didn't actually fix the issue.

Any timelines we can communicate to our customers about this?

Thank you. 👍

**Comment by wklikli** [comment]
@mobisw-msft We could all do with an update on this issue. It is painful for our customer base(s) and apart from providing a failed fix, very limited progress has been made. Thanks in advance for providing more clarity.

**Comment by wklikli** [comment]
@exextoc perhaps some update from your end?

**Comment by wklikli** [comment]
@mobisw-msft @exextoc Please provide an update.

**Comment by wklikli** [comment]
> Hey everyone,
> 
> We are working on this issue and we will keep this thread posted.

It would be awesome if you could indeed "keep this thread posted".

**Comment by geoffreyreemer** [comment]
@exextoc Hey. Just wanted to second the request for a prognosis on this one. As mentioned previously, quite a few customers of ours are affected, which hinders their ability to perform their workflows. It's important for us to understand whether a fix is expected in the short term. If the answer is that it's not possible to fix this in the short term, we have to determine next steps to minimize the impact on our customers.

Thank you and good luck!

**Comment by AlonEkelund** [comment]
Any update? Any recommendations on what we can do? this is **highly** critical for us and our customers. Please advice

**Comment by exextoc** [comment]
Fix for this is rolled out, it can be tested by. 
Office.context.mailbox.item.getSharedPropertiesAsync(function(result) {
            console.log(JSON.stringify(result));
          });

**Comment by geoffreyreemer** [comment]
@exextoc Thank you so much! I've done some preliminary testing and it seems to work well now. Appreciate you getting back to us in your weekend. 👍

**Comment by sumitjain-rsi** [comment]
for us it still not working on browser and starts giving cors error 
![image](https://github.com/user-attachments/assets/1a032bcf-4358-4d50-beee-694646426cc3)

**Comment by AlonEkelund** [comment]
We are still getting reports from customers that they still have the problem. In our own production in the New Outlook Client, it works. However, customers using web mail **still have the problem**.

**Comment by andymozza** [comment]
Do you need to add cors policy on the azure app services?Sent from my iPhoneOn 16 Sep 2024, at 03:42, Sumit Jain ***@***.***> wrote:﻿
for us it still not working and starts giving cors error
image.png (view on web)

**Comment by AlonEkelund** [comment]
We contacted the customers that still had the problem in web mail. After deleting the browser cache all is working. We are still doing some testing. But it seems to be working again. :-) 

Thank you very much guys.

**Comment by sumitjain-rsi** [comment]
> for us it still not working on browser and starts giving cors error ![image](https://private-user-images.githubusercontent.com/46016738/367640382-1a032bcf-4358-4d50-beee-694646426cc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NTU2MDAsIm5iZiI6MTcyNjQ1NTMwMCwicGF0aCI6Ii80NjAxNjczOC8zNjc2NDAzODItMWEwMzJiY2YtNDM1OC00ZDUwLWJlZWUtNjk0NjQ2NDI2Y2MzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDAyNTUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMzUyMWM0NjAzNDNiMjAwMDRmMjI4OTYwNjNkMDBiYzVmMzY0MTlhNDgxMTJjNWMzNmY4ZWI2MmNmYmE0ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.opYDv8_vJjb1IGCeqacUoHYM1wRFDYCsThk2u9BUvjg)

it seems to be working after clearing cache.

**Comment by alex-fitzgerald** [comment]
Great work @exextoc et al!

**Comment by wklikli** [comment]
Many thanks indeed. Going forward though, it would be massively appreciated if the comms can be more open. We have to manage customer and roadmap impact, which is extremely difficult to do if there is no information. Thanks!
