### ISSUE TITLE
Excel Online only : code execution is stuck on `context.sync()`

### ISSUE THREAD

**Issue by SharonCKC** [OfficeDev/office-js#4805]
# Provide required information needed to triage your issue
When executing code for the `worksheets.onChanged` event handler, code execution is stuck on `context.sync()` and doesn't continue.  This can only be observed in Excel on the web; no issue was found in Excel PC and Excel Mac. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Browser (if using Office on the web): Edge, Chrome
 
## Expected behavior
Code should continue to execute after `context.sync()` is run.

## Current behavior

Code execution is stuck on `context.sync()`.

## Steps to reproduce

1. Paste the code snippet below in ScriptLab
2. Click the button to run the onChanged event listener.
3. Open the console
4. Insert/delete a random row/column. We expect "try" to be printed in the console, then after `context.sync()` is run, "done" should be printed in the console. 
```
console.log("try");
await context.sync();
console.log("done");
```
5. Observe that "try" is printed on the console, but "done" is not printed.

# Provide additional details
Code snippet below:
```
name: Basic API call (TypeScript)
description: Performs a basic Excel API call using TypeScript.
host: EXCEL
api_set: {}
script:
  content: |
    $("#run").on("click", () => tryCatch(run));

    async function run() {
      await Excel.run(async (context) => {
        context.workbook.worksheets.onChanged.add(async () => {
          await test();
        });
      });
    }

    async function test() {
      await Excel.run(async (context) => {
        console.log("try");
        await context.sync();
        console.log("done");
      });
    }

    /** Default helper for invoking an action and handling errors. */
    async function tryCatch(callback) {
      try {
        await callback();
      } catch (error) {
        // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
        console.error(error);
      }
    }
  language: typescript
template:
  content: "<section class=\"ms-font-m\">\n\t<p class=\"ms-font-m\">This sample demonstrates basic Excel API calls.</p>\n</section>\n\n<section class=\"samples ms-font-m\">\n\t<h3>Try it out</h3>\n\t<p class=\"ms-font-m\">Click to start listening to worksheet onChanged event</b>.</p>\n\t<button id=\"run\" class=\"ms-Button\">\n        <span class=\"ms-Button-label\">Run event listener</span>\n    </button>\n</section>"
  language: html
style:
  content: |-
    section.samples {
        margin-top: 20px;
    }

    section.samples .ms-Button, section.setup .ms-Button {
        display: block;
        margin-bottom: 5px;
        margin-left: 20px;
        min-width: 80px;
    }
  language: css
libraries: |
  https://appsforoffice.microsoft.com/lib/1/hosted/office.js
  @types/office-js

  office-ui-fabric-js@1.4.0/dist/css/fabric.min.css
  office-ui-fabric-js@1.4.0/dist/css/fabric.components.min.css

  core-js@2.4.1/client/core.min.js
  @types/core-js

  jquery@3.1.1
  @types/jquery@3.3.1

```

**Comment by shanshanzheng-dev** [comment]
Hi @SharonCKC Thanks for reaching us. But I can repro your issue on Excel online. You can see this video:

https://github.com/user-attachments/assets/c6532637-6284-4ed3-93ee-3fa8f20a8654

Do you have a big dataset in your workbook? Or could you share your test workbook to help us repro this issue? Thanks.

**Comment by SharonCKC** [comment]
Hello @shanshanzheng-dev, thank you for investigating. No I don't have a big dataset in the workbook.  Here's another [fresh workbook](https://m4o365-my.sharepoint.com/:x:/g/personal/sharepointtest_m4o365_onmicrosoft_com/ETvUkf2dnW5FiSuj0sAXUv0BCLKIY1Joa7DnswYR7GINSg?rtime=vn5Vmd_B3Eg) that I shared, and here's a screenshot of the issue:



https://github.com/user-attachments/assets/b90a2bcb-e219-4c67-a318-951ca985908e

**Comment by shanshanzheng-dev** [comment]
Hi @SharonCKC Thanks for providing this doc link and video, I can repro this issue. We'll take a look and report back if we have a suggestion for you. Thanks.

**Comment by SharonCKC** [comment]
Hello @shanshanzheng-dev, I still see the bug (only in Excel on the browser) which is causing our add-in not to be able to detect a new column. Just wanted to follow up if there's anything that can be done at this time?

**Comment by SiruiSun-MSFT** [comment]
Hi @SharonCKC, Thanks for your patience! However, this issue seems more complex than we expected. We are still under investigation and fix. please stay tuned. Will update here when we have any progress. Thanks again!

**Comment by SiruiSun-MSFT** [comment]
Hi @SharonCKC, As I mentioned before, this issue is under the deeply investigation and fix. However, these days, we find a workaround for this case, which may somehow help you out first. Could you add a Delaying by setTimeout using await?
Here is the sample code:

_async function test() {
  await Excel.run(async (context) => {
    console.log("try");
    **await new Promise((resolve) => setTimeout(resolve, 100));**
    await context.sync();
    console.log("done");
  });
}_

We've done the first test on our machine, and this seems to be a workaround. If you are struggling on this issue, please try the above method. Hope this will work well! Thanks for your patience again!

**Comment by SharonCKC** [comment]
@SiruiSun-MSFT We added this workaround but it doesn't seem to work all the time. We can still observe this bug.

**Comment by didu9898** [comment]
This issue still occurs intermittently in Excel Online, and the [provided fix](https://github.com/OfficeDev/office-js/issues/4805#issuecomment-2490180659) doesn't seem to work all the time.
CC: @4tti @Wenjun-Gong

**Comment by SiruiSun-MSFT** [comment]
Hi @didu9898, our colleague have finished the fix at the end of April and the fix should have rolled to Excel Online Prod at the middle of May. And based my investigation just now, the issue seems not happen on our side currently. Here is my validation gif (on version 16.0.18928.42304):

![Image](https://github.com/user-attachments/assets/2d08e726-1165-4efd-a221-ddf617ea6697)

![Image](https://github.com/user-attachments/assets/23257075-2ab3-442d-a85b-743a0243e2c9)

Since you mentioned this issue still occurs, we're not sure whether there have another issues in the same scenario, could you provide more information about the frequency and the repro steps, version to us? Thanks!

**Comment by 4tti** [comment]
hello @SiruiSun-MSFT, in our case this is found by E2E tests when call of context.sync() (with side-loaded add-in) will cause 'excel online' to show 'saving' forever and the api seems to be stuck.

**Comment by didu9898** [comment]
Adding to @4tti’s comment about the E2E tests, we have over 300 tests for Excel Online. When we run them all at once, Excel throws an "An internal error has occurred" message. We suspected it was due to too many calls, so we decided to split the tests into smaller batches. After each batch, we reload the page, reopen the taskpane, and run the next batch.

However, after a few batches, when the page is reloaded and the taskpane is reopened, `context.sync()` gets stuck, and the page stays in a "Saving..." state indefinitely. Here's the screenshot:


![Image](https://github.com/user-attachments/assets/5425c0c4-7146-430c-a05d-03286a301d15)

**Comment by SiruiSun-MSFT** [comment]
Hi @4tti and @didu9898, Thanks for your reply here! From the screenshots you provided, there are indeed some problems. However, from your description, we could only know that this happened in your test, and there is no other information to speed up the investigation. Perhaps you guys could provide a more precise and straight-forward repro steps?

Also, if this case is not the same problem as the one discussed before, and the problem reported before has been fixed, could you please raise a new GitHub issue? This will make it easier for us to track different problems. 

Thank you!

**Comment by 4tti** [comment]
@SharonCKC can you confirm that it is fixed on your end?
@SiruiSun-MSFT we'll try to figure out the repro steps and possibly will open new ticket.

**Comment by SharonCKC** [comment]
Our team could not reproduce the issue recently, but since the bug was not consistent it is possible that it is still there.

**Comment by SiruiSun-MSFT** [comment]
@4tti and @SharonCKC , Thanks for your replies here! Considering the issue reported before has been fixed, I'll close this ticket as Fixed. And for the other issue you mentioned, if it still occurs, please feel free to open a new ticket! Thanks!

**Comment by Alex-adva** [comment]
We're experiencing the same issue reported by one of our customers. It looks like this issue is not fully fixed.

We have a feature called "Edit Online", which opens the selected file in Excel Online via SharePoint and launches our add-in.
After the add-in starts loading (we show a loader while initializing everything we need), it hangs indefinitely — the add-in keeps showing the loading state forever.

Investigation details:

1.For me, this issue reproduces rarely, not every time. For customer it reproduces every time.

2.The issue occurs only with large files (e.g. 8 reports, ~25 columns × 1000 rows, with many custom functions and several tables). The customer confirmed that small files work fine without any problems.

3.I added logs and found that the problem happens on the very first context.sync() call. All Excel operations we do before that - just taking a sheet with:
`const sheet = context.workbook.worksheets.getItemOrNullObject(sheetName);`
When calling context.sync() after it, everything hangs and never proceeds.

4. When I managed to reproduce the issue, I opened the browser console and ran another Excel.run:

```
await Excel.run(async (c) => {
  console.log(1);
  await c.sync();
  console.log(2);
});
```

The output was only "1", even after waiting for more than 10 minutes after the add-in was stuck.

sample from our code -     


```
Excel.run(async function (context) {
      _this.onSelectionChangeEventHandler = context.workbook.onSelectionChanged.add(_this.onSelectionChanged);
      _this.onCalculatedEventHandler = context.workbook.worksheets.onCalculated.add(_this.onCalculated);
      _this.onCopiedWorksheetEventHandler = context.workbook.worksheets.onAdded.add(_this.onCopiedWorksheet);
      await _this.initData(context);
      return context.sync();
});
```

Few layers below in initData, we do
```
      const sheet = context.workbook.worksheets.getItemOrNullObject(sheetName);

      await context.sync();
```

This is the 1st context.sync we do, and everything hangs after that.

@shanshanzheng-dev  @SiruiSun-MSFT

**Comment by RuizhiSunMS** [comment]
Hi @Alex-adva , thx for reporting issue. We suggest you create your own issue for tracking it better.
