### ISSUE TITLE
insertFileFromBase64 loads the content in different result and reformat the merge blocks

### ISSUE THREAD

**Issue by andregloeckner** [OfficeDev/office-js#4901]
We create a lot of complexe document processing templates and have created a word addin which loads the files directly from our web application. It works well more or less...

But in some complexe edge cases we found problems by modified placeholders durring loading.

See: 
Correct version, can you achive by use Word->Document->Open with the file, or you use the follow code snipped.
```
OfficeExtension.config.extendedErrorLogging = true;
await Word.run(async (context) => {
    context.application.createDocument(response.content).open();
    await context.sync();
}).catch(function (error) {
    messageContext.add({
        intent: "error",
        title: CodeStrings.Messages.ErrorTitle,
        text: 'Error: ' + JSON.stringify(error)
    });
});
```
![image](https://github.com/user-attachments/assets/3c1ea464-66ba-43b3-9e42-0feda98a8f49)

The problem happens when you try to load the byte array content directly in the Current word session:

```
await Word.run(async (context) => {
    context.document.insertFileFromBase64(response.data.content, Word.InsertLocation.replace, {
        importTheme: true,
        importStyles: true,
        importCustomProperties: true,
        importCustomXmlParts: true,
        importParagraphSpacing: true,
        importPageColor: true,
        importChangeTrackingMode: true,
        importDifferentOddEvenPages: true,
    });
    await context.sync();
}).catch(function (error) {
    console.log('Error: ' + JSON.stringify(error));
    if (error instanceof OfficeExtension.Error) {
        console.log('Debug info: ' + JSON.stringify(error.debugInfo));
    }
});
```
![image](https://github.com/user-attachments/assets/276e2899-b27f-4ce8-a3d5-058fab3075f1)

In the wrong case, you can see that the merge block is moved to a different position.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desctop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Microsoft® Word für Microsoft 365 MSO (Version 2402 Build 16.0.17328.20550) 64 Bit 
* Operating System: Windows 11
* Browser (if using Office on the web): ______
 
## Expected behavior

We want to use the loading of a byte array in the same word window, the only methode I found is using the 

## Steps to reproduce

When open a docx file as byte[] to new Word with that code block, the format is fine.
```
await Word.run(async (context) => {
    context.application.createDocument(response.data.content).open(); 
    await context.sync();
}).catch(function (error) {
    console.log('Error: ' + JSON.stringify(error));
    if (error instanceof OfficeExtension.Error) {
        console.log('Debug info: ' + JSON.stringify(error.debugInfo));
    }
});
```

When open a docx file as byte[] to current Word instance with that code block, it looks wrong.
```
await Word.run(async (context) => {
    context.document.insertFileFromBase64(response.data.content, Word.InsertLocation.replace, {
        importTheme: true,
        importStyles: true,
        importCustomProperties: true,
        importCustomXmlParts: true,
        importParagraphSpacing: true,
        importPageColor: true,
        importChangeTrackingMode: true,
        importDifferentOddEvenPages: true,
    });
    await context.sync();
}).catch(function (error) {
    console.log('Error: ' + JSON.stringify(error));
    if (error instanceof OfficeExtension.Error) {
        console.log('Debug info: ' + JSON.stringify(error.debugInfo));
    }
});
```

## Link to example(s)
Sample file well formated
[Extract.docx](https://github.com/user-attachments/files/17018597/Extract.docx)

Sample file after open with insertFileFromBase64()
[Extract - broken.docx](https://github.com/user-attachments/files/17018758/Extract.-.broken.docx)

**Comment by Piyush-IT** [comment]
Facing same issue

**Comment by shanshanzheng-dev** [comment]
Hi @andregloeckner @Piyush-IT Thanks for reporting this issue. Seem I can repro, we'll take a look and report back if we have a suggestion for you.

**Comment by andregloeckner** [comment]
Hi @shanshanzheng-dev, 

do you already have an idea how to fix that?
We cannot proced with the plugin idea we have, because with open we loose the context of which file it is.
The context contain informations like, DocumentName, DocumentId, TemplateEntity, CurrentRevision and so on. Serializable to JSON.

So we have just the possiblity to open in current Word with staying in the document context we have.
Or 
Call open with send an embedded json with the byte array to the new Word.

Best regards

**Comment by Searion** [comment]
@andregloeckner Thanks for reporting this. We have put on our backlog<Bug#9350173> for internal track. We found it happens for all insertfilefrombase64 apis and are still working on it. We will let you know if there are any updates.

Also, since this example is quite complex, I want to make sure we haven't missed anything. One content control should have included two rows but wrongly included all the table after inserting. Have you encountered similar problems with contentcontrols other than tables?

**Comment by andregloeckner** [comment]
@Searion 
I asked my collegues about your questions and it looks like that all similar problems we encountered were related to the tables.
Greetings

**Comment by aarzoomittal-microsoft** [comment]
Hi @andregloeckner , we are reviewing older Office.js issues to work out which scenarios still affect people on current Office builds.

This one has been open since it was filed and we have not given you a resolution in that time. That is on us.

Is this still affecting you? If it is, the most useful things are your current host and platform, your Office build number, and whether you have had to work around it.

If we do not hear back within 7 days we will close this as inactive. That would not mean the report was invalid or that the behaviour is fixed - only that we do not have current confirmation it is still affecting anyone. Reply any time after that and we can reopen it.

**Comment by andregloeckner** [comment]
Hi, we used the workaround of opening a new Word instance to go live.
I’ll recheck the issue.

**Comment by andregloeckner** [comment]
Hi @aarzoomittal-microsoft,

I retested the issue and can confirm that it still occurs.

Environment:
- Platform: Mac desktop
- Host: Word
- Version: Microsoft Word for Mac Version 16.112.3 (26083020)

I saved both loaded variants again and attached the resulting documents and screenshots:
[Loading via insert.docx](https://github.com/user-attachments/files/32156929/Loading.via.insert.docx) — loaded with `insertFileFromBase64(..., Word.InsertLocation.replace, ...)`

<img width="1597" height="747" alt="Image" src="https://github.com/user-attachments/assets/2dbcfbf4-f5e9-4d6a-8fa7-18ba237b4951" />

[Loading via new instance.docx](https://github.com/user-attachments/files/32156928/Loading.via.new.instance.docx) — loaded with `context.application.createDocument(content).open()`

<img width="1812" height="765" alt="Image" src="https://github.com/user-attachments/assets/7ddffb42-9828-4c1b-8ad8-67053d48e451" />

The `insertFileFromBase64` variant still corrupts the layout of table-related content controls, while loading the same source document in a new Word instance preserves the formatting.

Please keep the issue open.

**Comment by kustonaut** [comment]
@andregloeckner Thank you for letting us know. We are actively tracking this and prioritizing a bugfix. 
Internal tracking id: 9350173

cc: @aarzoomittal-microsoft
