### ISSUE TITLE
[Word] range.insertField in ContentControl fails unless range.select() is called before it

### ISSUE THREAD

**Issue by fangd1997** [OfficeDev/office-js#5628]
### Description  
In Word JavaScript API, when I try to insert a field using `range.insertField()` on a content control's range, it throws an error unless I call `range.select()` beforehand. This behavior is unexpected and seems like a bug or an undocumented requirement.

### Your Environment
Operating System : Windows
Host: Word Version 2503 (Build 18623.20178 Click-to-Run)

### Code to reproduce
```javascript
Word.run(async context => {
  const selection = context.document.getSelection();
  const cc = selection.insertContentControl();
  await context.sync();
  
  const range = cc.getRange('End');
  
  // Any form of select seems to prevent the error
  // For example: cc.select(); or context.document.body.select();
  range.select();  // Without this line, insertField throws an error

  range.insertField(Word.InsertLocation.replace, Word.FieldType.ref);
  await context.sync();
});

**Comment by penglongzhaochina** [comment]
Thanks for reporting this issue.  

It has been put on our backlog<Bug#10027890> for internal track. We will keep track of this issue and let you know if there are any updates.

**Comment by vishmittal** [comment]
Hi @fangd1997 , we are reviewing older Office.js issues to work out which scenarios still affect people on current Office builds.

This one has been open since it was filed and we have not given you a resolution in that time. That is on us.

Is this still affecting you? If it is, the most useful things are your current host and platform, your Office build number, and whether you have had to work around it.

If we do not hear back within 7 days we will close this as inactive. That would not mean the report was invalid or that the behaviour is fixed - only that we do not have current confirmation it is still affecting anyone. Reply any time after that and we can reopen it.

**Comment by fangd1997** [comment]
> Hi [fangd1997](https://github.com/fangd1997) , we are reviewing older Office.js issues to work out which scenarios still affect people on current Office builds.
> 
> This one has been open since it was filed and we have not given you a resolution in that time. That is on us.
> 
> Is this still affecting you? If it is, the most useful things are your current host and platform, your Office build number, and whether you have had to work around it.
> 
> If we do not hear back within 7 days we will close this as inactive. That would not mean the report was invalid or that the behaviour is fixed - only that we do not have current confirmation it is still affecting anyone. Reply any time after that and we can reopen it.

Hi @vishmittal , yes, this issue is still affecting me. I can still reproduce it on Version 2608 (Build 20326.20112 Click-to-Run).

Thanks for checking in.
