### ISSUE TITLE
Custom Functions Successfully Registered but Display as _xldudf with #NAME Errors - Critical

### ISSUE THREAD

**Issue by ar090** [OfficeDev/office-js#5865]
# Custom Functions Successfully Registered but Display as _xldudf with #NAME Errors - Critical Production Impact Causing Customer Loss

## Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop & Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel  
* Office version number: Most recently seen on: `16.0.17928.20588` but Multiple versions (affects both Windows and Mac across various Office versions)
* Operating System: Windows & macOS
* Browser (if using Office on the web): N/A

## Expected behavior

Custom functions should register automatically when the add-in is loaded with resiliency and always appear for the user if the addin is installed. Functions should be callable by their registered names (e.g., `=LX.ENTITY.GET()`) and execute properly (not return #NAME) requiring manual intervention from users

**Alternative acceptable solutions** (in order of preference):
1. **Automatic registration with resiliency**: Functions register reliably on add-in load without manual intervention
2. **Reliable programmatic re-registration**: A dependable API method to force registration/re-registration that doesn't break functionality
3. **Programmatic cache clearing**: A way to programmatically clear add-in cache to resolve the issue without impacting UX

## Current behavior

Custom functions are successfully registered (confirmed via CustomFunctionManager debugging - see images), but Excel fails to recognize them. Functions display as `_xldudf_<FunctionName>` with `#NAME` errors. The debugging shows that as far as the CustomFunctionManager is concerned, the functions **are** in fact registered, so the issue must be some kind of corruption on bindings between the JS runtime and Excel custom functions engine.

**Debugging**
- No error messages when Excel boots saying the add-in failed to register functions - the failure seems silent
- CustomFunctionManager shows all functions properly registered with correct parameters and function strings
- Functions appear as `_xldudf_<FunctionName>` to users with `#NAME` errors
- Issue persists until clever users remove directories mentioned or our support staff walks them through addin reinstalls

![Image](https://github.com/user-attachments/assets/678ba775-eb7a-4bc3-8ac7-602ce1d14fe6)
Excel showing _xldudf and #NAME error
![Image](https://github.com/user-attachments/assets/cb1ef75f-c19b-448c-b6a5-84e4cf67a796)

CustomFunctionManager showing successful registration with full debugging output

## Steps to reproduce

1. Deploy custom functions add-in to production environment (all our functions are doing API calls)
2. Functions work initially after installation
3. Issue manifests seemingly randomly, with certain patterns observed:
   - **Higher frequency**: After making changes to functions.json
   - **Specific scenario**: API call promise is not rejected properly → calculating cells get stuck in busy state → user closes Excel while calculation is in progress → functions disappear on next launch
   - **General usage**: Occurs over time across different usage patterns
4. Functions display as `_xldudf_<FunctionName>` with `#NAME` errors despite successful registration
5. Only fix is complete cache clearing (see workarounds below)

## Link to live example(s)

1. Cannot reliably reproduce in development environment
2. Issue occurs randomly in production across multiple customer environments  
3. Likely directly related to issue #4487: https://github.com/OfficeDev/office-js/issues/4487

### 1. Cache and Registration Fixes Attempted (Failed to Resolve Issue):
- **Force refresh cache**: Implemented `Office.ForceRefreshCustomFunctionsCache()` when sidebar opens - followed official troubleshooting guide at https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-troubleshooting to mark functions needing to be refreshed. Successfully sets but does nothing to resolve the issue described above.
- **Manual re-registration button**: Created button for users to force registration, only to realize they have always been registered according to CustomFunctionManager

### 2. User Experience Solutions Attempted:
- **Custom .exe tool**: Built executable for users to click which deletes problematic directories dependent on installation path. Trying to ease the pain of manual fixes

### 3. Consideration of Drastic Measures:
- **Complete rewrite consideration**: Have even debated rewriting our entire plugin as COM but will miss a lot of the UI functionality we have built. Weighing the cost of losing current web-based UI against reliability of COM approach

## Only Reliable Fix (Extremely Disruptive to Users)

1. Uninstall Addin
2. Close Excel
3. Restart Excel
4. Install Addin

OR

**Windows**: 
```
rmdir /s /q "C:\Users\[USERNAME]\AppData\Local\Microsoft\Office\16.0\Wef"
```
+ Restart Excel

**Mac**: 
```bash
rm -rf ~/Library/Containers/com.microsoft.Excel/Data/*
# OR  
rm -rf ~/Library/Containers/com.Microsoft.OsfWebHost/Data/
```
+ Restart Excel

**Note**: For Mac, I swear deleting just Wef didn't even work - I find myself needing to do the top-level directory approach (which contains Wef).

## Context - Critical Business Impact

**Customer Impact**: Extremely frustrated customers experiencing add-in that appears completely broken. Complex manual fixes destroy user experience and confidence. Large workbooks littered with #NAME errors.

**Business Impact**: Losing customer revenue due to reliability issues. Support volume surges after functions.json (Even just new function appends). Development resources diverted to workarounds instead of features.

**Timeline**: Over a year duration across multiple Office versions on Windows and Mac. Frequency increases when adding additional functions. I have seen numerous reports of this issue over the years as well.

### CustomFunctionManager Output (from debugging session):
```
All registered custom functions:
ENTITY.GET:
- Function: ƒ (e,t,n,r){return p(this,void 0,void 0,(function(){var o,a,i,u;return h(this,(function(l){try{if("string"==typeof n&&(o=n.trim())&&!/^(\d{4}-\d{2}-\d{2}|\d{1,2}\/\d{1,2}\/\d{2,4}|\d+)$/.test(o)){if(a=…
- Parameters: 4

[Additional functions registered but showing ENTITY.GET as example]
```

#### Key Technical Observations:
I hope these observations can help provide new insight into the issue
- Functions remain registered in CustomFunctionManager throughout the failure
- No registration errors or warnings in console
- Issue appears to be corruption whatever binds JS runtime and Excel's custom function engine
- Silent failure - Excel provides no indication of the problem from user perspective. No Addin failed to load warning or anything.

## Useful logs

- [x] Console errors: CustomFunctionManager shows successful registration (full debugging output in images)
- [x] Screenshots: Provided showing _xldudf prefix and #NAME errors vs successful registration  
- [x] Debugging session: Was able to debug on a call with a friendly user and noticed the detailed information provided above
- [ ] Test file: Affects multiple files/workbooks across different customer environments

## Relationship to Existing Issues
This issue provides extensive additional debugging information and business impact details for:
- **Primary issue**: #4487 (https://github.com/OfficeDev/office-js/issues/4487)
- **Original acknowledgment**: Issue #4007 (acknowledged by @zhenhuangMSFT requesting separate issue)

**Current state**: Issue #4487 was created in May 2024 following Microsoft team acknowledgment, but no timeline or official resolution has been provided despite the severe production impact.

Is there anyway we can escalate this issue or get commitments that we can provide to our customers? I am happy to discuss in more detail. 

Thank you in advance!

**Comment by RuizhiSunMS** [comment]
Hi @ar090 , thx for reporting here.
I have some questions here, would you please share some information:
1. how does other code snippets work in your dev env, will them reproduce this error too? Or say that no matter what functionalities your CFs have, changing functions.json would reproduce problem with high possibility
2. using ScriptLab to test your CFs will never reproduce this problem?
3. your CFs worked well previously but turned to encounter problem recently? If yes, do you remember when it happened firstly?
4. are our bot's comments about regressions helpful for you in this case?

**Comment by ar090** [comment]
Hi @RuizhiSunMS thanks for taking a look!

1) We are so conditioned to clear cache / rebuild functions during develop sideloads i am not sure.
2) testing with scriptlab I've only ever done locally and i dont think I have ever encountered this problem locally outside of the one specific case highlighted above:
  > Specific scenario: API call promise is not rejected properly → calculating cells get stuck in busy state → user closes Excel while calculation is in progress → functions disappear on next launch. Albeit programming errors here but still wouldnt expect this to corrupt the addin CFs.
3) We have had this problem since launching the plugin over a year ago. We've been able to draw more insights recently because we have a lot more users dependent on the system. Thats when we have started to see patterns emerge - for example we deployed changes which appended some new CFs to our plugin, and saw a dramatic uptick in support tickets with this issue. All resolved by reinstalling or deleting appropriate Wef/Data files.
4) Unfortunately none of the above are helpful as I dont believe this to be a regression (we've had this intermittent problem since launch). I cant confirm the expect behavior I outlined above has ever been the case with office.js.

**Comment by RuizhiSunMS** [comment]
> Hi [@RuizhiSunMS](https://github.com/RuizhiSunMS) thanks for taking a look!
> 
> 1. We are so conditioned to clear cache / rebuild functions during develop sideloads i am not sure.
> 2. testing with scriptlab I've only ever done locally and i dont think I have ever encountered this problem locally outside of the one specific case highlighted above:
> 
> > Specific scenario: API call promise is not rejected properly → calculating cells get stuck in busy state → user closes Excel while calculation is in progress → functions disappear on next launch. Albeit programming errors here but still wouldnt expect this to corrupt the addin CFs.
> 
> 3. We have had this problem since launching the plugin over a year ago. We've been able to draw more insights recently because we have a lot more users dependent on the system. Thats when we have started to see patterns emerge - for example we deployed changes which appended some new CFs to our plugin, and saw a dramatic uptick in support tickets with this issue. All resolved by reinstalling or deleting appropriate Wef/Data files.
> 4. Unfortunately none of the above are helpful as I dont believe this to be a regression (we've had this intermittent problem since launch). I cant confirm the expect behavior I outlined above has ever been the case with office.js.

Ok, thx for the sharing. I've reached out to the colleague owning this part. Will update here if having any new.

**Comment by b-gonzalez** [comment]
I just wanted to add that I've been seeing similar issues. My workarounds have been a combination of manually clearing the add-in cache, disabling/re-enabling office add-ins, and refreshing the add-in from the app store.

I've typically noticed that this happens after I push updates to my add-in. It can take some time to resolve. Sometimes the functions are not visible. Other times they'll be registered as expected but won't return the expected content. Other times they'll be flagged with `_xldudf` and so on.

Sometimes my add-in will prompt me that there is an error. But clicking the error notification doesn't give me any additional information. When I open the app store from here, the app store does not show my add-in as being registered with my account.

When I push updates, one thing I should note that I typically do **not** do is update the manifest version. I'm not clear on exactly when this needs to be updated when updates are pushed. But I've tried updating it before/after I push updates as well and it doesn't fix the situation.

It's possible that this issue is partially related to me trying to push several updates in a short time frame.

As a final note, it looks like my taskpane add-in, and the add-in in the app store do not necessarily reflect the same version number. And it appears that there's some delay before the correct version gets updated.

**Comment by ar090** [comment]
@RuizhiSunMS Adding some more investigation notes here: 
We did have someone come across this issue recently on a fresh installation - this is the first I had noticed that. Suggested some kind of a race condition which is why I wanted to dig deeper. Effectively the user installed our plugin, got the ribbon and the task pane, but no custom functions showed up. Deleted Wef directory, restarted excel and custom functions appeared.

I scanned the Wef directories on working installations vs not working installations. I didn't see anything in common with not working ones. Cache patterns are different but no idea how these are being used under the hood by office.js
I checked to see if we had any failed requests to any excel paths like functions.js or functions.json that we host - 0 non 200 or 304 response in the last month.

**Comment by RuizhiSunMS** [comment]
Thx @ar090 , I will paste your new sharing to my colleauges.

**Comment by b-gonzalez** [comment]
Hello. I think I made some progress on this issue this weekend.

I installed my add-in on a new account. When I tried accessing the functions they were not available. I tried disabling and re-enabling the add-in several times but it didn't appear to be working. That's when I remembered to activate the add-in from the add-in store. Once I did this the functions became available. Initially I was going to the add-in in the app store, clicking manage add-ins, and then opening the add-in. But this does not appear to be necessary. If the add-in is visible in the app store, you can just select the add-in. And then the functions will appear.

I was able to record the scenario on a video. You can see it at the link below (for some reason GitHub isn't letting me attach the mp4 file.):

https://www.youtube.com/watch?v=6CF8yRUx4jQ

If there's an issue accessing YouTube let me know and I can try to provide the video in some other way.

**Comment by MiaofeiWang** [comment]
@b-gonzalez Thanks for sharing—yes, that’s exactly the same mitigation we’re planning to communicate.

@ar090 As Brian mentioned, a simpler workaround is to click the add-in icon from the dropdown menu under the “Add-ins” button. This triggers a full installation of the custom functions and should resolve most #NAME errors.

For add-ins deployed by admins, we’ve identified the root cause and are actively working on a permanent fix. We’ll share updates as we make progress. Thanks again to everyone for the valuable input and your patience.

**Comment by ar090** [comment]
Thanks @MiaofeiWang thats great news. We have one admin deployed customer who experiences this problem more than the rest. There are still cases where we experience this problem outside of that. I'm sure you know that just wanted to make sure. Exciting to have some improvements here though! And yes that workaround has been helpful in the interim thank you.

**Comment by 4tti** [comment]
Hello, @MiaofeiWang, do we have some ETA? Thanks a lot.

**Comment by MiaofeiWang** [comment]
@4tti The fix has been checked in this week, and it will be available in Beta channel early next week. 
Please note this fix should be able to resolve most #NAME? errors, but maybe not all. We are still actively investigating if any missing failure cases.

**Comment by 4tti** [comment]
Awesome @MiaofeiWang! And how long does it take usually to get to current channel?
Thanks a lot for the updates ❤️

**Comment by MiaofeiWang** [comment]
@4tti We just backported this fix to July fork. So if everything goes well, it will get to current channel Production early September.

**Comment by ar090** [comment]
great news @MiaofeiWang thanks! I just want to confirm to level my expectations. this will _only_ impact customers experiencing this issue that deploy plugins through an admin, not users that just self install via the store is that correct?

**Comment by MiaofeiWang** [comment]
@ar090 Thank you for your question. I’d like to take this opportunity to share more details about the fix:
In our latest investigation, we identified scenarios—particularly with add-ins deployed by administrators—where the function JSON metadata is present, but the functions themselves are not triggered for registration. The recent fix addresses this by re-registering the functions in such cases. This re-registration process applies uniformly, regardless of whether the add-in was deployed via admin or through the store, so we expect it to benefit both deployment paths.

While this fix may not resolve all instances of the #NAME? error, we believe it will improve the reliability of existing workarounds—such as clicking the add-in button to open a task pane or selecting the add-in from the “Add-ins” dropdown menu.

Meanwhile, we’re continuing to investigate other root causes and are working toward a more comprehensive solution.

**Comment by ar090** [comment]
Thats great news makes sense @MiaofeiWang thanks a ton. Keep us posted on the release 🙏

**Comment by ar090** [comment]
@MiaofeiWang did this end up rolling out anywhere? seem to be seeing an uptick of this issue again users on office.js -> `16.0.18925.20216`

**Comment by MiaofeiWang** [comment]
@ar090 Build 2508 (version 16.0.19127.20154), which includes this fix, is rolling out to the Current Channel Production. However, version 18925.20216 is the latest build of the Monthly Enterprise Channel, and I am afraid users on this channel will not receive this fix until the build updates to 19127.

**Comment by vpanchal-jha** [comment]
@MiaofeiWang
Any idea when the target build with this fix is planned to roll to Current Channel Production?

**Comment by MiaofeiWang** [comment]
@vpanchal-jha Is your add-in using [dialog API](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins), especially for log-in? If yes, you may still need to wait—it’s expected to be ready by the end of this month. If no, the fix has been in CC Production.

**Comment by 4tti** [comment]
@MiaofeiWang  Does dialog API causes these issues? 😮 
Interesting.

**Comment by MiaofeiWang** [comment]
@4tti To clarify, the #NAME issue is not caused by the Dialog API itself. We are actively investigating and addressing different root causes of #NAME issues, and as mentioned earlier, a fix (for the scenario of admin deployed add-in) have already been deployed to CC Production.

During our recent investigation, we discovered that a previous change exposed a scenario where opening a dialog could trigger this issue. We have implemented a fix for this dialog-related case, but it will take some time before it reaches CC Production.

In the meantime, if you encounter a function installation failure due to this dialog scenario, you can use this workaround: sign in through the dialog once, then close and reopen Excel without clearing the cache. After that, your functions should work as expected without requiring another sign-in.

**Comment by 4tti** [comment]
Thanks @MiaofeiWang for the info!

**Comment by Saad-Akbar-1** [comment]
@MiaofeiWang My add-in uses dialog API and we are still facing these issues. Can you explain on the exact timelines when the fix will be deployed to various Excel builds. Some of us use Excel on Desktop (for both mac and windows) and some use Microsoft 365 Excel and Excel on the web. So far Excel web has been the most stable for us.

**Comment by MiaofeiWang** [comment]
@Saad-Akbar-1 Sorry to know that. The fix is rolling out to different channels. Here are some **expected** dates that can get the latest build with the #NAME fix related to dialog.

Excel on Windows:
- Beta Channel: 9/20/2025
- Current Channel Production: 9/30/2025
- Monthly Enterprise Channel: 10/18/2025

Excel on Mac:
- Beta Channel: 9/16/2025
- Current Channel Production: 9/30/2025

In the meantime, if opening the dialog leads to #NAME issue, can you try with the workaround: sign in through the dialog once, then close and reopen Excel without clearing the cache? Thank you.

**Comment by Saad-Akbar-1** [comment]
@MiaofeiWang Has the update been pushed through?

**Comment by MiaofeiWang** [comment]
Hi @Saad-Akbar-1 , yes, builds with the fix for dialog API have been released to both Beta Channel (Windows >=19315.2000, Mac >= 16.102.25092340) and CC Production (Windows >= 19127.20264, Mac >= 16.101.25092825). MEC doesn't have this dialog issue. Please update to the latest version and try with the fix. Thank you.

**Comment by Saad-Akbar-1** [comment]
hi @ar090 Can you confirm if the issue has been fixed for you? I'm still facing this issue and the appearance of the issue seems to be erratic for me.

**Comment by MiaofeiWang** [comment]
Hi @Saad-Akbar-1, sorry to hear you're encountering this issue. Could you clarify whether you're seeing an intermittent #NAME? error or if it's more frequently reproducible after specific steps? It would be helpful if you could share more details—such as the add-in name, how it was installed (via the Office Store or deployed by an admin), and the scenarios where the error occurs.
We’ve already released a fix for add-ins deployed by tenant admins, and we’re currently working on further improvements to stabilize the issue for add-ins acquired from the Office Store.

**Comment by Saad-Akbar-1** [comment]
@MiaofeiWang The reproductions steps are very simple. I have the Add-in deployed via Admin for me. Open up any excel file. Navigate to Add-in tab. Login through our dialog. Add some custom functions. Close the excel file. On next open of the file. The functions are stuck with #NAME error. 
The Add-in name is Maiden Century Add-in for Excel.

**Comment by MiaofeiWang** [comment]
Hi @Saad-Akbar-1 , Thank you for sharing the details. I tested your add-in but couldn’t reproduce the issue. Since I don’t have an account, I was only able to open the login dialog without actually signing in.
Here’s my screen recording for reference: https://github.com/user-attachments/assets/581ccc91-fe34-4b53-a2ee-839fc5b4a64f

Could you please share a screen recording from your side as well? Also, to help us narrow it down, could you share your Excel build details—version & build number and update channel (Beta/Current Channel), plus the platform (Windows/Mac/Web)?

**Comment by ar090** [comment]
Sorry @Saad-Akbar-1 i am just now seeing your response. I don't want to jinx it but I think we are seeing this issue less. That could be a side effect of two things:
1) The fixes the team has been making are working
2) Our users have become conditioned to clicking our add-in from the add-ins menu which forces it to reload (our solution we taught them prior to these fixes - see above)

We've noticed that opening the taskpane for our add-in through the method in #2 solves a host of issues. Sometimes our users report #Busy errors that hang forever when they go to calculate our addin's formulas. It is as if the add-in hasnt loaded the custom functions all the way similar to the issues reported above. What is worse is we cant really debug these as opening taskpane for console logs fixes the issue. @MiaofeiWang not sure if this could be another side effect of the same problem?

I agree in it being "erratic" as you described as we are unable to consistently replicate. We are hoping the work @MiaofeiWang's team is doing will improve stability all around and I think the truth is a combination of 1 + 2 above.

**Comment by MiaofeiWang** [comment]
Hi all, we’ve introduced additional improvements in version 2511 (build 19426.20002) to enhance stability for custom function registration. These changes are now available in latest Beta Channel and Current Channel Preview.
Please try the updated build and let us know if this resolves more of the #NAME? issues in your add-ins. Your feedback will help us confirm the effectiveness of these fixes. Thank you.

**Comment by iambacon** [comment]
### Persistent #NAME? errors with streaming custom functions in Shared Runtime

**Excel versions**
2508 - Semi‑Annual Enterprise Channel
2511 & 2512 - Mothly Enterprise Channel

We are experiencing a persistent issue with a Shared Runtime add-in using streaming custom functions. The issue is most notable when opening a workbook from a Network Drive. The deployment is via Admin Managed.

When the issue occurs, we see a complete desync between the Excel calculation engine and the UI:
 1.  Engine State: `context.workbook.application.calculationState` returns `Pending`. Excel is stuck waiting for a calculation to finish.
2.  Cell Value: `range.values` returns `#CALC!`. The engine has flagged the cell as "calculation needed."
3.  UI/Grid: `range.text` returns `#NAME?`. The UI layer does not recognise the function name.
4.  JS Runtime: invocations remain empty. Despite the engine being "Pending," it never dispatches the call to the JavaScript associate bridge.

This is highly reproducible when opening workbooks from network shares. Even though the JavaScript runtime eventually loads, calls `Office.onReady`, and executes `CustomFunctions.associate()`, the calculation engine remains in this "Pending" deadlock and never reconnects to the now-ready JS runtime.

Attempted Workarounds (Failed):
- Script Prioritisation: We reordered Webpack chunks to ensure associate() is called before heavy UI bundles.
- Plugin Upgrade: Upgraded `custom-functions-metadata-plugin` to v2.x.
- Force Recalculation: Ctrl + Alt + F9 (Full Rebuild) does not clear the state; the engine remains Pending and the cells remain #NAME?.

The only way for users to recover from this is to click the Add-ins command button in the home tab and click the add-in. This appears to do some re-registering magic to start the streaming custom functions up.

@MiaofeiWang
