### ISSUE TITLE
Excel Add-in installation issues

### ISSUE THREAD

**Issue by shaun-pendrigh** [OfficeDev/office-js#6093]
I have a production Excel Add-in that has been running for 2 years. Over the last 24 hours I have had numerous customers report issues with the Add-in connecting to Excel. We have not updated the app on Appsource for many months and our server was last updated with changes on 20 August. I am there assuming these issues cannot be related to our app. Issues reported are:

1. Receive error message "Error installing functions" but the everything seems to be working, event the functions. This is happening for me in my development environment too.
2. The Add-in disappears completely from Excel without any message.
3. Repeatedly get the message to "Accept and Continue" sometimes working after clicking accept but other times the Add-in disappears.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop and Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2508 Build 16.0.19127.20192) 64-bit 
* Operating System: Windows 11 and Mac
* Browser (if using Office on the web): N/A
 
## Expected behavior
These are existing customers that have used the Add-in before. So expected behavior is that they should just launch Excel and use the app as before.

## Current behavior
As detailed above - various errors.

## Steps to reproduce
This is difficult as mentioned these are existing customers that have used our Add-in for a long time without issues.
1. Install the Flash Reports Add-in
2. Click the login button on the Flash Reports toolbar
3. This shows me the "Error installing functions" message. But I cannot recreate the behavior some of the customers are seeing.

## Link to live example(s)
N/A

# Provide additional details
None

## Context
Production customer are not able to use our application.

## Useful logs
No logs are produced. If there is a way to get a log of the Add-in installation process that Excel does I would love to know how.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends. 

<img width="504" height="385" alt="Image" src="https://github.com/user-attachments/assets/1edbd9f7-bdaa-4191-8aa2-05a840028fb8" />

<img width="580" height="192" alt="Image" src="https://github.com/user-attachments/assets/a1f14f8f-0017-4cd1-9fff-b97c10a3a48e" />

**Comment by theRealHaojiangLiu** [comment]
Hi @shaun-pendrigh, thanks for reporting, but I have only reproduced for the issue#1 in my local. Could you please confirm with the customers about that the issue#2 and issue#3 still happen? We have created an internal bug(#10551319) to follow the issue#1. We will report back here if we have a suggestion for you.

**Comment by shaun-pendrigh** [comment]
Thank you @theRealHaojiangLiu. I am trying to get time scheduled with one of the customers to see if I can work out how to recreate the other errors.

Do you know what the next steps are to investigate this and how long it will take? Should I be logging a ticket anywhere else to get support or is this the correct place? This is a big problem for us as the customers are not able to execute their financial reports in our product.

**Comment by theRealHaojiangLiu** [comment]
Hi @shaun-pendrigh, here is the right place to report the bug. We couldn't reproduce Issue#2 and Issue#3 so that we are focusing on Issue#1. If Issue#2 and Issue#3 are still reproduced in your customer, could you help provide the repro video? Thanks.

**Comment by MiaofeiWang** [comment]
Hi @shaun-pendrigh, as @theRealHaojiangLiu mentioned, we’re currently focusing on resolving the first issue related to the login dialog. A fix is in the process of being rolled out.
In the meantime, could you please try the following workaround:
1. Click “Login” to open the login dialog and sign in. You may still see the error message, and custom functions might not work at this point.
1. Close Excel completely and then reopen it. **Do not** clear cache.
1. After reopening Excel, you should be logged in automatically so no need to open the "Login" dialog. Please check if the custom functions are now working as expected.

**Comment by shaun-pendrigh** [comment]
Thanks @MiaofeiWang 

Thanks for that advice. I have noticed that the error only occurs when we click the login button. And once you are logged in that error does not show on a subsequent session. And the custom functions are working. However some users are also reporting other issues, that I cannot recreate on my environment. I am hoping that whatever fix resolves this "Error installing functions" issue will also fix the other issues that some users are experiencing.

Just some other information that I have found, maybe not relevant if you are already working on a fix. But I tested on an old PC today that did not have the latest office updates. It was on this version, and this "Error installing functions" did not occur.

<img width="914" height="173" alt="Image" src="https://github.com/user-attachments/assets/bfc2b673-7006-4fa0-94c1-e9334bdac2af" />

<img width="1719" height="169" alt="Image" src="https://github.com/user-attachments/assets/e0a35d77-a470-4622-ae19-3c4eccbe56a5" />



I then ran the updates and the version went to this, and the error started occurring.

<img width="921" height="165" alt="Image" src="https://github.com/user-attachments/assets/3f4f38b6-a38d-4cbd-8795-0c291d6f6945" />

**Comment by MiaofeiWang** [comment]
Our current fix is focused on the consistently reproducible "Error installing functions" issue. As you've correctly identified, this error was introduced by a recent update. We’ve already developed a fix and are in the process of rolling it out.

Regarding the other issues, I’m not entirely certain, but to the best of my knowledge, a similar problem involving repeated "Accept and Continue" prompts has already been resolved. Since you're unable to reproduce it now, we hope your customer is encountering the same issue that has been addressed.

**Comment by shaun-pendrigh** [comment]
Thanks @MiaofeiWang, I will try and get online with the other customers and see what errors are still occurring. Thank you for your help and quick responses.

**Comment by shaun-pendrigh** [comment]
@MiaofeiWang @theRealHaojiangLiu I see there were office updates that installed today but the error is still occurring? Is there any update on when this will be fixed? My customers continue to experience strange issues which have all started recently. And our application has not been updated for more than a month meaning these issues are not related to any changes on our side. Somehow they must be linked to this issue with the custom function installation. It is causing a huge support load on our end and we are very eager to get this resolved and have our customers get back to smooth operation of the application. But it is out of our hands. Please can you give me an update on the status? Thanks

**Comment by MiaofeiWang** [comment]
Hi @shaun-pendrigh We truly apologize for the continued trouble this issue is causing you and your customers.
The fix for the custom function installation issue is planned to be included in the next update, which is expected to be available by the end of next week. We’ll keep you posted as soon as it’s available. Really appreciate your patience and understanding in the meantime.

**Comment by evelyn-chrono** [comment]
@MiaofeiWang do you know which update version will contain the fix for this issue?

**Comment by MiaofeiWang** [comment]
Hi @evelyn-chrono The build with the fix has been deployed to Beta (version 2510, build 19315.20000) and CC Preview (build 2509, build 19231.20116). It is rolling out to CC Production (version 2508, build 19127.20264) and you should be able to see the update in 1-3 days if not yet. 
@shaun-pendrigh FYI.

**Comment by shaun-pendrigh** [comment]
Thanks @MiaofeiWang and @theRealHaojiangLiu this update has become available and customers are testing. So far it seems to be resolving all the issues we have experienced. Thanks for your help with this. I presume the issue can be closed?

**Comment by MiaofeiWang** [comment]
@shaun-pendrigh Thank you for confirmation. I will close this issue.

**Comment by evelyn-chrono** [comment]
@MiaofeiWang @RuizhiSunMS @theRealHaojiangLiu Do you know if this issue has been fixed in Monthly Enterprise Channel?

We have users running Version 2508 (Build 19127.20314) experiencing a similar issue.

**Comment by MiaofeiWang** [comment]
Hi @evelyn-chrono,

The issue that opening a dialog could trigger *“Error installing functions”* and block custom function installation has been fixed in Version 2508. Users on 2508 (and later) should no longer be blocked by this interaction. 
In some cases, the status bar can still appear even though custom functions work as expected (a false alert). An additional fix for the message is rolling out to Beta Channel (build line 16.0.19417.20000).

Please ask affected users to confirm whether their custom functions **actually calculate** despite the error prompt (e.g., enter a known function and check results). Also share the exact **channel + build** (Excel → *File* → *Account* → *About*). Thanks for helping us validate on your side!
