### ISSUE TITLE
Add-in appears in Mac Outlook for a split second and disappears forever

### ISSUE THREAD

**Issue by esegcy** [OfficeDev/office-js#787]
When launching Mac Outlook v16.29 on MacOS Mojave, with only one email account setup, and the add-in deployed with Centralized Deployment from a manifest file, I see the add-in appear for a split second in this Mac Outlook, and then it disappears and never re-appears.

## Expected Behavior
Add-in should constantly appear, and never disappear.
Of course I am testing the add-in according to its activation rules (meaning I expect it to be shown when reading an email). Outlook is setup with reading-pane, so it should appear when launching (but I also tested when reading different emails and when opening an email in a new window).

## Current Behavior
Add-in only appears for a split second, and then disappears forever.

## Steps to Reproduce, or Live Example
1. Use Centralized Deployment to deploy an add-in from manifest file to an Office 365 account.
2. Restart Outlook to get the add-in.
3. Bug: the add-in appears for a split second, and then disappears forever.

## Context
This issue is reproducing consistently on a specific end-user's Mac, which is an out-of-domain computer; but is not reproducing on other devices we have with similar OS and Outlook versions. How can we help you troubleshoot what's specifically wrong with this (important) end-user's Mac?

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Mac Outlook v16.29
* Office version number: 16.29
* Operating System: MacOS Mojave
* Browser (if using Office Online): -

**Comment by macOutlookExtensibility** [comment]
Hello, thanks for reporting this. 
We are trying to repro this issues at our end. A couple of questions more,

1) does this issue appear on other platforms like Windows and Outlook web (in case your add-in manifest supports other platforms)
2)Can you give details of the user account? (admin or user account?/ account alias)
3)Can you see if the add-in appears under the _My Add-ins_ sections of in-app store? (Outlook ribbon->Get Add-ins icon->in-client Store->My Add-ins section)

**Comment by esegcy** [comment]
Hi,
Thanks for replying. Answers:
1. So far it only happens on one end-user's Mac device. I could not reproduce this as well. 
2. This email account is of an IT administrator with admin permissions.
3. Yes, it appears. But keep in mind it was deployed through Centralized Deployement, so it appears there with the note "Required by your administrator".

I could not find documentation on how it is possible to turn on add-in launch logs in Mac Outlook, so maybe you can direct me on how to supply you with logs or anything similar from this end-user that might help?

**Comment by macOutlookExtensibility** [comment]
thanks for the information,
ok, so this is an issue that happens only on Mac and the user is able to view the add-in on Outlook web or Windows.

Could you provide us with the following :
1) Manifest of the add-in
2) Domain/Alias of the end user (IT admin)

this is important for us while we check the logs

**Comment by esegcy** [comment]
Summary is correct, but please note there's a different error we're seeing in Win (reported here in issue #786).
As these details you further requested might be considered confidential to our company, can I email them privately to you somehow?

**Comment by AnjanaValsan** [comment]
Hello @esegcy ,
thank you for reporting this issue and also for your patience. This issue is related to issue #786 
It was fixed end of last week, Can you check and confirm?

**Comment by esegcy** [comment]
Hi @AnjanaValsan ,
Are you sure they are really related, even though the problems themselves are different, and that one of the issues is in Mac Outlook and the other is in Windows Outlook?

If so, anything I should do in order to see this fixed? Update Outlook or something? If so, to which version/build-number?

Thanks.

**Comment by macOutlookExtensibility** [comment]
Hi, @esegcy , you could restart Outlook and try once. If you are still facing challenges, kindly update here.

**Comment by esegcy** [comment]
Testing. Will update here.

**Comment by esegcy** [comment]
@macOutlookExtensibility , @AnjanaValsan , Unfortunately on Mac the add-in still comes up and then disappears almost straight away (without re-appearing).
So not fixed 😞 Do you want me to email you a recording (I can't post it here, see previous comments)?

**Comment by macOutlookExtensibility** [comment]
Hello @esegcy , can you clear your add-ins cache on Outlook mac and try once? the procedure to clear cache is 
1) go the this location on your machine-> delete /Users/<user>/Library/Group/Containers/<U????????>.OfficeOsfWebHost
2) delete the items under this folder
3) Restart Outlook Mac.

**Comment by esegcy** [comment]
Done. Doesn't help 😭 issue still reproducing.

**Comment by macOutlookExtensibility** [comment]
Hi @esegcy  sure, no worries. We will investigate further,

Could you provide us with the following :
1) Manifest of the add-in
2) Domain/Alias of the end user (IT admin)
this is important for us while we check the logs
3)screen recording of the issue and clearing of cache

Drop an email to this id meganb@M365x887143.onmicrosoft.com
